### ISSUE TITLE
Remove useless PHPDoc tags

### ISSUE THREAD

**Issue by ntzm** [FriendsOfPHP/PHP-CS-Fixer#3690] opened 2018-04-07 22:39 UTC
As suggested by https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3651#issuecomment-377224053

```diff
 /**
  * Does foo.
  *
  * @param string $bar Has a description so shouldn't be removed
- * @param mixed $baz
- *
- * @return array
  */
 function foo(string $bar, $baz): array
 {
 }
```

**Comment by Slamdunk** [comment] 2018-04-08 12:02
Little note: run this after #3640

**Comment by julienfalque** [comment] 2018-04-08 12:58
Currently covered by #3110.

**Comment by julienfalque** [comment] 2018-04-08 16:02
This is actually a duplicate of #2979.

**Closed by julienfalque** 2018-04-08 16:02 UTC
Labels: feature request
