### ISSUE TITLE
Spaces get removed in multiple exceptions in a catch when have both @PSR12 and @PhpCsFixer enabled

### ISSUE THREAD

**Issue by jfcherng** [FriendsOfPHP/PHP-CS-Fixer#6132] opened 2021-11-28 05:22 UTC
## Bug report

I believe @PhpCsFixer doesn't mean to break PSR12 hence a bug report. As per [PSR12](https://www.php-fig.org/psr/psr-12/):

```
5.6 try, catch, finally
A try-catch-finally block looks like the following. Note the placement of parentheses, spaces, and braces.

<?php

try {
    // try body
} catch (FirstThrowableType $e) {
    // catch body
} catch (OtherThrowableType | AnotherThrowableType $e) {
    // catch body
} finally {
    // finally body
}
```

Spaces in the above codes should stay intact after formatting but the following happens.

```diff
-} catch (OtherThrowableType | AnotherThrowableType $e) {
+} catch (OtherThrowableType|AnotherThrowableType $e) {
```

* PHP version: 8.0.13
* PHP CS Fixer version: v3.3.2
* the command used to run PHP CS Fixer: `$ php-cs-fixer fix`
* the configuration (file) you used:

  ```php
  <?php

  return (new PhpCsFixer\Config())
      ->setIndent('    ')
      ->setLineEnding("\n")
      ->setCacheFile(__DIR__.'/.php-cs-fixer.cache')
      ->setRules([
          '@PSR12' => true,
          '@PhpCsFixer' => true,
      ])
      ->setFinder(
          PhpCsFixer\Finder::create()
              ->in(__DIR__)
              ->exclude('vendor')
      )
  ;
  ```

### Code snippet that reproduces the problem

```php
<?php

declare(strict_types=1);

try {
    // try body
} catch (FirstThrowableType $e) {
    // catch body
} catch (OtherThrowableType | AnotherThrowableType $e) {
    // catch body
} finally {
    // finally body
}
```

**Comment by SpacePossum** [comment] 2021-11-28 11:53
Thanks for reporting, I suspect it is a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6102 , let me know if not than I'll reopen :+1:

**Closed by SpacePossum** 2021-11-28 11:53 UTC
Labels: kind/bug
