### ISSUE TITLE
constant_case suggests to use upper case for null and false types

### ISSUE THREAD

**Issue by KacerCZ** [FriendsOfPHP/PHP-CS-Fixer#5764] opened 2021-06-08 06:35 UTC
## Bug report

When PHP CS Fixer is configured to use upper case constants, it also tries to change case of `null` and `false` when they are used as type.

Using PHP CS Fixer 3.0.0 run on PHP 8.0.5 with following config:
```php
<?php

$finder = \PhpCsFixer\Finder::create()
        ->in( __DIR__ )
        ->path( '/^*.php/' );

$rules = [
        'constant_case' => [ 'case' => 'upper' ],
];

$config = new \PhpCsFixer\Config();
$config->setRules( $rules )
        ->setFinder( $finder );

return $config;

```

### Code snippet that reproduces the problem
Save content to file `constant_case.php`>
  ```php
<?php

$correct = NULL;

function foo( int|string|false|null $param ) {
        // body
}
```

Run `vendor/bin/php-cs-fixer fix -v --dry-run --diff constant_case.php`.

Following fix is suggested:
```
   1) constant_case.php (constant_case)
      ---------- begin diff ----------
--- /home/kacer/github/phpcs-fixer-bugs/constant_case/constant_case.php
+++ /home/kacer/github/phpcs-fixer-bugs/constant_case/constant_case.php
@@ -2,7 +2,7 @@
 
 $correct = NULL;
 
-function foo( int|string|false|null $param ) {
+function foo( int|string|FALSE|NULL $param ) {
 	// body
 }
```

Expected result is that no error is reported.

**Comment by keradus** [comment] 2021-08-03 10:26
> When PHP CS Fixer is configured to use upper case constants, it also tries to change case of null and false when they are used as type.

I'm not convinced that it's actually wrong.
you configured you want them in upper.

**Comment by SpacePossum** [comment] 2021-08-31 20:09
seems to work as intended, closing as `won't fix`

**Closed by SpacePossum** 2021-08-31 20:09 UTC
Labels: kind/bug

**Comment by KacerCZ** [comment] 2021-09-06 13:41
@keradus I think that check should treat `null` and `false` based on their usage in code.
If used in assignment or as default parameter value or as default property value, then it **is constant** and case should be checked.
Example: `$success = FALSE;`

If used as **part of type definition** then case should not be checked.
Example: `function convert(string|int|null $value): string|false {}`

This is similar to different handling of pipe (`|`) in expressions and in type union.
