### ISSUE TITLE
Place each block of code in new line

### ISSUE THREAD

**Issue by shhlkien** [FriendsOfPHP/PHP-CS-Fixer#5046] opened 2020-07-07 12:05 UTC
## Rule request

I want to place each block of code (such as `if else`, `try catch`, etc) in new line instead of same line as current, it's good for coding or debugging.

##### Unformatted code:
```php
<?php
if (condition) {
      echo 'a';
} else if (other conditions) {
      echo 'b';
} else {
      echo 'c';
}
```
##### Expected result:
```php
<?php
if (condition) {
      echo 'a';
} 
else if (other conditions) {
      echo 'b';
} 
else {
      echo 'c';
}
```

**Comment by julienfalque** [comment] 2020-07-07 12:13
Duplicate of #4178.

**Closed by julienfalque** 2020-07-07 12:13 UTC
Labels: kind/feature request
