### ISSUE TITLE
Priority issue between "braces" and "method_argument_space"

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#4657] opened 2019-11-22 09:31 UTC
#### The PHP version you are using (`$ php -v`):
=> 7.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.0

Run `@PSR2` rule on https://github.com/PrestaShop/PrestaShop/blob/1.6.0.5/admin-dev/filemanager/include/utils.php and notice, that the CS fixer needs to be run twice to produce stable/fully fixed result.

**Comment by keradus** [comment] 2019-11-24 12:44
can you provide a full bug report template with minimal code samples , please? that would ease how to deal with the issue

**Comment by SpacePossum** [comment] 2020-01-08 07:29
Closing for now as the required input to continue working on this issue has not be provided.
If we get the details than I'm happy to reopen so we can continue on this.

**Comment by mvorisek** [comment] 2020-01-08 07:53
@SpacePossum Please run the `PSR2` rule with the latest release on the file in the bug report and notice, that the fixer needs to be run twice to "stabilize".

**Comment by julienfalque** [comment] 2020-01-08 08:01
I confirm that the `@PSR2` ruleset needs to run twice to fix the example file. Probably a priority issue.

**Comment by julienfalque** [comment] 2020-01-08 08:03
This does not seem to be related to `$x++` conversion to `++$x` though. The issue title might need to be updated once we know exactly what the bug is.

**Comment by SpacePossum** [comment] 2020-02-11 09:14
assigning because I still cannot reproduce this issue locally

**Comment by SpacePossum** [comment] 2020-02-18 07:48
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4807

**Closed by SpacePossum** 2020-02-18 07:48 UTC
Labels: kind/bug
