### ISSUE TITLE
How to remove spacing around multiple type hints

### ISSUE THREAD

**Issue by mattkingshott** [FriendsOfPHP/PHP-CS-Fixer#5489] opened 2021-02-04 11:49 UTC
## Support question

Right now, CS Fixer is creating spaces either side of the pipe separators with multiple type hint parameters e.g.

`public function test(int | float | string | null $arg)`

How do I get it to remove these so it becomes like so:

`public function test(int|float|string|null $arg)`

The same also applies to return types.

Thanks!

**Comment by jameslkingsley** [comment] 2021-03-04 11:57
This temp solution worked for me https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5495#issuecomment-777187487

**Comment by mattkingshott** [comment] 2021-03-04 13:46
Thanks for posting, but this doesn't seem to work for me...

```php
'binary_operator_spaces' => [
    'align_double_arrow' => true,
    'align_equals' => true,
    'operators' => ['|' => null]
],
```

**Comment by kubawerlos** [comment] 2021-03-09 23:14
Currently removing spaces is not possible.

Only possible is to remove the spaces manually and configure Fixer not to add them back.

Feature request to add this behaviour is here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5495 so this one is kind of duplicate of it.

**Closed by kubawerlos** 2021-03-09 23:14 UTC
Labels: kind/question
