### ISSUE TITLE
no_superfluous_phpdoc_tags needs an option to allow params that aren't on the signature

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#4504] opened 2019-08-14 11:58 UTC
In Symfony, it's quite typical to find signatures like:

`public function foo($a, $b/*, $c = null*)`

we do this when we want to add an argument in a BC-compatible way.
when we do this, we also add an `@param ... $c` in the docblock to be explicit.

`no_superfluous_phpdoc_tags` currently removes this `@param`, but we don't want it to do that.

**Comment by julienfalque** [comment] 2019-08-14 14:38
Duplicate of #3933.

**Closed by julienfalque** 2019-08-14 14:38 UTC
