### ISSUE TITLE
no_spaces_around_offset fixer mailforms Array Destruct from PHP 7.1

### ISSUE THREAD

**Issue by TomasVotruba** [FriendsOfPHP/PHP-CS-Fixer#2454] opened 2017-01-07 22:32 UTC
![faillll](https://cloud.githubusercontent.com/assets/924196/21745697/640fc1e0-d531-11e6-9211-72129ad192b2.png)

[Array Destruct feature in PHP 7.1](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring)

The PHP version you are using:
**7.1**

PHP CS Fixer version you are using:
**2.0**

The command you use to run the fixer:

```bash
vendor/bin/php-cs-fixer fix packages --rules=no_spaces_around_offset --diff --dry-run -v
```

A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```php
if (! $controllerName = $request->attributes->get('_controller')) {
    return false;
}

[$class, $method] = $this->splitControllerClassAndMethod($controllerName);
```

The fixed version of that code after you run the fixer:

```php
if (! $controllerName = $request->attributes->get('_controller')) {
    return false;
} $method] = $this->splitControllerClassAndMethod($controllerName);
```

And the version you expected: *no fixes*

**Comment by GrahamCampbell** [comment] 2017-01-07 23:47
Thanks for the report. Lack of support for this construct is docuemted already in this issue: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2090.

However, actual breakage of code is not the same as lack of support. This is definitely a bug. :)

**Comment by keradus** [comment] 2017-01-08 16:17
actually we claimed to support it with introduction of custom token. we do not have dedicated fixers, but syntax should be supported.

thanks for report

**Comment by SpacePossum** [comment] 2017-01-09 13:47
FYI: the problem is in the SquareBraceTransformer transformer, I might be able to look at this the upcoming days I hope.

**Comment by SpacePossum** [comment] 2017-03-30 15:10
should be fixed now https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2475 is merged, 
let me know if it isn't @TomasVotruba

**Closed by SpacePossum** 2017-03-30 15:10 UTC
Labels: bug

**Comment by TomasVotruba** [comment] 2017-03-30 15:49
Thank you!

**Comment by SpacePossum** [comment] 2017-03-30 16:53
you're welcome :D
