### ISSUE TITLE
@return before @throws in phpdoc_order

### ISSUE THREAD

**Issue by BenMorel** [FriendsOfPHP/PHP-CS-Fixer#6422] opened 2022-06-11 21:56 UTC
## Feature request

Would it be possible to get **`@return` before `@throws`** in the `phpdoc_order` rule?

Sorry if this has been asked before, I've been unable to find a related issue or PR.

**Comment by SpacePossum** [comment] 2022-07-17 05:38
will be fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6466

**Comment by julienfalque** [comment] 2022-08-07 17:28
Duplicate of #1602.

**Closed by julienfalque** 2022-08-07 17:28 UTC
Labels: kind/feature request
