### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by mega-n3ss** [FriendsOfPHP/PHP-CS-Fixer#2114] opened 2016-08-05 10:35 UTC
Hi there,

My file are so long and it's difficult to know where the CS errors are.
What can i do to see the line number ? Can you put line number please ?

Best,

**Comment by keradus** [comment] 2016-08-05 10:41
Hi !

Currently you have no option for that.
If you want that feature please contribute.

Closing as duplicate of #1620

**Closed by keradus** 2016-08-05 10:41 UTC
