### ISSUE TITLE
Mirroring issues

### ISSUE THREAD

**Issue by JBleijenberg** [FriendsOfPHP/PHP-CS-Fixer#2098] opened 2016-07-25 11:35 UTC
Whenever i try to create a mirror of this package (the original package is required by Magento2) with Satis, i get the following error

`  [PharException]
  tar-based phar "/private/var/folders/8c/rtrl_2sj3ldggkpnrcpjr3c40000gn/T/composer_archive5795f901a61ca.tar" cannot be created, filename "tests/Fixtures/Integration/misc/simplified_null_return,no_useless_return,no_whitespace_in_blank_line,blank_line_before_return,no_e
  xtra_consecutive_blank_lines.test" is too long for tar file format`

What is going wrong here?
(I know what's going wrong here, the filename is too long. But please fix it)

**Comment by SpacePossum** [comment] 2016-07-25 12:20
which app/spec. states the name is too long?

**Comment by keradus** [comment] 2016-07-25 13:48
http://php.net/manual/en/phar.fileformat.tar.php

we are building phars without any problems.

also, why there is tests folder in your phar ?

**Comment by JBleijenberg** [comment] 2016-07-27 07:20
@keradus because it's in the package on packagist. And satis repackages eveything when it creates a mirror.

**Comment by JBleijenberg** [comment] 2016-07-27 07:20
Btw. I can still use 1.11, after that i get this error

**Comment by JBleijenberg** [comment] 2016-07-27 07:22
@SpacePossum Satis uses Composer to recreate the package. That's where the error pops up

**Comment by SpacePossum** [comment] 2016-07-27 07:43
I see, would a `.gitattributes` help?

**Comment by keradus** [comment] 2016-07-27 08:00
also, do you know how phar file is created? as I assume it don't use our config for box.

**Comment by Slamdunk** [comment] 2016-08-12 12:41
`.gitattributes` is coupled with git archive, so if the phar is compiled from source retrieved in any method except the zip, the error remains.

**Comment by keradus** [comment] 2016-08-12 12:47
the error is very tricky to reproduce. we also build phar file and we have no issues with it

**Comment by keradus** [comment] 2016-09-04 19:46
@JBleijenberg could you check if this is still an issue on 1.12 ?

**Comment by JBleijenberg** [comment] 2016-09-05 13:09
@keradus it works in 1.12
But just a question out of curiosity, why is your master branch completely different from v1.12?
When i require >= 1.11, composer will satis will break when it tries to repackage dev-master.

**Comment by keradus** [comment] 2016-09-05 13:53
Great to here it's working! In that case I'm closing this issue, big thanks for raising it and checking it!

The `master` branch is dev line of 2.x version.
I have no idea why satis will fallbacking 1.11 to dev-master, for me it's wrong behaviour

**Closed by keradus** 2016-09-05 13:53 UTC

**Comment by eyalzek** [comment] 2019-02-07 09:33
I know this is an old issue, but I just experience the same thing trying to mirror `"friendsofphp/php-cs-fixer": "*"` with satis:
```
Dumping package 'friendsofphp/php-cs-fixer' in version '2.12.x-dev'.
  - Installing friendsofphp/php-cs-fixer (2.12.x-dev b6402cc): Cloning b6402ccc2b from cache

                                                                               
  [PharException]                                                              
  tar-based phar "/tmp/composer_archive5c5b88bde1e32.tar" cannot be created,   
  filename "tests/Fixtures/Integration/misc/simplified_null_return,no_useless  
  _return,no_whitespace_in_blank_line,blank_line_before_statement,no_extra_bl  
  ank_lines.test" is too long for tar file format                              
                                                         
```

Is there an obvious way to mitigate this issue?

**Comment by eyalzek** [comment] 2019-02-07 10:41
Just for reference, this is the minimal `satis.json` to reproduce this issue:
```
{
    "name": "Satis",
    "repositories": [
        { "type": "composer", "url": "https://packagist.org" }
    ],

    "archive": {
      "directory": "dist",
      "format": "tar",
      "skip-dev": false
    },

    "require": {
        "friendsofphp/php-cs-fixer": "*"
    },
    "require-all": false,
    "require-dependencies": true,
    "require-dev-dependencies": true
}```

and then run satis:
`php /satis/bin/satis -vvv --ansi build /tmp/satis.json /composer/build/output friendsofphp/php-cs-fixer`

setting `skip-dev` to `true` solves this, but not an ideal solution. Omitting `"format": "tar"`, or alternatively setting it to `zip` (the default) seems to solve this. Though I guess a better solution would be to fix it in this repositories source code level an rename https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixtures/Integration/misc/simplified_null_return,no_useless_return,no_whitespace_in_blank_line,blank_line_before_statement,no_extra_blank_lines.test ...

**Comment by keradus** [comment] 2019-02-07 11:46
`tests/Fixtures` folder is excluded already https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.14/.gitattributes#L5 , looks like `skip-dev: false` is explicitly saying to use files marked as ignored for export as well.

**Comment by eyalzek** [comment] 2019-02-07 11:55
Thanks for the info! Are you aware of any way around this ?

**Comment by eyalzek** [comment] 2019-02-07 16:04
Seems like I was able to overcome this by setting `config.preferred-instal: dist` and `archive.rearchive: true` e.g:

```
{
    "name": "Satis",
    "config": {
      "preferred-install": "dist"
    },
    "repositories": [
        { "type": "composer", "url": "https://packagist.org" }
    ],

    "archive": {
      "directory": "dist",
      "format": "tar",
      "skip-dev": false,
      "rearchive": true
    },

    "require": {
        "friendsofphp/php-cs-fixer": "*"
    },
    "require-all": false,
    "require-dependencies": true,
    "require-dev-dependencies": true
}

I hope this doesn't have other side effects that I'm not aware of.
