### ISSUE TITLE
2.17 versions support php 8 in composer, but not in executable

### ISSUE THREAD

**Issue by ctrl-f5** [FriendsOfPHP/PHP-CS-Fixer#5498] opened 2021-02-12 11:53 UTC
## Bug report

when installing php-cs-fixer on php 8.0.1 with `--prefer-lowest` it is impossible to run because:
- `composer.json` allows `"php": "^5.6 || ^7.0 || ^8.0"`
- executable stops execution: 

```php
if (!defined('PHP_VERSION_ID') || \PHP_VERSION_ID < 50600 || \PHP_VERSION_ID >= 70500) {
    fwrite(STDERR, "PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.4.*.\n");
    exit(1);
```

**Comment by keradus** [comment] 2021-02-12 11:58
Closing as duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5375
tl;dr - please update to newest version, v2.17 is no longer maintained

**Closed by keradus** 2021-02-12 11:58 UTC
Labels: kind/bug
