### ISSUE TITLE
Files having an 'include' statement are not scanned

### ISSUE THREAD

**Issue by Zzortell** [FriendsOfPHP/PHP-CS-Fixer#982] opened 2015-01-21 15:33 UTC
Hi !
When a file state an 'include', php-cs-fixer fix command doesn't analyse at all the file (but none error is thrown).

PS: This is entirely independant of using the 'include' fixer.

**Comment by keradus** [comment] 2015-01-21 16:25
That's odd.
Could you provide a detailed description with file example ?

**Comment by Zzortell** [comment] 2015-01-26 19:29
Ok, as soon as I find the time.

**Comment by stof** [comment] 2015-03-02 15:10
@Zzortell any news ?

**Comment by Zzortell** [comment] 2015-03-02 18:15
Wow, I completely forgot. And I'm a little busy currently, I will try to keep this in mind.

**Comment by keradus** [comment] 2015-04-07 20:45
Closing due to cannot reproduce

**Closed by keradus** 2015-04-07 20:45 UTC
