### ISSUE TITLE
[bug] The spaces of some control structures are not fixed

### ISSUE THREAD

**Issue by Rolige** [FriendsOfPHP/PHP-CS-Fixer#4090] opened 2018-11-10 16:24 UTC
I have detected this bug with the `switch`, if you check my examples below, you will see that the closing parenthesis of the `switch` it's not aligned and it is not fixed after applying the command.

#### The PHP version you are using (`$ php -v`):
=> 7.1.24 (Homebrew)

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.1 (Homebrew)

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix /path/test.php --rules=@Symfony --using-cache=no

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class MyClass
{
    private $var = 3;

    public function __construct()
    {
        switch ($this->var) {
            case 1:
                // code...
                break;

            default:
                // code...
                break;
          }
    }
}
```

 * with the changes you expected instead:
```php
<?php

class MyClass
{
    private $var = 3;

    public function __construct()
    {
        switch ($this->var) {
            case 1:
                // code...
                break;

            default:
                // code...
                break;
        }
    }
}
```

**Comment by SpacePossum** [comment] 2018-11-12 17:54
thanks for reporting, I think this is a duplicate of the issue reported here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/776

**Closed** 2018-11-12 17:55 UTC
Labels: duplicate

**Comment by Rolige** [comment] 2018-11-12 17:59
Hi @SpacePossum that issue is since 2014, is this already fixed?, how I can configure my file or which rule I need use to fix it?

regards!

**Comment by SpacePossum** [comment] 2018-11-12 18:04
Sorry to say that the issue has not been resolved, I would really like to see it in though, I guess no one found the time to make it :(
