### ISSUE TITLE
[Feature Request]Single/ multi line php doc fixer

### ISSUE THREAD

**Issue by BackEndTea** [FriendsOfPHP/PHP-CS-Fixer#3300] opened 2017-12-06 19:57 UTC
My suggestion would be a fixer that either enforces doc blocks with only one tag are
```php
/** @return string */
```
or 
```php
/**
 * @return string
 */
```

Possilby a configuration for allowing different doc blocks for functions and class properties.

If there is any demand for this i'll shoot a PR myself soon, since i made part of this already in #3275

**Comment by kubawerlos** [comment] 2017-12-06 20:14
Duplicate of #2646

**Comment by BackEndTea** [comment] 2017-12-06 20:41
My bad didn't see that one

**Comment by keradus** [comment] 2017-12-06 22:27
while feature request is still valid, I'm closing this one as duplicate.
yet, work on it would be more than appreciated ;)

**Closed by keradus** 2017-12-06 22:27 UTC
