### ISSUE TITLE
Any plans for sebastian/diff ^2.0 compatibility?

### ISSUE THREAD

**Issue by alcohol** [FriendsOfPHP/PHP-CS-Fixer#2993] opened 2017-08-22 06:38 UTC
As the title suggests; `sebastian/diff` has been out for a few weeks now. `phpunit` 6.3 and higher requires it, making a side-by-side install through `require-dev` impossible at the moment.

**Comment by SpacePossum** [comment] 2017-08-22 06:41
Hi and thanks for reporting!

This issue has been noted and is a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2962.
We are in the process of resolving this issue ASAP, please bear with us for a bit longer :)

**Comment by alcohol** [comment] 2017-08-22 06:49
Oh sorry, I could not find that one. But I was not looking for closed issue, I guess that explains it :-)

**Closed** 2017-09-23 14:20 UTC

**Comment by SpacePossum** [comment] 2017-09-23 15:49
Sorry for the wait @alcohol and all the upvoters of this issue.
It took me longer than I wanted, but here we are, free of the `diff 1.4 dep`. 

For now only on master, will become part of the next minor release of the project.

**Comment by alcohol** [comment] 2017-09-25 06:21
No need to apologize. Appreciate all the amazing work everyone on this project puts in. Thanks!
