### ISSUE TITLE
Generic type is broken by fixer

### ISSUE THREAD

**Issue by b1rdex** [FriendsOfPHP/PHP-CS-Fixer#5064] opened 2020-07-23 09:15 UTC
Code block
```php
/**
 * @var \Some\Long\Namespaced\Class\Name $this
 * @var array<string, array> $options
 */
```
is fixed to
```php
```php
/**
 * @var \Some\Long\Namespaced\Class\Name $this
 * @var array<string,                    array> $options
 */
```
Config file:
```php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/src');

$rules = [
    '@DoctrineAnnotation' => true,
    '@PSR2' => true,
    '@Symfony' => true,
    'align_multiline_comment' => true,
    'array_indentation' => true,
    'array_syntax' => ['syntax' => 'short'],
    'cast_spaces' => false,
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'compact_nullable_typehint' => true,
    'concat_space' => ['spacing' => 'one'],
    'dir_constant' => true,
    'ereg_to_preg' => true,
    'escape_implicit_backslashes' => true,
    'explicit_indirect_variable' => true,
    'explicit_string_variable' => true,
    'fopen_flag_order' => true,
    'fopen_flags' => true,
    'fully_qualified_strict_types' => true,
    'function_to_constant' => true,
    'general_phpdoc_annotation_remove' => ['annotations' => ['author']],
    // 'heredoc_indentation' => true,
    'heredoc_to_nowdoc' => true,
    'implode_call' => true,
    'is_null' => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax' => ['syntax' => 'short'],
    'logical_operators' => true,
    'modernize_types_casting' => true,
    'native_function_invocation' => false, //['include' => ['@compiler_optimized'], 'scope' => 'namespaced', 'strict' => true],
    'no_alias_functions' => true,
    'no_binary_string' => true,
    'no_homoglyph_names' => true,
    'no_null_property_initialization' => true,
    'no_php4_constructor' => true,
    'no_superfluous_elseif' => true,
    'no_superfluous_phpdoc_tags' => ['allow_mixed' => true],
    'no_unset_cast' => true,
    // 'no_unset_on_property' => true,
    'no_useless_else' => true,
    'no_useless_return' => true,
    'php_unit_construct' => true,
    'php_unit_dedicate_assert' => true,
    'php_unit_dedicate_assert_internal_type' => true,
    'php_unit_expectation' => true,
    'php_unit_mock' => true,
    'php_unit_mock_short_will_return' => true,
    'php_unit_no_expectation_annotation' => true,
    // 'phpdoc_add_missing_param_annotation' => true,
    'phpdoc_align' => true,
    'phpdoc_summary' => false,
    'phpdoc_to_comment' => false,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_var_without_name' => false,
    'pow_to_exponentiation' => true,
    'psr4' => true,
    'random_api_migration' => true,
    'self_accessor' => true,
    'set_type_to_cast' => true,
    // 'simple_to_complex_string_variable' => true,
    'ternary_to_null_coalescing' => true,
    'visibility_required' => ['property', 'method', 'const'],
    'void_return' => true,
    'yoda_style' => false,
];

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules($rules)
    ->setUsingCache(true)
    ->setCacheFile(__DIR__ . '/.php_cs.cache')
    ->setFinder($finder);
```

php v7.4.7, fixer v2.16.4

**Comment by kubawerlos** [comment] 2020-07-23 19:25
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4879

**Closed by kubawerlos** 2020-07-23 19:25 UTC
Labels: kind/bug
