### ISSUE TITLE
explicit_string_variable: "$var" to "${var}" or "{$var}"

### ISSUE THREAD

**Issue by pablorsk** [FriendsOfPHP/PHP-CS-Fixer#3488] opened 2018-01-31 13:39 UTC
#### The PHP version you are using (`$ php -v`):
=> PHP 7.0.22

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.9.0

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix --config=.php_cs.dist

#### The configuration file you are using, if any:
```php
[
   'explicit_string_variable' => true
]
```

 * before running PHP CS Fixer (no changes):
```php
$query = "select id from $tableName where deleted_at is null";
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
$query = "select id from ${tableName} where deleted_at is null";
```

 * with the changes you expected instead:
```php
$query = "select id from {$tableName} where deleted_at is null";
```
I don't find information on php documentation about this, but I found a lot of examples on this way: `{$var}`

### Also, I found the following problem:

 * before running PHP CS Fixer (no changes):
```php
echo "El usuario $user->first_name no existe."
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
echo "El usuario ${user}->first_name no existe."
```

 * with the changes you expected instead:
```php
echo "El usuario {$user->first_name} no existe."
```
The last example, I think is very complicated, but if we can do somenthing, great! If not, a simple warning would be enough.

**Comment by SpacePossum** [comment] 2018-01-31 13:50
Thanks @pablorsk for reporting,

@Slamdunk , as author of the fixer, may I ask for your thoughts on this?

**Comment by Slamdunk** [comment] 2018-01-31 16:56
Fixed in #3334 released in 2.9.1

**Comment by SpacePossum** [comment] 2018-01-31 16:59
@pablorsk please try again after updating to 2.9.1
thanks @Slamdunk :+1:

**Comment by alexisverardo** [comment] 2018-02-01 12:17
@SpacePossum 
I'm sorry, try with v2.10.0
### before running PHP CS Fixer (no changes):
`$query = "select id from $tableName";`
###with unexpected changes applied when running PHP CS Fixer:
`$query = "select id from ${tableName}";`
###with the changes you expected instead:
`$query = "select id from {$tableName}";`

###in the case of
`$user->first_name` 
this right
`{$user->first_name} `

**Comment by SpacePossum** [comment] 2018-02-01 12:37
thanks for reporting back @alexisverardo 
closing this issue as reported that it has been fixed :)

**Comment by pablorsk** [comment] 2018-02-01 12:47
Sorry @SpacePossum but,

From
```php
$query = "select id from $tableName";
```
to
```php
$query = "select id from ${tableName}";
```
It's correct? Is not correct this?
```php
$query = "select id from {$tableName}";
```

**Comment by keradus** [comment] 2018-02-01 13:09
all 3 forms have same value. all of them are correct.

**Comment by Slamdunk** [comment] 2018-02-01 13:15
@alexisverardo @pablorsk yes it is the expected behaviour, try to run:
```
$ php-cs-fixer describe explicit_string_variable
```
To have the related documentation.

For simple variable, `${var}` is preferred over `{$var}` because the former it is considered the **simple** syntax, while the latter the **complex** one.
See the official documentation: https://secure.php.net/manual/en/language.types.string.php#language.types.string.parsing
Simple rules are always preferred over comples ones.

**Comment by SpacePossum** [comment] 2018-02-06 12:26
Closing as there is nothing left to do here I think? Please comment if you think there is and we can reopen.

**Closed by SpacePossum** 2018-02-06 12:26 UTC

**Comment by xapitancho** [comment] 2022-06-11 00:06
@SpacePossum I think it is time to change because of this: https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated
