### ISSUE TITLE
Line endings in multi-line strings are not corrected

### ISSUE THREAD

**Issue by iluuu1994** [FriendsOfPHP/PHP-CS-Fixer#3452] opened 2018-01-16 15:58 UTC
We've moved from `\r\n` line endings to `\n` in all of our PHP files and have used PHP-CS-Fixer for this migration. Unfortunately, PHP-CS-Fixer does not convert the line endings in multi-line strings. This makes sense as that's a change in behaviour. However in our case we really just want unified line endings.

Do you think it would make sense to add an additional rule for this?

#### The PHP version you are using (`$ php -v`):
> PHP 7.0.15 (cli) (built: Jan 17 2017 13:44:27) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
> PHP CS Fixer 2.10.0 Bowling Bear by Fabien Potencier and Dariusz Ruminski (513a376)

#### The command you use to run PHP CS Fixer:
> php-cs-fixer fix --cache-file=/cache/.php_cs.cache --verbose --diff

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR1' => true,
        '@PSR2' => true,
        '@Symfony' => true,
        '@PHP70Migration' => true,
        'phpdoc_align' => false,
        'phpdoc_summary' => false,
        'array_syntax' => ['syntax' => 'short'],
        'ternary_to_null_coalescing' => true,
        'ordered_imports' => true,
        'phpdoc_order' => true,
        'general_phpdoc_annotation_remove' => ['author'],
        'concat_space' => ['spacing' => 'one'],
        'yoda_style' => false,
    ])
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):

Hint: The `\r\n` and `\n` are just for clarity and not actually part of the source code.

 * before running PHP CS Fixer (no changes):
```php
return 'my\r\n
multi\r\n
line\r\n
string';
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
return 'my\r\n
multi\r\n
line\r\n
string';
```

 * with the changes you expected instead:
```php
return 'my\n
multi\n
line\n
string';
```

**Comment by SpacePossum** [comment] 2018-01-16 16:05
Hi @iluuu1994 and thank for raising this feature request.

The fixer does not fix your example by design. Making the suggested change changes the meaning of the code; so for safety this isn't done.

However, IIRC, there are more people who would like the fixer to act like you suggested. Since we cannot make it an option on the current rule (it would make the rule risky only when configured) it should be a new one I think. The new fixer shouldn't be hard to make I think, however lets get some more ideas on this first.

**Comment by iluuu1994** [comment] 2018-01-16 16:06
@SpacePossum That's what I though. Yes, a new fixer with the `risky` flag would probably be appropriate.

**Comment by iluuu1994** [comment] 2018-01-16 22:59
@SpacePossum I just thought I'd give it a try. Let me know if I need to improve something in the PR.

**Comment by keradus** [comment] 2018-01-22 20:52
Closing due to #3454 PR ;)

**Closed by keradus** 2018-01-22 20:52 UTC
Labels: feature request
