### ISSUE TITLE
Fixers should be configurable from the command line

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#2530] opened 2017-02-10 14:52 UTC
Forcing users to create a configuration file just to configure a fixer can be time-consuming and difficult. It should be quick and easy to try out a fixer and configure it from the command-line. Consider how one might support passing named parameters to fixers, such as in the following way.

```
--rules=array_syntax[syntax=short]
```

**Comment by julienfalque** [comment] 2017-02-10 14:55
Duplicate of #2423

**Comment by keradus** [comment] 2017-02-10 15:06
Closing as duplicate ;)

**Closed by keradus** 2017-02-10 15:06 UTC
