### ISSUE TITLE
Atom beautify not working with PHP.CS.Fixer

### ISSUE THREAD

**Issue by YutaNakai** [FriendsOfPHP/PHP-CS-Fixer#3967] opened 2018-08-09 16:42 UTC
I'm from 
https://github.com/Glavin001/atom-beautify/issues/2195

I've been trying to beautify but no result with no erro messages.

The owner of Atom-beautify said that there must be something worng in PHP.CS.Fixer.

PHP: 7.2.6
PHP-CS-Fixer: 4.1.1
PHP-CS-Fixer Conf: I don't know how to do it.
ATOM: 1.29.0
Beautify: 0.32.5
Beautify Conf: I don't know how to do it.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

$num = 10;
$dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';
$user = 'tennisuser';
   $page = 0;


    if (isset($_GET['page']) && $_GET['page'] > 0) {
        $page = intval($_GET['page'])-1;
    }

    try {
        $db = new PDO($dsn, $user, $password);
        $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);

        $stmt = $db ->prepare("
    SELECT * FROM bbs ORDER BY date DESC LIMIT :page, :num
    ");

        $page = $page * $num;
        $stmt->bindParam(':page', $page, PDO::PARAM_INT);
        $stmt->bindParam(':num', $num, PDO::PARAM_INT);

        $stmt ->execute();
    } catch (PDOException $e) {
        die('エラー：'.$e->getMessage());
    ?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>掲示板</title>
     </head>
  <body>
       <p><a href="index.php">トップページに戻る</a></p>
    <form class="" action="write.html" method="post">
          <p>名前:<input type="text" name="name"></p>
      <p>タイトル:<input type="text" name="title"></p>
                                    <textarea name="body"></textarea>
      <p>削除パスワード(数字4文字):<input type="text" name="pass"></p>
      <p><input type="submit" value="書き込む"></p>

    </form>
  </body>
</html>

**Comment by YutaNakai** [comment] 2018-08-09 16:44
It's working but beautify.


![33](https://user-images.githubusercontent.com/42037264/43912986-c4604a1c-9c3e-11e8-87a7-2347e1ed3af6.png)

![34](https://user-images.githubusercontent.com/42037264/43912999-cae559e0-9c3e-11e8-8e07-16e28a4f6584.png)

Here's my path in Atom.

**Comment by keradus** [comment] 2018-08-09 20:45
Closing as duplicate of #3966

1. seriously, one thread is enough
2. showing settings of atom is not helpful, as we are not atom support
3. `PHP-CS-Fixer: 4.1.1` -> newest line of PHP CS Fixer is 2; if you are using v4, I have no clue what you are using
4. as said in #3966 , your input file must be a valid PHP file (we also provided way to check it)... it is not - you do have opening `{` for `catch` block, but there is no `}`. for that, it's invalid PHP file, thus PHP CS Fixer refuses to touch it

**Comment by YutaNakai** [comment] 2018-08-09 21:07
Why are you closing?

The reason why l'm questioning is
l want to fix it.

l'm sorry l may not clearly understand how to use this site and my English
is not so good
because I'm not a native.

l just want to solve the problem that I have.

**Comment by YutaNakai** [comment] 2018-08-09 21:14
4.
as said in #3966 <https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3966> ,
your input file must be a valid PHP file (we also provided way to check
it)... it is not - you do have opening { for catch block, but there is no }.
for that, it's invalid PHP file, thus PHP CS Fixer refuses to touch it

For PHP CS Fixer to tocuh it what sould I do?

The problem is in PHP CS Fixer Isn't it?

**Comment by keradus** [comment] 2018-08-09 21:33
> Why are you closing?

I'm closed raised issue because it's a duplicate duplicate.
Also, you got answer for you question. And still, this is not support channel.
Finally, even if issue report is closed, as it's not an issue in the end, you can still - **you can still write here and get further answers**, as you can see.


> The problem is in PHP CS Fixer Isn't it?

No, it is not. issue is that file you are asking PHP CS Fixer to fix is not proper PHP file.
Try to run that file as part of your software - it will crash, due to syntax error, because... :
> `}` is missing for `catch` block.

**Comment by YutaNakai** [comment] 2018-08-10 02:17
Okay.

What do you mean by "not proper php file"?

lt should be "〜.php" right?

**Comment by keradus** [comment] 2018-08-10 05:45
content of the file you have provided (one with `$dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';` inside) is not proper php file - it has invalid syntax, missing `}` for `catch` block

**Comment by keradus** [comment] 2018-08-10 05:46
```diff
 <?php
 
 $num = 10;
 $dsn = 'mysql:host=localhost;dbname=bbs;charset=utf8';
 $user = 'tennisuser';
    $page = 0;
 
 
     if (isset($_GET['page']) && $_GET['page'] > 0) {
         $page = intval($_GET['page'])-1;
     }
 
     try {
         $db = new PDO($dsn, $user, $password);
         $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
 
         $stmt = $db ->prepare("
     SELECT * FROM bbs ORDER BY date DESC LIMIT :page, :num
     ");
 
         $page = $page * $num;
         $stmt->bindParam(':page', $page, PDO::PARAM_INT);
         $stmt->bindParam(':num', $num, PDO::PARAM_INT);
 
         $stmt ->execute();
     } catch (PDOException $e) {
         die('エラー：'.$e->getMessage());
+    }
     ?>
 <!DOCTYPE html>
 <html lang="en" dir="ltr">
   <head>
     <meta http-equiv="content-type" content="text/html; charset=utf-8">
     <title>掲示板</title>
      </head>
   <body>
        <p><a href="index.php">トップページに戻る</a></p>
     <form class="" action="write.html" method="post">
           <p>名前:<input type="text" name="name"></p>
       <p>タイトル:<input type="text" name="title"></p>
                                     <textarea name="body"></textarea>
       <p>削除パスワード(数字4文字):<input type="text" name="pass"></p>
       <p><input type="submit" value="書き込む"></p>
 
     </form>
   </body>
 </html>
```

**Comment by YutaNakai** [comment] 2018-08-10 05:59
Thank you for responding.

I copied and pasted this one and ran 'beautify'.
But not beautifying and I got this below.

![37](https://user-images.githubusercontent.com/42037264/43941136-f14eee2e-9cad-11e8-83ab-4ea0ff230e7c.png)

**Comment by keradus** [comment] 2018-08-10 06:07
once more, this is not Atom support, I'm not using Atom, I won't help with it.

What we saw already was output from PHP CS Fixer about incorrect input file.
If you expect more support here, provide steps how to reproduce your issue without using Atom, but pure CLI.

**Comment by YutaNakai** [comment] 2018-08-10 06:16
Yes, I know. 
But you know if my PHP.CS.Fixer setting is correct.

Because I don't know whrer to go unless I get where the problem is.

**Comment by YutaNakai** [comment] 2018-08-10 09:57
My problem's Atom?

**Comment by keradus** [comment] 2018-08-10 22:45
your original problem was that file you wanted to fix was invalid php file - there were a syntax issue

if you still have some problems, show how to reproduce it without using Atom, so we can verify it.

**Comment by YutaNakai** [comment] 2018-08-11 01:35
I can use cmd.

l don't know what I should type

**Comment by keradus** [comment] 2018-08-11 06:41
`php-cs-fixer fix path-to-file.php -vvv`

**Comment by YutaNakai** [comment] 2018-08-11 07:37
I did.

cmd said " php-cs-fixer is not identified
from inside and outside and is not allowed to
be manipulated."

It is translation.

**Comment by keradus** [comment] 2018-08-11 09:50
see readme/website how to install it

**Comment by YutaNakai** [comment] 2018-08-11 10:08
install what?

**Comment by keradus** [comment] 2018-08-11 10:40
i see this discussion leads nowhere :(

**Closed by keradus** 2018-08-11 10:40 UTC

**Comment by YutaNakai** [comment] 2018-08-11 10:42
l geuss but if you can help,
l can not use it

**Comment by robertplanetweb** [comment] 2021-11-07 20:11
- make an empty folder somewhere. example: C:\Programs\php-cs-fixer
- run `composer require friendsofphp/php-cs-fixer`
- open atom and go to settings -> packages -> atom beautify -> settings -> executables -> php cs fixer
- input the path there: `C:\Programs\php-cs-fixer\vendor\bin\php-cs-fixer.bat`
- optional: add `C:\Programs\php-cs-fixer\vendor\bin` to windows env path so you can use it to cli
