### ISSUE TITLE
[Feature Request] Force all associative arrays to be multi-line

### ISSUE THREAD

**Issue by skyzyx** [FriendsOfPHP/PHP-CS-Fixer#2978] opened 2017-08-14 19:16 UTC
For example, this:

```php
$var = ['abc' => 123, 'def' => 456];
```

…becomes this:

```php
$var = [
    'abc' => 123,
    'def' => 456
];
```

Other rules could apply to this as well, such as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2977 and trailing commas on multi-line arrays.

**Comment by keradus** [comment] 2017-08-14 19:26
Hi
Thanks for report.
It's a duplicate of #1217, thus closing.

This project is community driven software. As all of us are doing voluntarily, it's not possible to handle all requests by maintainers team. If you want this feature to happen, please send a PR.

**Closed by keradus** 2017-08-14 19:26 UTC
