### ISSUE TITLE
Config::addRules and Config::addRule

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#1428] opened 2015-09-28 09:22 UTC
Could be useful to have fixers addition methods on Config class.

In some case, we could import config from a bridge like this: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge

And add some fixers like header_comment.

Actually, with 2.x, we have to do this:

```php
use SLLH\StyleCIBridge\ConfigBridge;

$header = 'test';

$config = ConfigBridge::create();

return $config
    ->setUsingCache(true)
    ->setRiskyAllowed(true)
    ->setRules(array_merge($config->getRules(), ['header_comment' => ['header' => $header]]))
;
```

Would be great if we could do this:

```php
return ConfigBridge::create()
    ->setUsingCache(true)
    ->setRiskyAllowed(true)
    ->addRules(['header_comment' => ['header' => $header]])
;
```

Or, even better, this:

```php
return ConfigBridge::create()
    ->setUsingCache(true)
    ->setRiskyAllowed(true)
    ->addRule('header_comment', ['header' => $header])
;
```

I can provide a PR if interested.

**Comment by Soullivaneuh** [comment] 2015-09-28 09:55
In the same time, we could add both `removeRule` and `removeRules` also.

**Comment by keradus** [comment] 2015-09-28 12:42
:-1: for removal methods
+/- 0 for addRule

I would strongly recomment to use given setter for rules. If you would like to add one rule with dedicated method - what ruleset will be a base for such addition ?

**Comment by Soullivaneuh** [comment] 2015-09-28 13:57
> what ruleset will be a base for such addition ?

See my link and my pasted code.

The bridge will automaticaly calculate and sets rules based on StyleCI config file.

Unfortunately, some rules like `header_comment` are not supported on this configuration file and have to be added manually.

With only `setRules` method, we have to make an ugly `array_merge` and set again. :-)

**Comment by Soullivaneuh** [comment] 2015-09-28 13:59
> :-1: for removal methods

May I ask why? :-)

**Comment by keradus** [comment] 2015-09-28 14:07
> > what ruleset will be a base for such addition ?
> See my link and my pasted code.

I saw that, and that was my point. base for addition would be hidden. Set rules at once is great, but if we won't use it and we based on default one - and then add sth or remove sth - we won't have clear picture. Once we have situation when one can use CLI arg to modify tu fixers to be used - and no-one know what was the base. That is why I don't like adding ad-hoc some rules and strongly against removing it. This move was discussed during introducing rules and sets.

**Comment by keradus** [comment] 2015-09-28 14:13
End-user should use simple ruleset interface. Tools like bridges may work around it too.

**Comment by Soullivaneuh** [comment] 2015-09-28 14:14
> Tools like bridges may work around it too.

Sure. In any case, this is specified on my doc: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge#php-cs-fixer-2x

I just try to provide a nicier way. :+1:

**Comment by keradus** [comment] 2015-09-28 14:17
End user should know which rules he want to use, and not guessing it

**Comment by keradus** [comment] 2015-09-28 14:18
In your bridge case - if user has some ruleset for PHP CS Fixer, why would he run different set for StyleCI...

**Comment by keradus** [comment] 2015-09-28 14:25
> I just try to provide a nicier way.

Instead of hacking interface of your destination tool you should focus on filling the shortcoming of your source tool.
From what you said (https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge#php-cs-fixer-2x) the problem is that StyleCI doesn't handle header configuration well yet.

**Comment by Soullivaneuh** [comment] 2015-09-28 14:29
Yeah, this is my use case. But I think this could be useful to add fixers manually for others case like dynamic cases.

**Comment by keradus** [comment] 2015-09-28 14:33
And that the problems.
- shortcoming in one library shouldnt change interface of second. Your workaround will make it's job until StyleCI learn a bit more about configuration of fixers;
- on 2.x end-user won't use ruleset to register class. He will simply register custom fixer at start and then provide full ruleset (that uses with his private, custom fixer)

**Comment by GrahamCampbell** [comment] 2015-09-28 19:47
StyleCI has no intention of supporting php-cs-fixer's rule sets.

**Comment by theofidry** [comment] 2015-10-09 19:15
the less modifiers the better, so :-1: for this. The work around you're using looks great to me @Soullivaneuh and is enough for a bridge ;)

**Comment by keradus** [comment] 2015-10-10 11:21
Closing due to discussion.

**Closed by keradus** 2015-10-10 11:21 UTC
