### ISSUE TITLE
Incorrect indentation when mixing PHP with HTML in templates

### ISSUE THREAD

**Issue by JoyceBabu** [FriendsOfPHP/PHP-CS-Fixer#6562] opened 2022-08-19 09:25 UTC
## Bug report

PHP-CS-Fixer is not correctly detecting the indentation level, when mixing PHP code with HTML in template files.

```
./vendor/bin/php-cs-fixer -vvv fix public_html/php-cs.php

PHP CS Fixer 3.9.5 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.9
Loaded config default from "<working_dir>/.php-cs-fixer.dist.php".
Using cache file ".php-cs-fixer.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                        1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) public_html/php-cs.php (braces)
```
### Code snippet that reproduces the problem

```php
<?php
$var = 1;
?>
<!DOCTYPE html>
<html lang="en">
<body>
<div id="wrapper" >
    <ul>
        <!-- Indentation is removed for the following foreach ->
        <?php $tmpNo = 1;
        foreach ($arSign as $sign): ?>
            <li><?=$tmpNo++?>. <?=$sign?></li>
        <?php endforeach; ?>

        <!-- Indentation is not removed for the following -->
        <?php foreach ($arSign as $sign): ?>
            <li><?=$tmpNo++?>. <?=$sign?></li>
        <?php endforeach; ?>

    </ul>
</div>
</body>
</html>
```

#### Output Diff

```diff
@@ -8,7 +8,7 @@
     <ul>
         <!-- Indentation is removed for the following foreach ->
         <?php $tmpNo = 1;
-        foreach ($arSign as $sign): ?>
+foreach ($arSign as $sign): ?>
             <li><?=$tmpNo++?>. <?=$sign?></li>
         <?php endforeach; ?>

````

#### Expected Output

No change in `foreach` indentation.

**Comment by julienfalque** [comment] 2022-08-19 16:29
Duplicate of #6521.

**Closed by julienfalque** 2022-08-19 16:29 UTC
Labels: kind/bug
