### ISSUE TITLE
Bug in phpdoc_trim fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3316] opened 2017-12-12 12:18 UTC
**PHP 7.1.12; PHP CS Fixer 2.9.0**

The `fixStart` method in the `PhpdocTrimFixer` may return `null`, which ends up crashing everything. Will submit a reproducible test case later today.

**Comment by Slamdunk** [comment] 2017-12-12 13:37
Duplicate of #3309 (see also #3304 #3314)

**Comment by GrahamCampbell** [comment] 2017-12-12 14:11
Is it? I think this was working before, in 2.8, and is now broken?

**Comment by Slamdunk** [comment] 2017-12-12 14:12
Yes, because of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3272

**Comment by SpacePossum** [comment] 2017-12-13 12:26
3272 touched `fixEnd` not `fixStart` as reported, so maybe this might need more looking into?

**Comment by julienfalque** [comment] 2018-02-06 18:25
Closing as duplicate, we already have several open issues and PR to track this, thanks.

**Closed by julienfalque** 2018-02-06 18:25 UTC
