### ISSUE TITLE
Multi-line array definitions are not re-indented

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#1438] opened 2015-10-09 14:33 UTC
Using version 1.10, this code

``` php
        $this->assertEquals(
            [
            'lowUpperBound'        => '50',
            'highLowerBound'       => '90',
            'coverage-html'        => '/tmp/report',
            'coverage-clover'      => '/tmp/clover.xml',
            'json'                 => '/tmp/logfile.json',
            'plain'                => '/tmp/logfile.txt',
            'tap'                  => '/tmp/logfile.tap',
            'logIncompleteSkipped' => false,
            'junit'                => '/tmp/logfile.xml',
            'testdox-html'         => '/tmp/testdox.html',
            'testdox-text'         => '/tmp/testdox.txt',
            ],
            $this->configuration->getLoggingConfiguration()
        );
```

in PHPUnit's own test suite is not reformatted as

``` php
        $this->assertEquals(
            [
                'lowUpperBound'        => '50',
                'highLowerBound'       => '90',
                'coverage-html'        => '/tmp/report',
                'coverage-clover'      => '/tmp/clover.xml',
                'json'                 => '/tmp/logfile.json',
                'plain'                => '/tmp/logfile.txt',
                'tap'                  => '/tmp/logfile.tap',
                'logIncompleteSkipped' => false,
                'junit'                => '/tmp/logfile.xml',
                'testdox-html'         => '/tmp/testdox.html',
                'testdox-text'         => '/tmp/testdox.txt',
            ],
            $this->configuration->getLoggingConfiguration()
        );
```

as I would expect.

Am I missing a rule (https://github.com/sebastianbergmann/phpunit/blob/5.0/.php_cs is the configuration I use) or is there an issue with a rule that I use?

**Comment by SpacePossum** [comment] 2015-10-09 14:39
This should be done by the `align_double_arrow` which is in the `.php_cs` file of the PHPUnit repo, so it is not a configuration issue.
The fixer was update about 12 days ago, did you have the issue with the fixer before that as well?

**Comment by sebastianbergmann** [comment] 2015-10-09 14:51
I only noticed this today and have not updated my `php-cs-fixer` since July (I am using the latest PHAR release, v1.10; sorry for not mentioning that in the original report).

**Comment by sebastianbergmann** [comment] 2015-10-09 14:59
Having the same problem with latest 1.11-DEV.

**Comment by SpacePossum** [comment] 2015-10-09 15:16
Thanks for the details :+1: 
I'll have look soon.

**Comment by sebastianbergmann** [comment] 2015-10-09 19:22
Yes, `indentation` is missing but that is about spaces vs. tabs anyways, right?

**Comment by GrahamCampbell** [comment] 2015-10-09 19:23
`align_double_arrow` should just add spaces before the `=>`s in an array to align them. `indentation` is responsible for ensuring blocks have the correct indentation level.

**Comment by keradus** [comment] 2015-10-10 11:24
There is no fixer yet to align array's content. `indentation` won't do that.
It's not a bug, but simply lack of feature.

**Comment by sebastianbergmann** [comment] 2016-03-03 16:13
Any update on this? Would be nice if `php-cs-fixer` could fix this. Thanks!

**Comment by keradus** [comment] 2016-03-03 16:20
I'm :+1: for that feature, it would be really nice.
Sadly, I don't have time to create it soon, maybe you want to help with it?

**Comment by NewFuture** [comment] 2017-01-01 14:38
A nice feature

**Comment by tonivdv** [comment] 2017-03-15 07:16
No one working on this feature?

**Comment by SpacePossum** [comment] 2017-03-15 07:22
@tonivdv AFAIK there is no work on this ATM, maybe you can help out?

**Comment by tonivdv** [comment] 2017-03-15 07:28
@SpacePossum I'll see what I can do.

**Comment by derekmd** [comment] 2017-09-15 20:42
Has there been follow-up on this? The deprecated PSR-2 `indentation` rule used to auto-fix array spaces but replacement rule `indentation_type` for `@PSR2` or `@Symfony` mode doesn't affect array spaces.

Specifically I want to auto-fix Laravel PHP array-based files translation files.

Package "barryvdh/laravel-translation-manager" outputs 2 spaces so I've used `php-cs-fixer` to enforce consistent 4 spaces indentation. See pull request proposed for that project: https://github.com/barryvdh/laravel-translation-manager/pull/173

```php
<?php

return array(
  'first-name' => 'First Name',
  'last-name' => 'Last Name',
  'language' => array(
    'en' => 'English',
    'es' => 'Spanish',
  ),
);
```

to

```php
<?php

return [
    'first-name' => 'First Name',
    'last-name' => 'Last Name',
    'language' => [
        'en' => 'English',
        'es' => 'Spanish',
    ],
];
```

**Comment by keradus** [comment] 2017-09-16 08:26
`indentation` fixer was enforcing one to use 4 spaces over tabs.
it was indeed replaced by `indentation_type`, which is configurable and is enforcing to use 4 spaces of tab.

yet, it is not supposed to reindent arrays. we never have such a fixer. this file is a feature request, yet it didn't met much support from community.
If you also want to have this feature, please send PR proposal :+1:

**Comment by keradus** [comment] 2018-03-20 11:51
Closing due to amazing work of #3135 by @julienfalque

that was a long life of this feature request indeed.... glad to finally close it!

**Closed by keradus** 2018-03-20 11:51 UTC
Labels: feature request
