### ISSUE TITLE
No spaces in union types rules

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#5733] opened 2021-05-23 20:40 UTC
While preparing Symfony 6, which can now use union types thanks to PHP8, [we figured out](https://github.com/symfony/symfony/pull/41371#discussion_r637573703) that php-cs-fixer enforces spaces in union types.

but we'd really prefer spaces to be removed. Aka this:
`string | array | null $path = null`

should become this:
`string|array|null $path = null`

**Comment by julienfalque** [comment] 2021-05-24 17:53
I'm not sure there is any rule dedicated to enforcing a spacing style in union types. Isn't it applied by `binary_operator_spaces` instead?

**Comment by derrabus** [comment] 2021-05-24 18:09
Yes, apparently the `|` is detected as a bitwise OR operator. imho, the `binary_operator_spaces` fixer should not touch union type declarations at all.

**Comment by kubawerlos** [comment] 2021-05-24 18:21
> the `|` is detected as a bitwise OR operator

exactly ☝🏼, see the integration test in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5734

> imho, the `binary_operator_spaces` fixer should not touch union type declarations at all.

I'm not sure about, after all it is a binary operator (as it is operator and is binary), but we might want to exclude it, let's discuss it in: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5734

**Comment by derrabus** [comment] 2021-05-24 19:18
> I'm not sure about, after all it is a binary operator

Debatable. Even is we the view it as an operator and thus acknowledge that `binary_operator_spaces` is responsible for it, we need to treat the bitwise OR and the union pipe as different operators. Because they are, they just happen to share the same symbol.

So either way, whether we extend `binary_operator_spaces` or create a new fixer: It should be possible to configure the two operators individually.

**Comment by kubawerlos** [comment] 2021-05-24 19:32
`binary_operator_spaces` is configuring operators via their content: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/src/Fixer/Operator/BinaryOperatorSpacesFixer.php#L72 - which I guess is a good ways as it is very friendly for the users - they don't have to care about the tokens.

That said, the easy/best/lazy solution is to leave it that way and make the new fixer to override/clean after it.

> It should be possible to configure the two operators individually

How would it work then? `|_or` and `|_union_type`? There have to be a BC (or maybe not) change to `binary_operator_spaces` - is it worth the effort?

**Comment by julienfalque** [comment] 2021-05-24 20:00
IMO, `|` is not an operator when used for union types and `binary_operator_spaces` handling it is a bug.

**Comment by kubawerlos** [comment] 2021-05-25 05:56
@julienfalque it's fine for me (less integration tests - less problems) - but what about these - https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3210 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3215 - PRs then? Seems intentional.

**Comment by julienfalque** [comment] 2021-05-25 09:54
I have different insights today and I would consider these old PRs went into the wrong direction.

**Comment by sirian** [comment] 2021-06-01 14:21
+1 for this. temporarily workaround - disable `|` for `binary_operator_spaces`:

```php
return (new PhpCsFixer\Config())
    ->setRules([
        // ...
        'binary_operator_spaces' => [
            'operators' => [
                '|' => null,
            ],
        ],
     ]);
```

**Comment by sebastianbergmann** [comment] 2021-06-01 14:23
Looks like a duplicate of #5495 to me.

**Comment by julienfalque** [comment] 2021-06-01 15:10
It is, thanks.

**Closed by julienfalque** 2021-06-01 15:10 UTC
Labels: kind/bug
