### ISSUE TITLE
Order getter / setter / hasser

### ISSUE THREAD

**Issue by eigan** [FriendsOfPHP/PHP-CS-Fixer#3330] opened 2017-12-19 08:00 UTC
**Before running PHP CS Fixer:**
```php
class Foo {
    public function setTitle($title) { ... }
    public function getTitle() { ... }
    public function hasTitle(): bool { ... }
}

```

**After running PHP CS Fixer:**
```php
class Foo {
    public function getTitle() { ... }
    public function setTitle($title) { ... }
    public function hasTitle(): bool { ... }
}
```

Suggested rule names: `ordered_mutator_accessor`, `ordered_get_set_has`, or `ordered_class_methods`.
Configuration: `['get', 'set', 'has']`

##### Other notes
Where property is `NN`, the ordering should be: `NN, getNN, setNN, hasNN, haveNN, xxNN`

**Comment by Slamdunk** [comment] 2017-12-19 09:53
I would also suggest `'is'` for the following case:
```php
class Foo {
    public function setValid($valid)    { $this->valid = $valid; }
    public function getValid()          { return $this->valid; }
    public function isValid()           { return true === $this->valid; }
}
```

**Comment by keradus** [comment] 2017-12-19 10:36
closing as duplicate of #2746, please follow that thread instead.

**Closed by keradus** 2017-12-19 10:36 UTC
