### ISSUE TITLE
binary_operator_space rule does not work inside function callbacks

### ISSUE THREAD

**Issue by adwinying** [FriendsOfPHP/PHP-CS-Fixer#4247] opened 2019-01-08 12:27 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.1

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer`

#### The configuration file you are using, if any:
```php
<?php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->name('*.php')
    ->notName('*.blade.php')
    ->notName('UnauthorizedRouteTest.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        'binary_operator_spaces' => [
          'operators' => [
            '=' => 'align_single_space_minimal',
            '=>' => 'align_single_space_minimal',
            '??' => 'align_single_space_minimal',
          ],
        ],
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'linebreak_after_opening_tag' => true,
        'is_null' => true,
        'ordered_imports' => true,
        'phpdoc_order' => true,
        'phpdoc_summary' => false,
        'phpdoc_separation' => false,
        'phpdoc_align' => [
          'tags' => ['param', 'property', 'throws', 'type', 'var'],
        ],
        'yoda_style' => [
          'equal' => false,
          'identical' => false,
        ],
    ])
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
$foo(function ($bar) {
    $foobar = 123;
    $baz    = 456;
});
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
$foo(function ($bar) {
    $foobar = 123;
    $baz = 456;
});

```

 * with the changes you expected instead:
```php
$foo(function ($bar) {
    $foobar = 123;
    $baz    = 456;
});
```

**Comment by SpacePossum** [comment] 2019-01-10 18:35
hi @adwinying ,

Thank for the detailed report!
Currently we know of a few issues with this rule. Could you check if your issue might be a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3986 or if it shares the same root cause as yours? (I might oversee a detail here :) )  Thanks!

**Comment by SpacePossum** [comment] 2019-01-11 08:35
thanks, please track that issue for progress on this :)

**Closed by SpacePossum** 2019-01-11 08:35 UTC
Labels: bug, duplicate
