### ISSUE TITLE
[Bug] Linting mixed HTML/PHP in Windows format output a mixed line endings file

### ISSUE THREAD

**Issue by Yivan** [FriendsOfPHP/PHP-CS-Fixer#4812] opened 2020-02-13 20:49 UTC
Hello,

Using @Symfony rules for linting mixed HTML/PHP in Windows format output a mixed line endings file.
PHP lines are LF and HMTL line stay CRLF.

I imagine it is because only PHP line are analysed, but it result in a really bad file format...

I think the fixer should preprocess the file by something like dos2unix.

Best regards.

**Comment by SpacePossum** [comment] 2020-02-14 07:03
Hi @Yivan 

Thank you for your suggestion. This tool fixes (valid) PHP code only by design, however we could fix the html line endings if we had a rule for it.

We used to have such rule;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/5de5794c0409982c5ed36aaa1546d2fa6d5fdf24/src/Fixer/Whitespace/UnixLineEndingsFixer.php

I would like to see it back. Only with a different name and description, marked as `risky` and using the configured line ending (so not always the Unix one).

**Comment by Yivan** [comment] 2020-02-14 13:47
@SpacePossum Thanks for your return on this.

Yes i really think it is needed, because actually, it is even worse without this rules as it ends in mixed line endings silently and no so many IDE can spot it, so it could lead to problem hard to find later on those mixed lines files (it could break other parser because they detect end line jsut form the first or last line, and so will have problem inside the file if mixed ending lines).

It should not be set risky but should be default. From the instant line ending is changing in one line on a file, it must be done on all the file to assure coherent line ending for this file.
This is the actual behaviour which is risky i think (just changing PHP ending line and left other line of the files as it is...).

I hope it make sense.
For now, solution is to run dos2unix as pre fix before running the fixer.

I detected some other problem on this file format subjet:
- trim trailing space is not done on php comment bloc (full php file)
- empty last line is not added on mixed files (php/hmtl)
I will open separated issue for them, but they all have purpose to achieve a clean file format: unix lf, trim trailing space, have on empty line on the file (linux way). UTF8-BOM removing works fine (on hpp files and mixed html/php), so this one is ok!

**Comment by Yivan** [comment] 2020-02-14 13:54
Here is the linked trim trailing space for reference: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4814

**Comment by SpacePossum** [comment] 2020-02-14 13:57
I think updating `string_line_ending` to fix inside `T_INLINE_HTML` as well will fix this issue more easy. WDYT @julienfalque  ?

**Comment by Yivan** [comment] 2020-02-14 14:12
Here is the empty last line issue for reference: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4815
Like i said i mentionned those two last two issue because they have in common with this one the subject of general file format.

**Comment by SpacePossum** [comment] 2020-02-26 13:54
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4840

**Closed by SpacePossum** 2020-02-26 13:54 UTC
Labels: kind/feature request

**Comment by Yivan** [comment] 2020-02-26 14:06
Great !! Thanks a lot.

**Comment by SpacePossum** [comment] 2020-02-26 14:09
you're welcome :)
