### ISSUE TITLE
Fixer request: Unify multiline vs single-line PHPDoc for properties

### ISSUE THREAD

**Issue by hkdobrev** [FriendsOfPHP/PHP-CS-Fixer#3598] opened 2018-03-14 13:58 UTC
There are two competing styles for PHPDoc `@var` annotations on class properties:

1.
```php
/**
 * @var string
 */
private $name;
```
2.
```php
/** @var string */
private $name;
```

It would be great to have a fixer configuring which one should be used and converting one to the other.

**Comment by keradus** [comment] 2018-03-20 12:01
I'm closing this one as it's a duplicate of #2646 , and sadly #3061 and #3300
Would you mind to propose a PR to bring this feature alive, @hkdobrev ?

**Closed by keradus** 2018-03-20 12:01 UTC
Labels: feature request

**Comment by hkdobrev** [comment] 2018-03-20 13:20
I'll add it to my TODO list and would see if I can create a useful PR. I'm very keen to fixing that in our app and enforcing it so I'll give it a go.
