### ISSUE TITLE
ENUM type casting issue

### ISSUE THREAD

**Issue by LocalHeroPro** [FriendsOfPHP/PHP-CS-Fixer#6474] opened 2022-07-11 18:29 UTC
## Bug report
Why Only on that one we have to insert space after ENUM name? In about 20 other ENUMs that package don't see issue in same syntax.

### Code snippet that reproduces the problem
```shell
$ php8.1 vendor/bin/php-cs-fixer fix app --verbose --diff --dry-run
PHP Warning:  JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0
PHP CS Fixer 3.9.2 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.8
Loaded config default.
............................................................F................................................................................................................................................................................................. 254 / 394 ( 64%)
............................................................................................................................................                                                                                                                   394 / 394 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) app/Enums/TaskType.php (ternary_operator_spaces)
      ---------- begin diff ----------
--- /var/www/example.com/html/app/Enums/TaskType.php
+++ /var/www/example.com/html/app/Enums/TaskType.php
@@ -9,7 +9,7 @@
 use Illuminate\Support\Facades\Gate;
 use Illuminate\Support\Str;
 
-enum TaskType: int
+enum TaskType : int
 {
     use Base;
 

      ----------- end diff -----------


Checked all files in 6.042 seconds, 22.000 MB memory used
```

**Comment by jrmajor** [comment] 2022-07-11 18:38
I'm unable to reproduce the issue with snipped provided. Would you mind sharing the entire file?

**Comment by LocalHeroPro** [comment] 2022-07-12 19:09
```php
<?php

namespace App\Enums;

use App\Console\Commands\MailingCampaignSend;
use App\Console\Commands\OrdersUpdate;
use App\Models\Permission;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

enum TaskType: int
{
    use Base;

    /**
     * Keep same IDs like in NotificationType
     */
    case IMPORT_ORDERS = 1;
    case MAILING_CAMPAIGN = 2;
    case MAILING_AFTER_ACTION = 3;
    case SENDING_PACKAGES = 4;
    case IMPORT_SUBSCRIBERS = 5;
    case EXPORT_ORDERS = 6;
    case UPDATE_ORDER_STATUSES = 7;
    case ORDER_STATUS_CHANGE_AFTER_PACKAGE_IS_CREATED = 8; // can have only one

    public const DEFAULT = self::IMPORT_ORDERS;

    public static function getForSelect2(array $validated): array
    {
        $options = self::options(true);
        $search = Arr::get($validated, 'search');
        $showAll = Arr::get($validated, 'show_all');
        $toReturn = [];

        if (!$showAll) {
            unset(
                $options[self::EXPORT_ORDERS->value],
                $options[self::IMPORT_SUBSCRIBERS->value],
                $options[self::SENDING_PACKAGES->value],
                $options[self::UPDATE_ORDER_STATUSES->value],
            );
        }

        if (filled($search)) {
            $search = Str::lower($search);
        }

        $data = is_null($search)
            ? $options
            : array_filter($options, function ($label, $value) use ($search) {
                return Str::contains(Str::lower($label), $search);
            }, ARRAY_FILTER_USE_BOTH);

        if (!Gate::allows(Permission::LABELS[Permission::ORDERS_UPDATE_FROM_WOOCOMMERCE])) {
            Arr::forget($data, self::IMPORT_ORDERS->value);
        }

        foreach ($data as $key => $item) {
            $toReturn[] = ['id' => $key, 'text' => $item];
        }

        return $toReturn;
    }
}

```

**Comment by jrmajor** [comment] 2022-07-17 14:30
This is a duplicate of #6336.

**Closed** 2022-07-18 10:27 UTC
Labels: kind/bug
