### ISSUE TITLE
The deprecated phpdoc tag should not forbid dot

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2445] opened 2017-01-03 13:38 UTC
It is very common to include sentences in the description of ``@deprecated`` to explain what should be used as a replacement instead. And so ending with a dot makes sense.

**Comment by keradus** [comment] 2017-01-03 14:21
like
`@deprecated because of sth.`
or
`@deprecated because of sth. Use sth else.`

?

**Comment by SpacePossum** [comment] 2017-01-03 14:25
like
```php
/**
 * This is @deprecated
 */
```

should not become 

```php
/**
 * This is @deprecated.
 */
```

same issue with `@link` and `@see`

```php
/**
 * description @see www.sth.com
 */
```
should not become
```php
/**
 * description @see www.sth.com.
 */
```

**Comment by keradus** [comment] 2017-01-03 14:29
in all your cases @SpacePossum there is no doc-level annotation, only phpdoc summary. summaries should have trailing full stop

**Comment by SpacePossum** [comment] 2017-01-03 14:35
```php
/**
 * This is class A @see www.sth.com
 *
 * Class A something something something something, 
 * something something something something,
 * something something something something.
 *
 * @final
 * @internal
 */
class A 
{
}
```

is invalid? (and if so, the fixer should not fix invalid things IMO, like we don't fix invalid PHP code)

**Comment by stof** [comment] 2017-01-03 14:55
@keradus yeah, exactly.

**Comment by stof** [comment] 2017-01-03 14:57
@keradus in Symfony, ``@deprecated`` tags generally look like this:

```
@deprecated since 3.3, will be removed in 4.0. Use something else instead.
```

**Comment by keradus** [comment] 2017-01-03 18:50
@SpacePossum , in your case it's valid, but `@see` is not treated here as phpdoc-level annotation, for that Summary still should have dot.

@stof , if description contains multiple sentences the dot shall not be removed (as removing only last dot will make wrong pronunciation). IIRC it was already changes, which version you are using ?

**Comment by SpacePossum** [comment] 2017-01-22 20:35
>Summary still should have dot.

disagree, as it impossible for API doc generators and/or IDE to know if the dot at the end belongs to the URL before it or not. Anyway, this all seems out of scope of the issue so lets leave it like that ;)

@stof can you provide a code sample that is fixed wrong together with version of the tool you are using (+config), I could not reproduce the problem (i.e. dot being removed)

**Comment by SpacePossum** [comment] 2017-02-06 18:23
ping @stof do you've a sample that goes wrong?

**Comment by SpacePossum** [comment] 2017-04-03 07:11
ping @stof :)

**Comment by SpacePossum** [comment] 2017-04-06 17:35
Closing after almost 2,5 months of no response by reporter. 
However, @stof, feel free to comment here with an example that is fixed wrongly and we get start bug-hunting and fixing, but without we cannot fix this issue.

**Closed by SpacePossum** 2017-04-06 17:35 UTC
Labels: to verify
