### ISSUE TITLE
Complex PHPDoc types are broken

### ISSUE THREAD

**Issue by IonBazan** [FriendsOfPHP/PHP-CS-Fixer#5832] opened 2021-08-03 07:27 UTC
## Bug report

   * PHP version: PHP 8.0.8 (cli) (built: Jul 12 2021 02:58:53) ( NTS )
   * PHP CS Fixer version: 3.0.1

A nested generic and array phpdoc causes a trailing pipe `|` to be added

### Code snippet that reproduces the problem

  ```diff
     /**
-     * @return Data<array{enabled: string[], all: array<string, string>}>
+     * @return Data<array{enabled: string[], all: array<string, string>|}>
      */
     public function getFeatures(): Data;
  ```

This started to occur after upgrading from v3.0.0 to v3.0.1.

**Comment by julienfalque** [comment] 2021-08-03 08:29
This looks like a duplicate of #5798.

**Closed by julienfalque** 2021-08-03 08:29 UTC
Labels: kind/bug
