### ISSUE TITLE
Deprecation causes unexpected ErrorException

### ISSUE THREAD

**Issue by alcohol** [FriendsOfPHP/PHP-CS-Fixer#2919] opened 2017-07-18 06:24 UTC
The PHP version you are using:
```
rob@macbookpro.local > php -v
PHP 7.0.20 (cli) (built: Jun 23 2017 07:46:30) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

PHP CS Fixer version you are using:
```
rob@macbookpro.local > bin/php-cs-fixer -v
PHP CS Fixer version 2.3.2 by Fabien Potencier and Dariusz Ruminski
```

Config
``` php
rob@macbookpro.local > cat .php_cs.dist
<?php

$finder = new PhpCsFixer\Finder();
$config = new PhpCsFixer\Config('***');

$finder
    ->in('src')
    ->exclude('src/frontend')
;

$config
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        '@PHP70Migration' => true,
        'concat_space' => ['spacing' => 'one'],
        'no_useless_else' => true,
        'not_operator_with_space' => true,
        'ordered_imports' => ['sortAlgorithm' => 'alpha'],
    ])
    ->setFinder($finder)
;

return $config;
```

Command
```
rob@macbookpro.local > bin/php-cs-fixer fix --allow-risky yes
You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
Loaded config *** from "***/.php_cs.dist".
Using cache file ".php_cs.cache".


  [ErrorException]
  Passing "replacements" at the root of the configuration is deprecated and will not be supported in 3.0, use "replacements" => array(...) option instead.


fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...

```

I'm not even using replace myself... I'm guessing the migration fixer does, but why does it throw an exception?

**Comment by julienfalque** [comment] 2017-07-18 08:50
@SpacePossum provided a fix for the deprecation notices in built-in rulesets. But I'm still wondering how these silenced notices can still be converted into an `ErrorException`: the error handler checks the `error_reporting` level before doing so, this should not occur for silenced errors.

I see you are running the tool with XDebug enabled, is it possible that you have `xdebug.scream` setting enabled? I'm able to reproduce the `ErrorException` issue when enabling this setting. Thanks @SpacePossum for the hint ;)

**Comment by alcohol** [comment] 2017-07-18 09:03
You are correct. I do have xdebug.scream turned on in my current environment it seems. I think the issue is on my side :-)

**Comment by keradus** [comment] 2017-07-18 09:35
Great to hear, closing due to discussion and opened PR ;)

**Closed by keradus** 2017-07-18 09:35 UTC
Labels: question
