### ISSUE TITLE
Linefeed fixer cannot be blacklisted

### ISSUE THREAD

**Issue by amorel-ljsl** [FriendsOfPHP/PHP-CS-Fixer#1887] opened 2016-04-25 17:12 UTC
Hi,

I'm working on Windows with the need to have CRLF EOLs. When running PHP-CS-FIXER, i add the option `--fixers=-linefeed`, as such:

> "C:\php\php.exe" "C:\php7\lib\php-cs-fixer.phar" "fix" "C:(...)\ColumnHydrator.php" "--level=symfony" "--fixers=-linefeed" "--diff" "--ansi" "--no-interaction"

**My file gets converted to LF EOL except for the first line**! Doesn't seem the wanted behaviour to me.

**Comment by GrahamCampbell** [comment] 2016-04-25 18:12
That's because our other fixers assume the correct linefeed is used when they make modifications (but not otherwise).

**Comment by amorel-ljsl** [comment] 2016-04-25 19:41
Hi @GrahamCampbell,
I'm not sure to understand: in my experience the whole file is changed to LF EOLs, even when the other fixers don't touch anything.
But anyway: is it the desired behaviour, to get fixers other than linefeed to change line endings? That makes it unusable on non-LF workflows...

**Comment by SpacePossum** [comment] 2016-05-17 07:10
>I'm not sure to understand: in my experience the whole file is changed to LF EOLs, even when the other fixers don't touch anything.

This should not happen as fixers have one task, however;

> is it the desired behaviour, to get fixers other than linefeed to change line endings? That 

no, but some of the fixer might add linebreaks when needed. Those fixers use `\n` for linebreaks. Currently PHP-CS-Fixer can not be configured to use `\r\n` for linebreaks.

Can you provide the version of the PHP-CS-Fixer you are using together with your configuration, command line (with arguments) and PHP version and maybe a small example of file that gets touched the wrong way, with that we can start debugging.

**Comment by keradus** [comment] 2016-05-18 11:12
a lot of playing around new lines is made by `braces` fixer. if you have a lot of fixes from it then that could be the reason why you have whole file changed.

Indeed, we are assuming correct line ending, which in general in PHP world is `\n`. If you are not following it we have a fixer for you ;)
If you don't want to switch, feel free to contribute to make it configurable.

**Comment by SpacePossum** [comment] 2016-07-25 06:08
ping @amorel-ljsl can you provide an example?

**Comment by amorel-ljsl** [comment] 2016-08-02 09:35
Hi @SpacePossum, 
We are not using PCF anymore on the current project. However the example is very easy to reproduce, on Windows. If i run any PHP file through the fixers, with the command line given in first post, the whole file becomes LF, except for the first line.
If you absolutely need a file, i can try to make one example for you, by the end of the week.

@keradus : not sure what you mean by "correct line ending" :) line ending is not a language thing, but more of a platform one. And sometimes (rearely), some external factors keep you stuck with \r\n, as it is in our case.

**Comment by SpacePossum** [comment] 2016-12-07 20:25
@amorel-ljsl you can retry using the 2.0 release, there you can configure the line ending (i.e `\r\n` vs. `\n`) explicitly.
I could not reproduce your issue, so in order to bug hunt your case further we really need an (minimal) code sample showing the issue, the PHP-CS-Fixer version you are using (`php-cs-fixer -V`), PHP version (`php -v`) and the version of Windows.

**Comment by keradus** [comment] 2016-12-07 20:58
I think this issue is not longer valid on 2.x line.
if it is, create new, clean issue with requested informations.
closing

**Closed by keradus** 2016-12-07 20:58 UTC
