### ISSUE TITLE
Multiple sub generics split up in wrong way

### ISSUE THREAD

**Issue by gisostallenberg** [FriendsOfPHP/PHP-CS-Fixer#6157] opened 2021-12-09 11:36 UTC
## Bug report
* PHP version: 8.0
* PHP CS Fixer version: PHP CS Fixer 3.3.3-DEV
* the configuration used: `return (new PhpCsFixer\Config())->setRules(['@Symfony' => true]);`

### Code snippet that reproduces the problem
```php
/**
 * @return array<int, array<string, mixed>|Collection<string, mixed>>
 */
function example(): array
{
    // ...
}
```

![image](https://user-images.githubusercontent.com/11526270/145388003-d2547f66-9c34-4c36-bb71-b43f949d4ad9.png)

I would expect PHP CS Fixer to do no changes.

**Comment by julienfalque** [comment] 2021-12-11 16:13
Closing because I think this is a duplicate of #5921. If not, please let me know.
Also, can you please give #6063 a try and tell us whether it fixes the issue for you?

**Closed by julienfalque** 2021-12-11 16:13 UTC
Labels: kind/bug

**Comment by gisostallenberg** [comment] 2021-12-13 10:32
Yes https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6063 fixes the issue. I fixed it in my code base for now by defining all parts separately, as in `array<int, array<string, mixed>>|array<int, Collection<string, mixed>>`.

Thanks for your response.
