### ISSUE TITLE
PhpdocTypesFixer - Resource class in PhpDoc type is incorrectly replaced with 'resource' lowercase

### ISSUE THREAD

**Issue by oniric85** [FriendsOfPHP/PHP-CS-Fixer#2678] opened 2017-04-07 12:46 UTC
Hi,
I'm using the phpdoc_types fixer and I have a class called Resource (with the R) used by my code. The fixer is always converting the phpdoc type annotations to "resource" with the lower version.

Here is an example code which is incorretly fixed:

```
 /**
   * The resource.
   *
   * @var Resource
   */
   protected $resource;

```
I would expect the fixer to understand that in this case Resource is a class name, not the PHP internal type.

I'm using 5.6.30 with PHP CS Fixer version 2.2.0.

**Comment by ntzm** [comment] 2017-04-07 20:40
This issue also affects classes called:

- Double
- Boolean
- Integer
- Iterable
- Mixed
- Object
- Real
- Void (on PHP < 7.1)

Probably some differences between PHP versions, all test on 7.0.13

**Comment by GrahamCampbell** [comment] 2017-04-07 21:26
This is not a bug. This is intentional. Please turn off the fixer that does this, if you don't want that behaviour.

**Comment by oniric85** [comment] 2017-04-08 07:25
I see, is it possible to turn off the fixer only for specific files?

**Comment by keradus** [comment] 2017-04-12 19:03
no, not currently.

cool, closing due to discussion

**Closed by keradus** 2017-04-12 19:03 UTC
Labels: to verify

**Comment by SpacePossum** [comment] 2017-04-12 20:56
I would welcome an enhancement where the fixer checks if any of the keywords are imported as a class from another namespace (by using `use`) as well and if so skip the fixing. However lets only continue on this only if someone has the time to make such change ;)

**Comment by oniric85** [comment] 2017-04-13 09:08
Hi @SpacePossum, I guess using `class_exists` is not an option here. Which could be a possible approach? I'm trying to understand if it's something I could do with my basic knowledge of the code base :)

**Comment by SpacePossum** [comment] 2017-04-13 09:27
Hi :)
`class_exists` would indeed not work as we do not class load the code we are fixing.
Since we are looking at the `Tokens` we could look for `Tokens` that make up `use`-statements, similar as the `NoUnusedImportsFixer` finds those. Based on the findings we could do a bit of better fixing as we than we would know which `classes` are explicit imported. However this would be tweak and not a trivial thing to build.

**Comment by keradus** [comment] 2017-04-13 11:43
> I would welcome an enhancement where the fixer checks if any of the keywords are imported as a class from another namespace (by using use) as well and if so skip the fixing. However lets only continue on this only if someone has the time to make such change ;)

**Comment by SpacePossum** [comment] 2017-04-13 12:38
Indeed, these cases we do not know, i.e. not covered by ` than we would know which classes are explicit imported`. Still it would be nice tweak as the ones that are explicitly imported by `use` statements are not fixed anymore, so perfect; no, but better ;)

**Comment by keradus** [comment] 2017-04-14 10:32
naming sth after internal PHP class is bad practice anyway. I would accept such an improvement, but for me we could spent time on sth more important

**Comment by gisostallenberg** [comment] 2022-03-15 08:58
An easy work around is to alias the import.
```php
<?php
use SomeNamespace\Resource as SomeResource;

// ...
class Foo {
    /**
     * .... 
     *
     * @param SomeResource $resource
     */
    // ...
}
```
