### ISSUE TITLE
Excluded dirs not excluded

### ISSUE THREAD

**Issue by wowcut** [FriendsOfPHP/PHP-CS-Fixer#2956] opened 2017-08-02 09:39 UTC
It looks like directories contained in `exclude()` are not excluded. I have something like this in a `.php_cs.dist` file in the project directory:
```php
$finder = PhpCsFixer\Finder::create()
	->exclude(array('.git', 'donotprocess', 'something'))
	->in(__DIR__);

return PhpCsFixer\Config::create()
	->setIndent("\t")
	->setRules([
		'@PSR2' => true,
		'@Symfony' => true
	])
	->setFinder($finder);
```
php-cs-fixer uses this file: 
```
Loaded config default from "/dir/to/source/.php_cs.dist".
```
However I can see in the `--verbose` output of the tool that files inside excluded directories have been processed, e.g.:
```
...
7) /donotprocess/index.php (full_opening_tag, no_spaces_inside_parenthesis, elseif, no_trailing_whitespace, binary_operator_spaces, include, single_quote, braces)
...many more...
```

**Comment by keradus** [comment] 2017-08-02 10:53
If you ask for help, provide all requested data:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.github/ISSUE_TEMPLATE

**Comment by wowcut** [comment] 2017-08-02 13:02
Not asking for help just trying to help with reporting a bug. Here is some additional info:
```
> php -v
PHP 7.1.7 (cli) (built: Jul 24 2017 11:03:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7, Copyright (c) 1999-2017, by Zend Technologies

> php-cs-fixer -V
PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski
```
The actual command I run from the project directory with the described `.php_cs.dist` file:
```
php-cs-fixer --verbose fix .
``` 
is there anything more you need?

**Comment by keradus** [comment] 2017-08-02 13:50
If you report a bug (or at least you think so), then it's even more crucial to provide information we asked for in advance, then you would not have ping-pong but answer right away ;)

> php-cs-fixer --verbose fix .

You just override whole finder located in config file here by that `.`
`php-cs-fixer --verbose fix path` means "i don't care what i chosen in config file, fix `path` !"
and as you overwritten path, exclusion got lost.

having fully configured finder in config file, you don't need to provide path at all:
`php-cs-fixer --verbose fix`.

If you want you could combine flexibility of providing paths as CLI args and exclusions from config file using `--path-mode=intersection`, for that read README for details.

Closing as not a bug.

**Closed by keradus** 2017-08-02 13:50 UTC
Labels: question

**Comment by wowcut** [comment] 2017-08-02 15:47
Thank you very much taking your time explaining this detail. 

You should mention this behavior explicitly in the docs, it was totally not intuitive for me that **`path`** on the command line would override an **`exclude`** in a config file - is not obvious that these differently named options could possibly affect each other. One sentence in the second paragraph of the [Usage](https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage) section of the Readme might be enough, e.g.:

_Please note that using the `path` command argument will also disable any excluded paths specified in a config file!_

**Comment by keradus** [comment] 2017-08-02 16:04
Please feel free to open PR :+1:
