### ISSUE TITLE
Force constructor promotion in php 8

### ISSUE THREAD

**Issue by Legion112** [FriendsOfPHP/PHP-CS-Fixer#6345] opened 2022-03-25 12:14 UTC
## Rule request
In PHP 8 there is a short way to assign contractor property  to the class called [contractor promotion](https://stitcher.io/blog/constructor-promotion-in-php-8)
It would be nice to be able to force this rule if it possible. 

### Code snippet that shows how the rule would fix PHP code

  ```php
  <?php
class CustomerDTO
{
    public string $name;

    public string $email;

    public DateTimeImmutable $birth_date;

    public function __construct(
        string $name, 
        string $email, 
        DateTimeImmutable $birth_date
    ) {
        $this->name = $name;
        $this->email = $email;
        $this->birth_date = $birth_date;
    }
}
  ```
Will look like 
  ```php
class CustomerDTO
{
    public function __construct(
        public string $name, 
        public string $email, 
        public DateTimeImmutable $birth_date,
    ) {}
}
  ```

**Comment by SpacePossum** [comment] 2022-03-25 21:00
Hi and thanks for sharing this idea!
I believe it is a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5956 and as such I'm going to close here, let me know if not and I'll reopen :)

**Closed by SpacePossum** 2022-03-25 21:00 UTC
Labels: kind/feature request
