### ISSUE TITLE
File not being procesed properly

### ISSUE THREAD

**Issue by raptor235** [FriendsOfPHP/PHP-CS-Fixer#1878] opened 2016-04-19 16:53 UTC
I'm running the php-cs-fixer lib through atom's beautifier package... and in some cases just not getting proper results... 

![image](https://cloud.githubusercontent.com/assets/313825/14647881/a56afe94-062d-11e6-8a94-10a0549fc72e.png)

Any idea why lines 8 and on aren't properly indented? 

I tried running the file through command line and same result.

**Comment by SpacePossum** [comment] 2016-04-19 17:04
Hi,
Thanks for the report. This could be caused by a few things, like a bug in the fixer or because we don't have the feature to fix what you (yet). I suppose your screenshot is the input for the fixer? 
In that case I think your report is the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1438 (or at least has the same root cause)

**Comment by raptor235** [comment] 2016-04-20 20:54
Yep that's correct. Thanks @SpacePossum

**Comment by keradus** [comment] 2016-04-20 21:44
Closing as feature request duplicate

**Comment by keradus** [comment] 2016-04-20 21:45
@raptor235 please, feel free to contribute and propose new fixer for that !

**Closed by keradus** 2016-04-20 21:44 UTC
