### ISSUE TITLE
`php-cs-fixer self-update` reverts to old version of PHP-CS-Fixer 

### ISSUE THREAD

**Issue by PurpleBooth** [FriendsOfPHP/PHP-CS-Fixer#2995] opened 2017-08-22 09:07 UTC
My PHP Version
```
$ php  -v
PHP 7.1.8 (cli) (built: Aug  7 2017 19:51:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.17.3~mac-x64-non_zts71, https://blackfire.io, by SensioLabs
```

Starting PHP-CS-Fixer version
```
$ php-cs-fixer --version
PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski (63661f3)
```

When you self update
```
$ php-cs-fixer self-update
php-cs-fixer updated (v1.13.2)
$ php-cs-fixer --version
You are running PHP CS Fixer v1, which is not maintained anymore. Please update to v2.
If you need help while solving warnings, ask at https://gitter.im/FriendsOfPHP/PHP-CS-Fixer, we will help you!
PHP CS Fixer version 1.13.2 by Fabien Potencier and Dariusz Ruminski (106313a)
```

**Comment by keradus** [comment] 2017-08-22 09:11
Hi. Thanks for report.
Please use search button next time ;)
duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2991

**Closed** 2017-08-22 09:36 UTC
Labels: duplicate

**Comment by PurpleBooth** [comment] 2017-08-22 09:49
I did see those reports, however they're all closed, indicating that it wasn't a bug.

If it's still happening shouldn't at least one be open?

**Comment by PurpleBooth** [comment] 2017-08-22 09:53
For those coming after me looking for non-dupe issue, it's #2988
