### ISSUE TITLE
Php-cs-fixer acts like "file fixed" but nothing changed

### ISSUE THREAD

**Issue by lamnguyen95** [FriendsOfPHP/PHP-CS-Fixer#2215] opened 2016-10-08 02:20 UTC
Hi, 

I'm using Windows 10 x64. When I try to beautify a .php file, for example:

```
<!DOCTYPE html>
<html>
<body>

<?php

    $x = 10;
$y = 6;

echo                   $x + $y;
?>

</body>
</html>
```

Though the verbose message seems perfectly fine: 

> C:\Users\LAMFM95>php-cs-fixer -vvv fix "L:##Inspiration\L's Projects\N WEB\atom-etady\test.php"
> You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
> .
> Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
> Fixing time per file:
> [0.314 s] L:##Inspiration\L's Projects\N WEB\atom-etady\test.php
> 
> Fixed all files in 0.320 seconds, 8.000 MB memory used

Nothing is changed in the test.php
- In Atom, there're no issues on syntax notified. When run php-cs-fixer, it said "Your code look perfect... Nothing to fix!". I tried Atom-Beautify with necessary configuration but my code wasn't fixed.
- I tried running php-cs-fixer using both .phar distribution and composer's installation but the problem was still there.
- I switched between some PHP versions (5.5 5.6 7.1) but no help :(

**Comment by SpacePossum** [comment] 2016-10-08 07:47
Hi,

I think you setup might actually be fine. Could you try to modify this line
```
echo                   $x + $y;
```
into this;
```
echo                   $x     +   $y   ;
```
and run the tooling again? I would expect the fixer to fix the spacing after `$x`, `+` and `$y`.
The white space after `echo` and before `$x` is not fixed by the fixer ATM (but I tried mast branch only).

Kindly note that the fixer will report `Fixed all files` even if it didn't change anything. You can check the exit code if you want to know if something is changed (0 - nothing changed, 1 - something changed (for the 1.x releases)). Also if something is changed by a fixer it will show up in the output (as you are running the tooling with `-vvv`), so the absence of a list changes tells you nothing has changed on the file ;)

**Comment by SpacePossum** [comment] 2016-10-26 17:09
ping @lamnguyen95

**Comment by rgfx** [comment] 2016-11-22 16:03
@SpacePossum I have this same issue - Fixed all files in 0.087 seconds, 6.000 MB memory used

I purposely jacked up to code to make sure. 

     <?php 
				endwhile;
				 ?>
								<?php wp  _reset_pos tdata();?>
							</div>
				<?php } ?>

no change

**Comment by SpacePossum** [comment] 2016-11-22 22:57
@rgfx thanks for the follow up!

Looking at your example, the following would be the best outcome after fixing I think
```php
 <?php
    endwhile;
?>
							<?php wp  _reset_pos tdata();?>
						</div>
			<?php } ?>
```

although the `wp _reset...` doesn't look like valid PHP to me.

What needs clarification on the issue is whether or not the fixer states that something does not need to be fixed while it does (would be a bug). Or the end user expected changes while there aren't (would be a missing feature, i.e. feature request). I suspect the later.

**Comment by SpacePossum** [comment] 2017-01-26 22:44
ping @lamnguyen95 and @rgfx , more details would help here :)

**Comment by SpacePossum** [comment] 2017-02-25 19:48
I'm closing this because the details to resolve this issue are not provided.
The request to fix more indent cases is notes, however this is not what the issue is about.
Thank you all for reporting, feel free to comment more on this if I missed something :)

**Closed by SpacePossum** 2017-02-25 19:48 UTC

**Comment by ttamnedlog** [comment] 2017-05-02 20:56
@SpacePossum I have been experiencing this same issue for quite some time. I am on MacOS Sierra, not Windows, but I have the same results. PHP-CS-Fixer never proposes any changes. It's possible I'm a PHP rockstar, but I doubt it! I tried the basic example proposed by the @lamnguyen95 and added spaces after the `$x` and `+` and `$y` as you suggested. No changes by PHP-CS-Fixer occurred.

**Comment by photocurio** [comment] 2017-08-19 00:08
I have the very same issue

**Comment by keradus** [comment] 2017-08-19 08:31
are you able to prepare full report with steps to reproduce ?

**Comment by photocurio** [comment] 2017-08-19 16:21
@keradus, I was wrong. php-cs-fixer is making changes to my code, just not helpful changes. I'll look into configuration.

**Comment by HenryHaller** [comment] 2020-01-29 23:04
I have a similar issue. I installed and tried using php-cs-fixer but it seems to do literally nothing.

```Using cache file ".php_cs.cache".
➜  php cat index.php              
<!doctype html>
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<title>
Multiplication table
</title>
</head>
<body>
<div class="container">
Multiplication Table</div>
<body>
</html>
➜  php php-cs-fixer fix index.php 
Loaded config default.
Using cache file ".php_cs.cache".
➜  php cat index.php              
<!doctype html>
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<title>
Multiplication table
</title>
</head>
<body>
<div class="container">
Multiplication Table</div>
<body>
</html>
➜  php which php-cs-fixer   
/usr/local/bin/php-cs-fixer
➜  php php-cs-fixer --version
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski (c8afb59)
➜  php 
```

**Comment by SpacePossum** [comment] 2020-01-30 07:14
Hi @HenryHaller ,

The PHP-CS-Fixer doesn't fix your file because it only contains html and none of out PHP-code-rules fixes html.
