### ISSUE TITLE
Indent is applied every time php-cs-fixer is run

### ISSUE THREAD

**Issue by phil-davis** [FriendsOfPHP/PHP-CS-Fixer#6481] opened 2022-07-13 16:06 UTC
## Bug report
Each time that I run php-cs-fixer 3.9.1 3.9.2 or 3.9.3 it keeps adding more indent to an array structure like below.

```
rm .php-cs-fixer.cache
php -ee d zend.enable_gc=0 vendor-bin/owncloud-codestyle/vendor/bin/php-cs-fixer fix -vv --diff --allow-risky yes
```
Then commit the changes.
Then repeat again, the indent is increased, commit the changes.
Keep repeating - the indent keeps increasing.
php-cs-fixer itself is not happy with the indent fix that it just applied.

See demo PR https://github.com/owncloud/core/pull/40202 - in the 3rd, 4th and 5th commits the indent of a lot of places keeps increasing.

This makes it impossible to commit code that php-cs-fixer is happy with and will pass CI. When the CI pipeline runs code-style checks, it wants to always add another indent.

### Code snippet that reproduces the problem

  ```php
	public function deleteKey($app, $key) {
		$this->emittingCall(function () use (&$app, &$key) {
			$this->loadConfigValues();

			$sql = $this->conn->getQueryBuilder();
			$sql->delete('appconfig')
				->where($sql->expr()->eq('appid', $sql->createParameter('app')))
				->andWhere($sql->expr()->eq('configkey', $sql->createParameter('configkey')))
				->setParameter('app', $app)
				->setParameter('configkey', $key);
			$sql->execute();

			unset($this->cache[$app][$key]);
			return true;
			}, [
							'before' => ['app' => $app, 'key' => $key],
							'after' => ['app' => $app, 'key' => $key]
						], 'appconfig', 'deletevalue');
	}

  ```

The lines down the end keep getting more indent added:
```
							'before' => ['app' => $app, 'key' => $key],
							'after' => ['app' => $app, 'key' => $key]
						], 'appconfig', 'deletevalue');
```

**Comment by julienfalque** [comment] 2022-07-15 16:23
Thanks. This seems to be fixed by #6480, can you give it a try?

**Comment by phil-davis** [comment] 2022-07-15 16:28
> Thanks. This seems to be fixed by #6480, can you give it a try?

will do - it's late here so I will play with it tomorrow

**Comment by phil-davis** [comment] 2022-07-16 03:56
There are still cases where the indent is constantly increased on every run of php-cs-fixer. See each commit in demo PR https://github.com/owncloud/core/pull/40211

https://github.com/owncloud/core/pull/40211/commits/8f4a7ae580d32f14f1eefe59d08144b743f789de

https://github.com/owncloud/core/pull/40211/commits/c914206663239ae28b8830f862ec7f944fa132e7

https://github.com/owncloud/core/pull/40211/commits/e2f2b1fe80508f16e67853fcfbdced4b72f4584e

https://github.com/owncloud/core/pull/40211/commits/a04b87cada26afd1e824feac383c7b84b0210a67

**Comment by driehle** [comment] 2022-07-27 11:23
I can confirm the issue with PHPCSFixer 3.9.5 and the following config:

```php
return (new PhpCsFixer\Config())
    ->setUsingCache(true)
    ->setCacheFile(__DIR__ . '/.php-cs-fixer.cache')
    ->setRules([
        '@PSR12' => true,
        '@Symfony' => true,
        '@DoctrineAnnotation' => true,
        '@PHP80Migration:risky' => true,
        '@PHP81Migration' => true,
        'align_multiline_comment' => ['comment_type' => 'phpdocs_like'],
        'concat_space' => ['spacing' => 'one'],
        'combine_nested_dirname' => true,
        'dir_constant' => true,
        'echo_tag_syntax' => ['format' => 'long'],
        'function_to_constant' => true,
        'heredoc_indentation' => ['indentation' => 'same_as_start'],
        'is_null' => true,
        'linebreak_after_opening_tag' => true,
        'no_alternative_syntax' => false,
        'no_superfluous_elseif' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'non_printable_character' => true,
        'nullable_type_declaration_for_default_null_value' => true,
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_order' => true,
        'phpdoc_separation' => false,
        'ternary_to_null_coalescing' => true,
    ])
    ->setRiskyAllowed(true)
    ->setFinder($finder);
```

**Comment by julienfalque** [comment] 2022-08-01 16:07
Since this issue seems to only occur with files that mix PHP and HTML now, I'm going to close here and keep #6521 to track it.

**Closed by julienfalque** 2022-08-01 16:07 UTC
Labels: kind/bug
