### ISSUE TITLE
File encoding get changed after fixing

### ISSUE THREAD

**Issue by jfcherng** [FriendsOfPHP/PHP-CS-Fixer#3579] opened 2018-03-06 04:33 UTC
#### The PHP version you are using (`$ php -v`):
=> 7.2.3

```
[Clover@Clover-NB test]$ php -v
PHP 7.2.3 (cli) (built: Feb 28 2018 06:05:12) ( NTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.10.3

```
[Clover@Clover-NB test]$ php-cs-fixer -V
PHP CS Fixer 2.10.3 Bowling Bear by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix --verbose

```
[Clover@Clover-NB test]$ php-cs-fixer fix --verbose
Loaded config default from "D:\_Download\test\.php_cs".
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) src\test.php (braces)
```

#### The configuration file you are using, if any:
```php
<?php

$config = PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('libs')
            ->exclude('tests/Fixtures')
            ->exclude('var')
            ->exclude('vendor')
            ->in(__DIR__)
    )
;

return $config;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
**UTF-8 file**
```php
<?php

class ClassName
{
// 入
}
```

 * with unexpected changes applied when running PHP CS Fixer:
**NOT detected as UTF-8 file**
```php
<?php

class ClassName
{
    // å…    ¥
}
```

 * with the changes you expected instead:
**UTF-8 file**
```php
<?php

class ClassName
{
    // 入
}
```

**Comment by keradus** [comment] 2018-03-06 12:19
hm...
what are the newlines in input/outputs files ?

**Comment by kubawerlos** [comment] 2018-03-06 14:15
New lines are fine, it's the `preg_match` problem again: https://3v4l.org/HBT2u

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3446 will solve this.

And this is actually duplicate of the problem from https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3291.

**Comment by jfcherng** [comment] 2018-03-06 17:42
Guess this could be closed since duplicated?

**Comment by keradus** [comment] 2018-03-08 11:03
Closing by merge of #3446

**Closed by keradus** 2018-03-08 11:03 UTC
