### ISSUE TITLE
[DocBlock] Do not add a trailing dot after :

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfPHP/PHP-CS-Fixer#1086] opened 2015-03-23 14:55 UTC
I'm using the last commit of 2.6 branch (6d4d5f9).
And here is the generated diff:
```diff
     /**
-     * Special arguments:
+     * Special arguments:.
      *
      *  * flags: if set, setFlags() will be called with its value
      *  * exchange: The exchange name to use (default exchange by default)
```

As you can see, php-cs-fixer added a `.` after the `:`. 

I wanted to make a PR; but I'm unable to find the correct fixer.

**Comment by lyrixx** [comment] 2015-03-23 15:01
Just took 5 minutes to find how to fix that ;)

**Comment by GrahamCampbell** [comment] 2015-03-23 15:25
This isn't actually a bug. This is the expected behaviour. You are not allowed to end a short description in a colon.

**Comment by Anahkiasen** [comment] 2015-03-23 15:52
Shouldn't it replace the colon with a period then?

**Comment by GrahamCampbell** [comment] 2015-03-23 15:53
@Anahkiasen No, I think people need to manually fix these cases, because they were probably misusing the short description in the first place.

**Comment by GrahamCampbell** [comment] 2015-03-23 15:54
@lyrixx In your example there, you are actually missing using the short description.

**Comment by GrahamCampbell** [comment] 2015-03-23 15:56
Your entire short description is:

```
Special arguments:
```

And your entire long description is just a list of bullets, which make no sense by themselves.


You need to add a separate short description at the top, actually describing what the method does.

**Comment by keradus** [comment] 2015-03-23 16:59
Agreed with @GrahamCampbell 

btw, cool we have 2.6 already :D

**Comment by keradus** [comment] 2015-04-09 17:45
Closing due to closing of #1087

**Closed by keradus** 2015-04-09 17:45 UTC
Labels: question
