### ISSUE TITLE
Rework priority system

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#4731] opened 2020-01-11 22:31 UTC
See the discussion in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4710. I'd like the following to happen, but instead when using the fixer in combination with the PSR2 ruleset, the blankline is removed.

---

INPUT

```php
<?php

class Example
{
    use Foo, Bar;

    public function baz() {}
}
```

EXPECTED:

```php
<?php

class Example
{
    use Foo;
    use Bar;

    public function baz() {}
}
```

ACTUAL:

```php
<?php

class Example
{
    use Foo;
    use Bar;
    public function baz() {}
}

**Comment by GrahamCampbell** [comment] 2020-01-11 22:33
// cc @kubawerlos, @ julienfalque, @SpacePossum

**Comment by GrahamCampbell** [comment] 2020-01-11 22:33
// cc @kubawerlos, @julienfalque, @SpacePossum

**Comment by SpacePossum** [comment] 2020-01-13 07:16
I think this should be fixed by the `class_attributes_separation` ?

**Comment by julienfalque** [comment] 2020-01-13 08:40
I agree this behavior can be quite unexpected for users. Dependencies between rules are not documented and can lead to unwanted/incomplete changes in case one uses a single rule instead of a ruleset. Single responsability should be about the code, not about the rules themselves. Though this is the way all rules are implemented and changing it would be painful, this won't happen on 2.x branch for sure but maybe we can start thinking about it for 3.x branch.

In this current example, suppose you have a rule `traits_on_single_line` that forces `use` statements to be on the same line. If `single_trait_insert_per_statement` adds a newline, the other rule will then have to remove it. This means `single_trait_insert_per_statement` should be aware of the other enabled rules and their config. If we want to change this, the config has to become global somehow. So in the example above, the fixer would be able to know whether it should add the newline without relying on another rule it doesn't know about. The point is to have the first fixer directly trigger the changes from the second fixer it depends on instead of expecting it to run subsequently, which is not always true. Changes would be applied atomatically, removing priority issues.

**Comment by SpacePossum** [comment] 2020-01-13 08:45
> unwanted/incomplete changes in case one uses a single rule instead of a ruleset.

That is all there is to it IMHO, I think it _is wanted_ and _is complete_ as a single rule. 

@GrahamCampbell proposes different behavior and now that is blown up into priorities, dependencies, etc. (let me claim readability here before anyone else does btw)., but in the end, he wants something else than I wanted when I wrote the fixer. 

If you want the fixer to deal with new lines, indentation, other fixers and what else, please create a ticket for that and reason from there. Do not reason from a fixer that works as intended.

**Closed by SpacePossum** 2020-01-13 08:45 UTC
Labels: kind/rfc
