### ISSUE TITLE
Return fix result to STDOUT

### ISSUE THREAD

**Issue by akalongman** [FriendsOfPHP/PHP-CS-Fixer#1675] opened 2016-01-15 15:10 UTC
@GrahamCampbell how I can return formatted output for this command: ```cat test.php | php-cs-fixer fix  --level=psr2 -```?

**Comment by aschwin** [comment] 2016-03-24 15:33
I have a similar question. PHP Beautifier makes it possible to direct the output to a file with a custom extension (e.g. .fixed). This make it easy to compare in PHPStorm to see what fixes to take over and which not.

So, at least make it possible to use STDOUT or otherwise an output destination would be desired.

**Comment by GrahamCampbell** [comment] 2016-03-24 15:34
Could potnetially be looked at after https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1824?

**Comment by SpacePossum** [comment] 2016-03-24 16:13
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1654 will fix the output streaming to STDOUT vs. STDERR, we are close, hold on a bit longer ;)

**Comment by keradus** [comment] 2016-04-20 09:03
Both PRs merged, closing

**Closed by keradus** 2016-04-20 09:03 UTC
Labels: question

**Comment by sampablokuper** [comment] 2018-06-08 01:54
At time of writing, **this issue has not been fixed.**

However, it should remain closed: not because it has been fixed (to repeat: it has not been), but because it is a duplicate of #454.

Further remarks about this issue should therefore ideally be posted at #454.
