### ISSUE TITLE
[@Symfony] class_attributes_separation + method_argument_space_fixer behavior on recent PHP code

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#5910] opened 2021-08-28 09:17 UTC
## Feature request

I've recently migrated a codebase to PHP > 7.4 and started using typed properties along with Symfony's set. There are two fixers that I had to disable and I'm wondering if they should be adapted to the new possibilities PHP versions offer.

An example file would be : 

```php
<?php

declare(strict_types=1);

namespace App\SomeModule;

final class SomeClass
{
    private ?SomeObject $someObject;
    private array $array = [];

    public function __construct(
        private AnotherObject $anotherObject,
        #[SomeAttribute] private YetAnotherObject $yetAnotherObject,
    ) {}
}
```

Here class_attributes_separation will require an empty line between the two natively typed class (non-promoted) properties.
And method_argument_space_fixer will require an empty line between the two promoted constructors arguments.

I don't think (though that's my opinion) that these two fixers help improve readability here. With the new natively typed system, it's quite readable.

A edge-case I would agree with though would be for method_argument_space_fixer when the attributes are written on a separate line, like it would happen on a Doctrine Entity : 

```php
public function __construct(
    #[ORM\Id]
    #[ORM\Column(name: 'id', type: 'snowflake')]
    private Snowflake $id,

    #[ORM\Column(name: 'label', type: 'string')]
    private string $label,

    #[ORM\OneToOne(targetEntity: ExpenseReportTransition::class)]
    #[ORM\JoinColumn(name: 'current_transition_id', referencedColumnName: 'id', onDelete: 'SET NULL')]
    private ?ExpenseReportTransition $currentTransition = null,
) {}
```

This one deserves a space in between IMHO.

So here it is, I'm curious for your opinions about these fixers and if they need an upgrade or not.
Thanks for your insights !

**Comment by kubawerlos** [comment] 2021-08-28 09:34
For `class_attributes_separation` would https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5871 help?

> method_argument_space_fixer will require an empty line between the two promoted constructors arguments.

This sounds like a bug, but I cannot reproduce it - can you provide a config and code sample that is affected?

**Comment by SpacePossum** [comment] 2021-08-31 07:41
>method_argument_space_fixer will require an empty line between the two promoted constructors arguments.

sounds like a very old PHP8 issue

other issue should be fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5920 , use the `none` configuration option for the `elements` `property` (SF uses `one`)

let me know if not than we can reopen :)  (please provide the fixer version and PHP version you are using than as well)

**Closed by SpacePossum** 2021-08-31 07:41 UTC
Labels: kind/feature request

**Comment by SpacePossum** [comment] 2021-09-11 11:17
or just wait until the fix is released?

**Comment by SpacePossum** [comment] 2021-09-11 11:18
`none` does _not_ describe what you claim, as you can see in the tests, but you would have to use latest master or wait for the next release
