### ISSUE TITLE
allow Symfony 3.0

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfPHP/PHP-CS-Fixer#1491] opened 2015-11-07 11:18 UTC
related to https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/pull/49

**Comment by GrahamCampbell** [comment] 2015-11-07 11:30
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1281.

**Comment by gharlan** [comment] 2015-11-24 21:21
fixed by #1510

**Comment by keradus** [comment] 2015-11-24 21:23
indeed

**Closed** 2015-11-24 21:23 UTC
