### ISSUE TITLE
V2 downloaded but I got V1

### ISSUE THREAD

**Issue by koriym** [FriendsOfPHP/PHP-CS-Fixer#2988] opened 2017-08-19 23:35 UTC
I download v2 but I got the version 1.13.1.

```
$ wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer && chmod +x php-cs-fixer
$ ./php-cs-fixer --version

You are running PHP CS Fixer v1, which is not maintained anymore. Please update to v2.
If you need help while solving warnings, ask at https://gitter.im/FriendsOfPHP/PHP-CS-Fixer, we will help you!
PHP CS Fixer version 1.13.2 by Fabien Potencier and Dariusz Ruminski (106313a)
```

If I specify the version, It's OK.

```
$ wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.4.0/php-cs-fixer.phar -O php-cs-fixer && chmod +x php-cs-fixer
$ ./php-cs-fixer --version
PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski (63661f3)
```

**Comment by SpacePossum** [comment] 2017-08-20 07:48
Thanks for reporting! I've confirmed this.

This seems to be an hosting issue therefor I'm pinging @keradus as I believe he is the one who might be able to fix it.

**Comment by keradus** [comment] 2017-08-20 08:13
I can confirm it. automate website update was not prepare to handle v1 releases anymore, and we just release v1.13.x.
Let me retrigger the website update.

**Comment by keradus** [comment] 2017-08-20 08:32
Done.
Thanks

**Comment by koriym** [comment] 2017-08-20 08:50
Confirmed. 
Thanks

**Comment by LittleBigFox** [comment] 2017-08-21 07:13
Hi!
The "selfupdate" method still download the v1.13,2 over the v2.4...
Best Regards,
LBF

**Comment by keradus** [comment] 2017-08-21 08:49
will be fixed by newest release of 2.x

**Comment by PurpleBooth** [comment] 2017-08-22 09:52
This is still happening for me.

**Comment by SpacePossum** [comment] 2017-08-22 11:19
yeah sorry about that, will be fixed after next 2.x release which should be soon, we all hope ;)

**Comment by julienfalque** [comment] 2017-08-22 12:37
I reopen this issue because a new release will not fix the issue but simply hide it, we should provide a proper fix too.

**Comment by keradus** [comment] 2017-08-22 14:17
issue fixed, closing.

for mechanism preventing issue to happen again, please created dedicated issue.

**Closed by keradus** 2017-08-22 14:17 UTC
