### ISSUE TITLE
binary_operator_spaces breaks union types

### ISSUE THREAD

**Issue by BenMorel** [FriendsOfPHP/PHP-CS-Fixer#5624] opened 2021-04-13 12:14 UTC
## Bug report

Related to #4702 (PHP 8.0 support).

- PHP version: 8.0.3
- PHP CS Fixer version: 2.18.5

When running on a PHP 8 codebase using union types, php-cs-fixer mixes union types with binary "or" operator and wrongly applies the `binary_operator_spaces` fix:

Before:

```php
    private Amount|Rate $value;
```

After:

```php
    private Amount | Rate $value;
```

**Comment by kubawerlos** [comment] 2021-04-13 14:56
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5495

**Closed by kubawerlos** 2021-04-13 14:56 UTC
Labels: kind/bug
