### ISSUE TITLE
'braces' with option 'position_after_functions_and_oop_constructs' = 'next' does not work for multi line methods

### ISSUE THREAD

**Issue by CMalvika** [FriendsOfPHP/PHP-CS-Fixer#3637] opened 2018-03-27 08:54 UTC
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> php 7.1.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> .PHP CS Fixer 2.10.0

#### The command you use to run PHP CS Fixer:
=> fix

#### The configuration file you are using, if any:
```php
=>'braces' => [
                'allow_single_line_closure' => true,
                'position_after_anonymous_constructs' => 'same',
                'position_after_functions_and_oop_constructs' => 'next',
                'position_after_control_structures' => 'same',
            ],
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
=> private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) 
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) {
}
```

 * with the changes you expected instead:
```php
=> private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) 
{
}
```

**Comment by julienfalque** [comment] 2018-04-01 18:16
I think this is the expected behavior: the fixer was implemented with [PSR-2](https://www.php-fig.org/psr/psr-2/#44-method-arguments) in mind:

> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

Maybe the documentation of the fixer should be updated to be more explicit about this. We could also implement a new option to enable the behavior you want, though I'm not a big fan, let's see if more people need it.

**Comment by CMalvika** [comment] 2018-04-03 21:28
Thanks @julienfalque 
i've tried something and opened a pull request..! Let's see if my pull request is qualified enough to merge [#3677](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3677)

Although it didn't pass all the checks.

**Comment by apfelbox** [comment] 2018-08-02 16:28
@julienfalque if this is the intended behavior, then the option should be removed.

Because it says clearly "position after functions and oop constructs" and this statement has nothing to do with PSR-2. In fact, I would argue that this fixer handles a superset of PSR-2, as it is supposed (at least as I read it) both versions.

**Comment by SpacePossum** [comment] 2022-08-27 05:32
In `curly_braces_position` this options value is now called `next_line_unless_newline_at_signature_end` to clarify this behavior.

> then the option should be removed.

We cannot, because of BC reasons, remove or rename an option that is already public.

I don't think we should support this CS style:

```php
private function __construct(
    argument 1,
    argument 2,
    argument 3,
    argument 4
) 
{
}
```

unless it is part of a standard or in use by a bigger FOSS community that I don't know off, so please if so let me know, so I think we can close this isse.

**Closed** 2022-08-28 15:59 UTC
Labels: kind/feature request
