### ISSUE TITLE
Implement trailing comma fixer for @PHP73Migration ruleset

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#4237] opened 2019-01-04 21:30 UTC
```diff
 foo(
     $a,
-    $b
+    $b,
 );
```

**Comment by kubawerlos** [comment] 2019-08-21 22:35
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4135?

**Comment by julienfalque** [comment] 2019-08-22 06:37
Indeed.

**Closed by julienfalque** 2019-08-22 06:37 UTC
Labels: feature request
