### ISSUE TITLE
Add a switch to print fixed code to stdout.

### ISSUE THREAD

**Issue by naquad** [FriendsOfPHP/PHP-CS-Fixer#454] opened 2014-08-17 16:48 UTC
I'm trying to use php-cs-fixer as a filter program so i need it to accept input on stdin and print output on stdout, but it doesn't. It would be super awesome if it had a switch to just print the resulting code to make similar invocation possible:

```
cat some_code.php | php-cs-fixer fix --stdout -
```

**Comment by lxg** [comment] 2015-05-27 07:26
>  Is there anyone who want to have that feature?

Yes, this would really be a great feature. Outputting PSR-2 fixed code to STDOUT would be great for usage within IDEs, e.g. Bluefish and Kdevelop allow passing files and file chunks through filters. Would be great to be able to format the code of an open file with a simple key stroke in the IDE.

**Comment by keradus** [comment] 2015-05-27 13:56
> file chunks through filters

most fixers wont work on file chunks

**Comment by lxg** [comment] 2015-05-27 20:31
@keradus: Ok, it was just an example. Anyway it would be very helpful to have support for STDIN/STDOUT. Pressing a key to have a complete file properly formatted, would help a lot. Every decent IDE has this feature, and *php-cs-fixer* is a great tool for PSR-2 compliant PHP code formatting.

**Comment by keradus** [comment] 2015-05-28 06:05
BTW support of stdin is already implemented. Just the stdout is currently the same as in `dry-run` mode and you need here a full file on output and non other information (what is BC break).

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.9/Symfony/CS/Console/Command/FixCommand.php#L277

**Comment by lxg** [comment] 2015-05-28 07:22
Uh, ok ... but it's pretty useless at the moment. The only output is

    $ cat SomeFile.php | php-cs-fixer fix -
    1) stdin.php
    Fixed all files in 0.084 seconds, 6.500 MB memory used

What is that good for?

**Comment by keradus** [comment] 2015-05-28 07:37
That is why I said what is currently and what need to be changed (and that is that BC break you need to make)

**Comment by lxg** [comment] 2015-05-28 08:36
Ok, I'll write a patch. Do you think it is better to send the debug information (“*Fixed all files in 0.084 seconds, 6.500 MB memory used*”) to STDERR or to omit it altogether?

**Comment by keradus** [comment] 2015-05-28 08:37
Wouldn't it already printed on stderr ?

**Comment by lxg** [comment] 2015-05-28 10:18
Nope. Everything is sent through `$output` which is mapped to STDOUT. Also, appending `2>/dev/null` to the command line still show everything. But, no problem, I'll fix that, too.

**Comment by SpacePossum** [comment] 2015-05-28 10:23
(writing to STDERR is done/fixed on master/2.0)

**Comment by keradus** [comment] 2015-05-28 10:59
And @lxg need to use master due to BC break

**Comment by lxg** [comment] 2015-05-28 10:59
@SpacePossum: Only Progress is written to STDERR. “Loaded config …” and “Fixed all files …” messages as well as the list of fixed files are still written to STDOUT. I would propose to write only “payload” information to STDOUT, i.e. streams of fixed code. Informational text should go to STDERR. This is like most other *nix tools behave. Or, alternatively, don't print any informational text unless the verbosity level is at least 2.

**Comment by SpacePossum** [comment] 2015-06-10 07:24
If https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1247 makes it into 2.0 a new (custom) output class can be made to that will be the only one writing to STDOUT.

**Comment by keradus** [comment] 2015-09-27 14:12
This thread is dead.
Closing due to lack of interest by anyone.

**Closed by keradus** 2015-09-27 14:12 UTC
Labels: feature

**Comment by sampablokuper** [comment] 2018-06-08 01:44
@lxg [wrote](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/454#issuecomment-106232279):
> Do you think it is better to send the debug information (“_Fixed all files in 0.084 seconds, 6.500 MB memory used_”) to STDERR or to omit it altogether?

When present, it should be written to STDERR. If it is output by default, then the user should be able to silence it with a `--quiet` option. (Conversely, if it is *not* output by default, then the user should be able to enable it with a `--verbose` option.)

**Comment by sampablokuper** [comment] 2018-06-08 01:51
Please can this issue be reopened? **It has not been fixed.**

The following remarks are follow-up from #1579, which is a duplicate of this issue.

@stof [wrote]:
> `cat file > php-cs-fixer fix -` should do the work

This, of course, is wrong, because `>` is an inappropriate shell redirection character to use here. Rather than piping the contents of `file` to the command `php-cs-fixer`, it would instead write the contents of `file` to a file called `php-cs-fixer`, creating the latter if necessary. But even we we use `|` instead of `>` per @gharlan 's [correction](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1579#issuecomment-162616905) of @stof's error, the functionality requested in @garak's [opening comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1579#issue-120824852) ("I don't want to pass a path and get the file(s) on that path to be fixed, I want to pass a content as stdin and get the fixed content as stdout") is still not fully present:

```
$ cat 1.php | php-cs-fixer fix --dry-run -
Loaded config default.
Using cache file ".php_cs.cache".
   1) php://stdin

Checked all files in 0.197 seconds, 12.000 MB memory used
```

Yes, PHP-CS-Fixer accepts stdin, which is good. But rather than sending to stdout, as desired, the fixed version of the PHP code that it received via stdin, PHP-CS-Fixer instead sends stdout some lines of metadata (that would more appropriately be sent to stderr).

I think it is also worth gently noting that @stof's [comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1579#issuecomment-162618513):
> use the `--diff` option to get the diff in the output

while presumably well-intentioned, was essentially off-topic, because @garak's post was about retrieving the **fixed PHP code** via stdout, *not* about retrieving a **diff** via stdout.

**Comment by keradus** [comment] 2018-06-08 07:09
Writing (basically the same content) to 5 different, years old (like here, 4!), issues, is not helpful at all - be glad that anyone saw that.
Also, content provided by you does not give any new value, @sampablokuper .

Issues, as claimed during closing them, were not closed because feature were implemented, but because, after initial alignment, nobody was interested in them anymore.

If you want to change that, simply raise a PR.

**Comment by akalongman** [comment] 2018-06-08 08:29
+1 for this feature

**Comment by SpacePossum** [comment] 2018-06-08 10:45
Please open a new issue/PR, a lot has changed since this was discussed so lets start fresh and see what can be done now :)
