### ISSUE TITLE
wrong files included

### ISSUE THREAD

**Issue by theofidry** [FriendsOfPHP/PHP-CS-Fixer#2490] opened 2017-02-01 22:54 UTC
Hey,

For a project, I have the following configuration:

```php
// .php_cs.dist
<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$finder = Finder::create()
    ->in([
        __DIR__.'/src',
        __DIR__.'/tests'
    ])
;

return Config::create()
    ->setRiskyAllowed(true)
    ->setRules([...])
    ->setFinder($finder)
;
```

Yet, when I run it, I can see that the file `var/SymfonyRequirements.php` is affected. Is it the expected behaviour? (I wouldn't expect other directories than the one specified to be appended).

```
$ php -v
PHP 7.1.0-dev (cli) (built: Jan  3 2017 09:51:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
```

PHP CS Fixer version you are using:
```
$ php-cs-fixer -V
PHP CS Fixer 2.0.0
```

**Comment by GrahamCampbell** [comment] 2017-02-01 23:12
What exact command are you using to execute php-cs-fixer please?

**Comment by theofidry** [comment] 2017-02-01 23:17
`$ bin/php-cs-fixer fix`

**Comment by GrahamCampbell** [comment] 2017-02-01 23:23
Hmm, how odd!

**Comment by keradus** [comment] 2017-02-01 23:33
`bin/php-cs-fixer fix -vvv` ?

**Comment by theofidry** [comment] 2017-02-01 23:39
```
$ bin/php-cs-fixer fix -vvv
string(55) "/path/to/project/.php_cs does not exist"
string(50) "pick /path/to/project/.php_cs.dist"
Loaded config default from "/path/to/project/.php_cs.dist".
Using cache file ".php_cs.cache".
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFSFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFSFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) SymfonyRequirements.php (no_unused_imports)
   2) cache/dev/classes.php (method_separation, blank_line_after_opening_tag, single_quote, space_after_semicolon, method_argument_space, no_spaces_inside_parenthesis, whitespace_after_comma_in_array, single_line_after_imports, visibility_required, no_unused_imports, blank_line_before_return, braces, ordered_imports, single_blank_line_at_eof)
   3) cache/dev/templates.php (blank_line_after_opening_tag, no_spaces_after_function_name)
   4) cache/dev/twig/04/04322bc17e41579dcae62857f19b4d96337719200f564a12fe49152c80bd8e0e.php (single_quote, trim_array_spaces, method_argument_space, no_spaces_after_function_name, braces)
   5) cache/dev/twig/06/068121c147d5f683c4905596bda0d71a531125b7d490d87985d204a00c757b23.php (single_quote, trim_array_spaces, method_argument_space, no_spaces_after_function_name, braces)
...
```

Worth noting that there is no `path/to/project/cache/` folder and that the files above are all in `path/to/project/var/`

**Comment by SpacePossum** [comment] 2017-02-02 07:13
Did you modify how the tool finds the configuration file? It surprises me that it finds the configuration @ `/path/to/project/.php_cs.dist` while the tool is located in a `bin/` directory and no `--config` option is passed through the commandline.
Secondly can you try running without the caching (or remove the old cache), just so we exclude that as possible cause.

**Comment by theofidry** [comment] 2017-02-02 09:39
>Did you modify how the tool finds the configuration file?

Nope

>It surprises me that it finds the configuration @ `/path/to/project/.php_cs.dist` while the tool is located in a bin/ directory and no --config option is passed through the commandline.

As I execute it from `/path/to/project` I guess it's taking this place as the current working directory.

>Secondly can you try running without the caching (or remove the old cache), just so we exclude that as possible cause.

Yes, I get this behaviour with or without cache :/

**Comment by keradus** [comment] 2017-02-02 09:45
just a quick shot - is the project public? if so, it would be extra easy for us to debug it

**Comment by theofidry** [comment] 2017-02-02 09:59
unfortunately no :( I will try to reproduce it on a sandbox project.

**Comment by theofidry** [comment] 2017-03-12 23:46
Ok, this seemed to have be caused by adding `""`, e.g. `vendor/bin/php-cs-fixer fix ""`. Another weird thing is that it made it display the message:

```
Loaded config default from "/path/to/project//.php_cs.dist".
```

(yes with the double slash...)

You can find a dummy project [here](https://github.com/theofidry/phpcsfixer-demo0) where you can reproduce this issue.

**Comment by keradus** [comment] 2017-03-13 15:54
hm... why are you adding empty path as argument ?

**Comment by theofidry** [comment] 2017-03-13 16:00
by mistake, a shell script with something like `bin/php-cs-fixer fix "$FOO"` with `FOO` not defined so resulting in an empty string...

You can dismiss the issue by saying it's a misuse, but I must admit I would expect an error in that situation rather than this weird situation...

**Comment by keradus** [comment] 2017-03-13 16:11
the error report is fine, i was just curious about your usage case, thanks for explaining ;)

**Comment by SpacePossum** [comment] 2017-10-19 17:25
ping @keradus , like to know what the issue is so I can help out if you've no time for this one :)

**Comment by gokhankarol** [comment] 2020-05-01 22:07
⚜️

**Comment by julienfalque** [comment] 2020-05-14 07:33
Closing as #4940 was merged.

**Closed by julienfalque** 2020-05-14 07:33 UTC
Labels: kind/enhancement, topic/I/O
