### ISSUE TITLE
Converting nullable typehints using Union

### ISSUE THREAD

**Issue by BrekiTomasson** [FriendsOfPHP/PHP-CS-Fixer#6530] opened 2022-08-02 13:48 UTC
## Feature request

When type-hinting method parameters and return types, both of these are valid PHP:

```php
public function doSomeStuff(?string $input) : ?string
{
    // stuff goes here.
}

public function doSomeStuff(string|null $input) : string|null
{
    // stuff goes here.
}
```

It would be good to have a rule that allows you to define which of the two you prefer so that it automatically converts between the two. The rule should also have an optional parameter to decide whether to put the `null` at the beginning of the Union Type list or at the end.

**Comment by julienfalque** [comment] 2022-08-07 13:42
Duplicate of #5651.

**Closed by julienfalque** 2022-08-07 13:42 UTC
Labels: kind/feature request
