### ISSUE TITLE
Files that were not fixed due to errors reported during linting before fixing

### ISSUE THREAD

**Issue by mdecaffmeyer** [FriendsOfPHP/PHP-CS-Fixer#1364] opened 2015-08-27 16:45 UTC
Whenever I try to format files with php-cs-fixer, I have the following message:

"Files that were not fixed due to errors reported during linting before fixing"

The files have correct syntax, it even used to work before on those same files.
When using --verbose option, I see that files are marked:
I-invalid file syntax, file ignored

The version is 2.0-DEV

**Comment by keradus** [comment] 2015-08-27 18:04
Please, try to fix a single file like `php php-cs-fixer fix my\file.php` until you find file that produces error, then please post the file. We will try to figure it out then

**Comment by GrahamCampbell** [comment] 2015-08-27 18:11
Or turn off linting, then look at the output. You might easily be able to see the file with the syntax error.

**Comment by mdecaffmeyer** [comment] 2015-08-27 23:12
```
<?php
class Test {
}
```
> php-cs-fixer fix --verbose Test.php
**I**
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes,
 F-fixed, E-error
Fixed all files in 0.040 seconds, 4.500 MB memory used
**Files that were not fixed due to errors reported during linting before fixing:**
   1) C:\data\websites\dokagenda-v3\Model\Test.php

How do I turn off linting?

**Comment by GrahamCampbell** [comment] 2015-08-28 08:30
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Config/Config.php#L63

**Comment by keradus** [comment] 2015-08-28 08:50
Try setting php executable (available on 2.x line): https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Config/Config.php#L188

**Comment by mdecaffmeyer** [comment] 2015-08-28 11:52
1) With ```->setUsingLinter(false)``` it works, except if I specify a single file, then I have the same message as in intiial post.

```php-cs-fixer fix --verbose .```

Outputs me something like FFFFF etc.
When I executed it once more, it gave SSSSS etc.

```php-cs-fixer fix --verbose Test.php```

Gave me the intial error. Looks like ```->setUsingLinter(false)``` is only effective when fixing a directory of files, and thus doesn't work when trying to fix a single file.

But what exactly is linting and do I need it, enable it and stil try to find the error?

2) @keradus I don't know what i should put in this option, sorry.
I tried ```->setPhpExecutable('C:\\Program Files (x86)\\EasyPHP-DevServer-14.1VC11\\binaries\\php\\php_runningversion\\php.exe')``` and it doesn't work
**Unable to use linter, can not find PHP executable**

**Comment by GrahamCampbell** [comment] 2015-08-28 11:56
Disabling it will prevent the linting errors from showing up so that you can see exactly what went wrong.

**Comment by GrahamCampbell** [comment] 2015-08-28 11:56
Oh, wait, just reread this. It says **before**. Ignore what I've said...

**Comment by mdecaffmeyer** [comment] 2015-08-28 11:58
When I disabled it the files got fixed (and by running it again, skipped). No errors displayed.

**Comment by keradus** [comment] 2015-08-28 12:06
1. each F means that one file was fixed, then you run it again and each S means Skipped, because of cache (file already fixed, no need to fix again)
2. Then sth probably fail with that path, maybe try to put php.exe on env paths? On my side it is working (php in xampp dir)

As we cannot reproduce it - it would be great if you want to help us finding the problem.

On 1.x line you must has `php` command for linting (like php.exe / php.bat) in your env paths.
If you don't have it then linting will always fail. Then, 2.x line fixed it.

On 2.x line we have some more magic. You can configure php executable yourself in Config (eg in .php_cs file), then it is passed here:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Linter/Linter.php#L45
If you don't specify it we try to guess it here:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Linter/Linter.php#L48

If it still won't work, try to put some debugs inside:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/Symfony/CS/Linter/Linter.php#L101

**Comment by mdecaffmeyer** [comment] 2015-08-28 14:01
I var_dump'ed the php executable:
```
        if (null === $phpExecutable) {
            $executableFinder = new PhpExecutableFinder();
            $executable = $executableFinder->find();
            var_dump($executable);
        }
```
This prints: ```string(89) "c:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_r
unningversion\php.exe"```` 

But when I set manually the very same path to Config:
```    ->setPhpExecutable('c:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\php.exe')```
I have the message:
**Unable to use linter, can not find PHP executable**

**Comment by sstok** [comment] 2015-08-29 07:14
What happens if you execute "c:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\php.exe" manually without the php-cs-fixer ?

**Comment by sstok** [comment] 2015-08-29 07:21
Ignore that last command I just woke-up :) 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/646c8446afff44e60b506efa4f773c8b47740ba9/Symfony/CS/LintManager.php#L52

`$process = new Process('php -l '.ProcessUtils::escapeArgument($path));`
What if you provide the full location to the php executable? Note that `Process` adds some more details for Windows and running php is not the same as php.exe

**Comment by mdecaffmeyer** [comment] 2015-08-29 07:48
```$ "c:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\php.exe" --version```
>PHP 5.6.4 (cli) (built: Dec 17 2014 13:21:16)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

If I replace 
```
$process = new Process(sprintf('%s -l %s', $this->executable, ProcessUtils::escapeArgument($path)));
```
by
```
$process = new Process('php -l '.ProcessUtils::escapeArgument($path));
``` 
(from older php-cs-fixer version) it works, files are getting fixed.

**Comment by mdecaffmeyer** [comment] 2015-08-29 08:02
string(51) "**$path:** C:\data\websites\app\Model\Test.php"
string(165) "**$process.commandLine 2.x:** c:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\php.exe -l "C:\data\websites\app\Model\Test.php""
string(79) "**$process.commandLine 1.x:** php -l "C:\data\websites\app\Model\Test.php""

string(48) "**$path:** C:\data\websites\app\tmp7A26.tmp"
string(162) "**$process.commandLine 2.x:** c:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\php.exe -l "C:\data\websites\app\tmp7A26.tmp""
string(76) "**$process.commandLine 1.x:** php -l "C:\data\websites\app\tmp7A26.tmp""

```
    private function createProcessForFile($path)
    {
var_dump('$path: '.$path);
        // in case php://stdin
        if (!is_file($path)) {
            return $this->createProcessForSource(file_get_contents($path));
        }
        $process = new Process(sprintf('%s -l %s', $this->executable, ProcessUtils::escapeArgument($path)));
var_dump('$process.commandLine 2.x: '.$process->getCommandLine());
        $process = new Process('php -l '.ProcessUtils::escapeArgument($path));
var_dump('$process.commandLine 1.x: '.$process->getCommandLine());
        $process->setTimeout(null);
        $process->run();

        return $process;
    }
```

**Comment by mdecaffmeyer** [comment] 2015-08-29 08:04
Looks like
```
%s -l %s
```
should be 
```
"%s" -l %s
```

**Comment by stof** [comment] 2015-08-29 08:22
@keradus the issue is that there is a space in the executable path, and you don't escape things properly when building the process command, so it tries to run ``c:\Program`` as executable.
I suggest you to use the ProcessBuilder, which will handle this for you

**Comment by stof** [comment] 2015-08-29 08:22
@mdecaffmeyer it is not a matter of using Windows or no, but of having spaces in the path to PHP.

**Comment by mdecaffmeyer** [comment] 2015-08-29 08:25
@stof yea I know, I just thought that maybe Linux system directories don't contain usually spaces like on Windows (e.g. "Program Files (x86)").
Anyway, did you see my last comment, just needs to call ```ProcessUtils::escapeArgument()``` on ```$this->executable``` in the command line

**Comment by keradus** [comment] 2015-08-29 11:11
Great you catch the case. Could you send a PR with a fix?

**Comment by mdecaffmeyer** [comment] 2015-08-29 12:12
(I'm not used to PR, so please check if I didn't make any mistake)

**Comment by keradus** [comment] 2015-09-26 07:53
Closing due to merge of #1414

**Closed by keradus** 2015-09-26 07:53 UTC
Labels: bug

**Comment by Trusted97** [comment] 2019-12-19 11:58
Hi i've found this issue while i'm try to resolve my problem. I see that there is no solution, so i've posted the file that are giving me this issue.

```
<?php defined('BASEPATH') or exit('No direct script access allowed');

class Static extends CI_Controller {

  /*
	*
	* Constructor for Static Controller
	*
	*/
	public function __construct(){
		parent::__construct();

	}

  public function privacy_policy(){

		$data["title"] = 'Privacy Policy';
		$data["description"] = '';

		$this->load->view('parts/header', $data);
		$this->load->view('privacy_policy');
		$this->load->view('parts/footer');
  }

  public function terms_of_service(){
		$data["title"] = 'Terms of service';
		$data["description"] = '';

		$this->load->view('parts/header', $data);
		$this->load->view('terms_of_service');
		$this->load->view('parts/footer');
  }

}
```

**Comment by SpacePossum** [comment] 2019-12-19 12:10
Hi @Trusted97 ,

The sample you shared is invalid PHP;

```
$ php -l test.php 
PHP Parse error:  syntax error, unexpected 'Static' (T_STATIC), expecting identifier (T_STRING) in test.php on line 3
Errors parsing test.php
```

as such this tool cannot fix the code style of. If you change your code to valid PHP code it will.

**Comment by timfrith** [comment] 2024-06-25 17:59
I've found an issue that causes the "Files that were not fixed due to errors reported during linting before fixing".

<?php if (something) { ?>
   do something
<? } ?>

If I either change the first tag from <?php to <? or the second from <? to <?php then the file will be fixed.
So if the PHP tag containing the opening of the PHP code block does not match the one used for the closing of the PHP code block it appears the linter will not see the code block ( {} ) as being closed.

**Comment by timfrith** [comment] 2024-06-25 18:01
I've found an issue that causes the "Files that were not fixed due to errors reported during linting before fixing".

```
<?php if (something) { ?>
   do something
<? } ?>
```

If I either change the first tag from <?php to <? or the second from <? to <?php then the file will be fixed.

So if the PHP tag containing the opening of the PHP code block does not match the one used for the closing of the PHP code block it appears the linter will not see the code block ( {} ) as being closed.

**Comment by Wirone** [comment] 2024-06-25 19:14
@timfrith please don't comment on issues closed 9 years ago. If there's any problem, please report a new issue.
