### ISSUE TITLE
Breaking foreach loop

### ISSUE THREAD

**Issue by Petah** [FriendsOfPHP/PHP-CS-Fixer#3221] opened 2017-11-07 07:43 UTC
> The PHP version you are using:
> $ php -v
```
PHP 7.1.5 (cli) (built: May  9 2017 19:48:36) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
```
> PHP CS Fixer version you are using:
> $ php-cs-fixer -V
```
PHP CS Fixer 2.8.0 Round Numbers by Fabien Potencier and Dariusz Ruminski
```

> The command you use to run the fixer (and the configuration file you are using if any).
```
..\..\..\vendor\bin\php-cs-fixer.bat fix router.php --rules=@PSR2
```
> A minimal sample of valid PHP code that is not fixed correctly (if applicable).
```
<?php
$url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
if (is_file(__DIR__ . '/../public/' . $url)) {
    return false;
}
if ($url !== '/' && is_dir(__DIR__ . '/../public/' . $url)) {
    if (!preg_match('~[^/]/$~', $url)) {
        header('Location: ' . rtrim($url, '/') . '/');
        return;
    }
    foreach (new DirectoryIterator(__DIR__ . '/../public/' . $url) as $fileInfo) {
        if ($fileInfo->getFilename() === '.') {
            continue;
        }
        echo '<a href="./' . htmlspecialchars($fileInfo->getFilename(), ENT_QUOTES) . '">' . $fileInfo->getFilename() . '</a><br />' . PHP_EOL;
    }
    return;
}

require __DIR__ . '/../public/index.php';
```
> The fixed version of that code after you run the fixer and the version you expected.

I expect it to basically stay the same, but instead it breaks the foreach loop like:

```
<?php
$url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
if (is_file(__DIR__ . '/../public/' . $url)) {
    return false;
}
if ($url !== '/' && is_dir(__DIR__ . '/../public/' . $url)) {
    if (!preg_match('~[^/]/$~', $url)) {
        header('Location: ' . rtrim($url, '/') . '/');
        return;
    }
    foreach {
        (new DirectoryIterator(__DIR__ . '/../public/' . $url) as $fileInfo) {
        if ($fileInfo->getFilename() === '.') {
            continue;
        }
        echo '<a href="./' . htmlspecialchars($fileInfo->getFilename(), ENT_QUOTES) . '">' . $fileInfo->getFilename() . '</a><br />' . PHP_EOL;
    }
        return;
    }
}

require __DIR__ . '/../public/index.php';
```

**Comment by julienfalque** [comment] 2017-11-07 07:59
Hi, thanks for the report. This is a duplicate of #3202, it should be fixed with #3208 which will be released soon.

**Closed by julienfalque** 2017-11-07 07:59 UTC
