### ISSUE TITLE
phpdoc_to_comment false positive

### ISSUE THREAD

**Issue by fluffycondor** [FriendsOfPHP/PHP-CS-Fixer#5119] opened 2020-08-20 10:19 UTC
## Bug report

Rule phpdoc_to_comment turns phpdoc @var on return statement to two-slash comment.

PHP 7.3.21, PHP CS Fixer 2.16.4 Yellow Bird

The command:
`/usr/local/bin/php-cs-fixer fix --verbose --diff --config "$PHP_CS_CONFIG" $CHANGED_FILES;`

Config:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . DIRECTORY_SEPARATOR . 'src')
    ->notPath('Kernel.php')
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        '@Symfony' => true,
        '@PhpCsFixer' => true,
        'declare_strict_types' => true,
        'concat_space' => ['spacing' => 'one'],
        'ordered_class_elements' => false,
        'phpdoc_add_missing_param_annotation' => false,
        'binary_operator_spaces' => [
            'default' => 'single_space',
            'operators' => [
                '=>' => null,
                '=' => null,
            ],
        ],
    ])
    ->setFinder($finder)
;
```
### Code snippet that reproduces the problem
```php
public function findDeleted($id, $lockMode = null, $lockVersion = null): ?Project
{
   /** @var null|Project */ <-- this comment is required to specify concrete object from parent::find,
                           otherwise PHPStan throws an error "should return Project|null but returns object|null"
  return parent::find($id, $lockMode, $lockVersion);
}
```
PHP-CS-Fixer turns it to
```php
public function findDeleted($id, $lockMode = null, $lockVersion = null): ?Project
{
   // @var null|Project
  return parent::find($id, $lockMode, $lockVersion);
}
```

If I try to avoid it like this:
```php
public function findDeleted($id, $lockMode = null, $lockVersion = null): ?Project
{
   /** @var null|Project */
   $project = parent::find($id, $lockMode, $lockVersion);

   return $project;
}
```

The rule return_assignment turns it to
```php
public function findDeleted($id, $lockMode = null, $lockVersion = null): ?Project
{
   /** @var null|Project */
  return parent::find($id, $lockMode, $lockVersion);
}
```

And on the next run the rule phpdoc_to_comment is coming again:
```php
public function findDeleted($id, $lockMode = null, $lockVersion = null): ?Project
{
   // @var null|Project
  return parent::find($id, $lockMode, $lockVersion);
}
```
And this kind of comment can't be inspected by PHPStan.

**Comment by julienfalque** [comment] 2020-08-20 12:01
Duplicate of #5109/#4649.

**Closed by julienfalque** 2020-08-20 12:01 UTC
Labels: kind/bug
