### ISSUE TITLE
The v2 download link is not up to date

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfPHP/PHP-CS-Fixer#3157] opened 2017-10-16 19:04 UTC
```
$ wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
$ php php-cs-fixer-v2.phar --version
Cannot load Xdebug - it was already loaded
PHP CS Fixer 2.7.0 Sandy Pool by Fabien Potencier and Dariusz Ruminski (e4e93a1)
```

Should be `2.7.1` AFAIK.

**Comment by Soullivaneuh** [comment] 2017-10-30 18:07
@SpacePossum this should be also tagged as a bug IMHO.

**Comment by SpacePossum** [comment] 2017-10-30 18:48
While I agree this is a erroneous state I feel we should not tag it as a bug.
It is a procedure / hosting / eco climate failure, however it is not a bug within the code base of the project.
The later is a condition to tag something a bug here.

The difference is important to everyone here as it distinguish between artifacts;
- that can be resolved by anyone up the the task, no matter their role
- and/or effect all users (including those using the project as composer requirement)

and:

- (`phar`) releases and/or their hosting issues which _typically_ require a role that grants enough to resolve such issue

In the end the result in the same;
the labeling is mostly for maintainers and members to align the work to be done, so no worries, your report is validated and noted :)

**Comment by Soullivaneuh** [comment] 2017-10-31 07:33
> the labeling is mostly for maintainers and members to align the work to be done, so no worries, your report is validated and noted :)

Well, this is also why I was thinking to a more critical label than just release, but it's simply a suggestion. :wink: 

Thanks.

**Comment by keradus** [comment] 2017-10-31 08:28
Updated.

**Closed by keradus** 2017-10-31 08:28 UTC
Labels: releases
