### ISSUE TITLE
PHPCSfixer not working on Travis PHP7.2

### ISSUE THREAD

**Issue by mazentouati** [FriendsOfPHP/PHP-CS-Fixer#4284] opened 2019-01-28 00:36 UTC
Hey there,
For some reasons php cs fixer not working on Travis.org using PHP7.2, though it works locally with PHP7.2.2 installed.

It throws the following error
```
PHP Fatal error:  Class 'null' not found in /home/travis/build/mazentouati/Validation/vendor/symfony/options-resolver/OptionsResolver.php on line 1004
Fatal error: Class 'null' not found in /home/travis/build/mazentouati/Validation/vendor/symfony/options-resolver/OptionsResolver.php on line 1004
PHP Fatal error:  Class 'null' not found in /home/travis/build/mazentouati/Validation/vendor/symfony/options-resolver/OptionsResolver.php on line 1004
PHP Stack trace:
PHP   1. {main}() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:0
PHP   2. PhpCsFixer\Console\Application->__construct() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:74
PHP   3. PhpCsFixer\Console\Command\DescribeCommand->__construct() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:56
PHP   4. PhpCsFixer\FixerFactory->registerBuiltInFixers() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/Console/Command/DescribeCommand.php:77
PHP   5. PhpCsFixer\Fixer\DoctrineAnnotation\DoctrineAnnotationSpacesFixer->__construct() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/FixerFactory.php:107
PHP   6. PhpCsFixer\Fixer\DoctrineAnnotation\DoctrineAnnotationSpacesFixer->configure() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php:57
PHP   7. PhpCsFixer\Fixer\DoctrineAnnotation\DoctrineAnnotationSpacesFixer->configure() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/Fixer/DoctrineAnnotation/DoctrineAnnotationSpacesFixer.php:48
PHP   8. PhpCsFixer\FixerConfiguration\FixerConfigurationResolver->resolve() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php:156
PHP   9. Symfony\Component\OptionsResolver\OptionsResolver->resolve() /home/travis/build/mazentouati/Validation/vendor/friendsofphp/php-cs-fixer/src/FixerConfiguration/FixerConfigurationResolver.php:106
PHP  10. Symfony\Component\OptionsResolver\OptionsResolver->offsetGet() /home/travis/build/mazentouati/Validation/vendor/symfony/options-resolver/OptionsResolver.php:772
PHP  11. Symfony\Component\OptionsResolver\OptionsResolver->verifyTypes() /home/travis/build/mazentouati/Validation/vendor/symfony/options-resolver/OptionsResolver.php:877
Fatal error: Class 'null' not found in /home/travis/build/mazentouati/Validation/vendor/symfony/options-resolver/OptionsResolver.php on line 1004
```

the full information about the job
https://travis-ci.org/mazentouati/Validation/jobs/485183932

#### The PHP version you are using (`$ php -v`):
=>7.2

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> v2.14.0

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer --diff --dry-run --verbose fix

### configuration
```PHP
<?php
return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@PHP71Migration:risky' => true,
        'phpdoc_align' => false,
        'phpdoc_summary' => false,
        'mb_str_functions' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_imports' => true,
        'phpdoc_order' => true,
        'array_syntax' => ['syntax' => 'short'],
        'no_short_echo_tag' => true,
        'php_unit_construct' => true,
        'php_unit_dedicate_assert' => true,
        'php_unit_expectation' => true,
        'php_unit_mock' => true,
        'php_unit_namespaced' => true,
        'php_unit_ordered_covers' => true,
        'php_unit_set_up_tear_down_visibility' => true,
        'php_unit_test_annotation' => [
            'style' => 'annotation',
        ],
        'php_unit_test_case_static_method_calls' => ['call_type' => 'self'],
        'php_unit_test_class_requires_covers' => true,
    ])
    ->setCacheFile(
        sprintf(
            '%s/.php_cs.cache',
            getenv('TRAVIS') ? getenv('HOME').'/.php-cs-fixer' : __DIR__
        )
    )
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(['library', 'tests'])
            ->name('*.php')
            ->name('*.phpt')
    );
```

I'm not sure whether the source of issue is the PHP version, php-cs-fixer or OptionsResolver. But I posted here as php-cs-fixer is the one that triggered the error.

**Comment by kubawerlos** [comment] 2019-01-28 07:18
Seems like duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4256

**Comment by keradus** [comment] 2019-01-28 08:14
indeed

**Closed by keradus** 2019-01-28 08:14 UTC
