### ISSUE TITLE
Fixer takes almost a WHOLE DAY to finish on ALREADY FIXED code

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5279] opened 2020-11-19 10:05 UTC
Version: latest stable 2.16

Code:

https://github.com/mvorisek/TCPDF/tree/psr12_cs

Command:

```
vendor\friendsofphp\php-cs-fixer\php-cs-fixer fix -v
```

Fixer output:

```
Fixed all files in 74065.269 seconds, 522.000 MB memory used
```

I think it is related with https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4656 even the main issue there is with an unfixed code.

This issue should considered as fix asap bug as performance like this makes CS Fixer almost impossible to run with CI not mentioning the usability on the programmer side.

**Comment by mvorisek** [comment] 2020-11-24 10:59
@SpacePossum `array_indentation` rule is very slow even on fixed code, is there something that can be easily improved?

**Comment by keradus** [comment] 2020-11-28 21:37
Observation (not root cause of the problem)
TokenizerLinter looks way slower than ProcessLinter on big files
```
ker@dus:~/github/PHP-CS-Fixer λ php php-cs-fixer fix --rules=array_indentation debug/cid0cs.php 
Loaded config default from "/home/d.ruminski/github/PHP-CS-Fixer/.php_cs.dist".
Paths from configuration file have been overridden by paths provided as command arguments.
string(41) "PhpCsFixer\Linter\ProcessLinter::lintFile"
string(18) "ProcessLinter time"
float(0.0019989013671875)
```

```
ker@dus:~/github/PHP-CS-Fixer λ php php-cs-fixer fix --rules=array_indentation debug/cid0cs.php 
Loaded config default from "/home/d.ruminski/github/PHP-CS-Fixer/.php_cs.dist".
Paths from configuration file have been overridden by paths provided as command arguments.
string(43) "PhpCsFixer\Linter\TokenizerLinter::lintFile"
string(20) "TokenizerLinter time"
float(6.3825531005859)
```

**Comment by keradus** [comment] 2020-11-28 21:44
@mvorisek , the example file you gave has 698517 tokens... :sob:

**Comment by mvorisek** [comment] 2020-11-28 22:50
> 
> 
> @mvorisek , the example file you gave has 698517 tokens... 😭

that itself should be fine, but the code complexity is probably too bad

**Comment by keradus** [comment] 2020-11-28 23:03
@mvorisek , for now, I would suggest you to exclude the file from fixing in your config file.

1.7 MB file (or 700k tokens) is very huge PHP file, out of regular human-written files. Isn't it autogerenated? Do you expect someone to modify this file manually, or do a review of it ?

I fully agree that it would be great if the tool would be able to process the file in a reasonable time. I spent 2 hours on this topic and unfortunately cannot bring any valuable improvement in that time. If you want, please investigate the topic on your side and we will gladly accept a PR.

As 2MB file of code is our of regular usage, I would call it out of scope for core team to take care of this request - we have limited time capacity and we are in need to focus on topics that will impact majority of community, like PHP 8 support.

For that, I'm closing the issue on GitHub. Feel free everyone to continue the discussion on the topic, and I'm very happy to accept PR for it.
I hope you will understand my decision.

**Closed by keradus** 2020-11-28 23:03 UTC
Labels: kind/bug

**Comment by mvorisek** [comment] 2020-11-28 23:09
Please reopen. There are much more files that big, the `tcpdf.php` itself is about 1MB too. I think this should be fixed as for smaller files the tital time is lower, but probably still slow enough with a lot of space to improve due non linear complexity.

**Comment by SpacePossum** [comment] 2020-12-04 09:06
Besides the tokenizer I think the alignment fixers issues are the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3996 
Until someone figured out a way to fix this I would suggest disabling the alignment rules or skip the files (also based on the findings of Keradus).

**Comment by mvorisek** [comment] 2020-12-04 10:24
@SpacePossum @keradus reading the discussion, comment https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3996#issuecomment-456733931 tells that https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4250 might be a fix for this. Can that PR be merged soon?

**Comment by keradus** [comment] 2020-12-08 14:35
#4250 is not actively working on, we are focusing on PHP v8 support.
also, #4250 will help only when the fixing itself is slow due to huge amount of tokens to be inserted. in concern you spotted, the fixer is slow for already fixed file, due to amount of arrays and distance between opening and ending of them measured in thousands of tokens

**Comment by SpacePossum** [comment] 2020-12-08 15:48
The issue with the alignment fixers is that these insert placeholder tokens even if there is nothing to fix, as such these are always slow as on big token sets. I agree on the focus though, we cannot do PHP8 and PSR12 while also looking into this.
