### ISSUE TITLE
Anonymous classes' constructor params are forced on one line

### ISSUE THREAD

**Issue by SvenRtbg** [FriendsOfPHP/PHP-CS-Fixer#4628] opened 2019-11-06 16:55 UTC
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
PHP 7.2.21-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:53:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.21-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.16.0 Yellow Bird by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix --diff --dry-run --rules=class_definition .

#### The configuration file you are using, if any:
none

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
$class = new class(
    $foo,
    $bar,
    $baz
) extends \Psr\Log\AbstractLogger implements \Psr\Log\LoggerInterface {
    public function __construct($foo, $bar, $baz)
    {
    }

    public function log($level, $message, array $context = array())
    {
        echo $message;
    }
};
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
$class = new class($foo, $bar, $baz) extends \Psr\Log\AbstractLogger implements \Psr\Log\LoggerInterface {
```
The multiline constructor parameters are forced onto one line. This example uses short var names, using longer var names and outer class properties (like injecting mock objects in tests) makes this more obvious that creating a very long single line is not a good idea.

 * with the changes you expected instead:
PSR12 states in section 8: Anonymous Classes MUST follow the same guidelines and principles as closures in the above section.

Section 7 has this example
```php
$longArgs_longVars = function (
    $longArgument,
    $longerArgument,
    $muchLongerArgument
) use (
    $longVar1,
    $longerVar2,
    $muchLongerVar3
) {
   // body
};
```

I'd expect that using multiline argument lists like in the example code is completely correct, no changes should take place at all.

**Comment by SvenRtbg** [comment] 2019-11-06 16:56
Looks like an open issue for PSR12 support #4502

**Comment by SpacePossum** [comment] 2019-12-18 12:33
Hi and thanks for reporting,

The fixer does this as part of PSR2:

> 4.1 The extends and implements keywords MUST be declared on the same line as the class name.

However anonymous classes have no names, so one could reason that the fixer is to strict here.

Your case can be indeed be fixed through PSR12 as well though  :+1:

**Comment by SpacePossum** [comment] 2021-09-23 05:57
closing as duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4289

**Closed by SpacePossum** 2021-09-23 05:57 UTC
Labels: kind/feature request, topic/PSR-12
