### ISSUE TITLE
Atom | Atom Beautify | PHP Is Not Formatting Even Without Any Error

### ISSUE THREAD

**Issue by EXEIdeas** [FriendsOfPHP/PHP-CS-Fixer#6263] opened 2022-02-04 05:18 UTC
I am using Atom 1.58.0 x64 with Atom Beautify 0.33.4. I am able to Beautify other Languages but not PHP. I followed all over internet guides and are now of that state where I am not getting any error but also not formatting my PHP file too. Here is my settings and updates.

![image](https://user-images.githubusercontent.com/3936751/152475792-6cb686ef-697d-4a14-8c6f-8cb8bfd4d307.png)

Also my PATH variable is updated too.

![image](https://user-images.githubusercontent.com/3936751/152476071-248c4549-8b6f-4809-a192-0baf8af7b585.png)

But not able to beautify my PHP file even loader is working in ATOM.

![image](https://user-images.githubusercontent.com/3936751/152476184-b2853557-1054-42f2-9e73-4c447f4d01e8.png)

What to Do?

**Comment by keradus** [comment] 2022-02-04 09:51
We cannot support you on request about your IDE (or any other IDE).

Can you reproduce the issue using PHP CS Fixer CLI? then, raise the report using full template, so we can analyse and reproduce: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.md
If you cannot reproduce using PHP CS Fixer directly, report issue to IDE or plugin you are using

**Comment by SpacePossum** [comment] 2022-02-17 12:13
Closing as I see no action we can take here without additional information, will reopen if the information is provided to continue on this.

**Closed by SpacePossum** 2022-02-17 12:13 UTC
Labels: kind/question, status/input required
