### ISSUE TITLE
binary_operator_spaces is running on HTML code (in a PHP template file)

### ISSUE THREAD

**Issue by jaydiablo** [FriendsOfPHP/PHP-CS-Fixer#6211] opened 2021-12-29 20:55 UTC
## Bug report

This appears to only happen in version 3.4.0+ (when testing with 3.3.2, the behavior isn't there). We run php-cs-fixer against `phtml` files, which are typically HTML templates with PHP code in them (mixture of short tags for echoing (`<?=`) and "long" tags for control flow and such). I was just testing 3.4.0 against this code base, and just one template resulted in some odd formatting.  I think that something is triggering the `binary_operator_spaces` fixer to think it's operating on PHP code, but it's actually in the HTML.

### Code snippet that reproduces the problem

```html
<a
    href="<?= $someVariable; ?>"
    id="details-row-link-<?= $someOtherVariable; ?>-<?= $andAnother; ?>"
    data-id="<?= $aVariable; ?>-<?= $oneMore; ?>"
>
    Test text
</a>
```

This is a simplified version of the actual code, but I was able to reproduce the error with this snippet.

After running PHPCsFixer 3.4.0 against this file, it formats it as so:

```html
<a
    href="<?= $someVariable; ?>"
    id="details-row-link-<?= $someOtherVariable; ?> - <?= $andAnother; ?>"
    data-id="<?= $aVariable; ?>                     - <?= $oneMore; ?>"
>
    Test text
</a>
```

According to the summary output, it seems that the only fixer applied is `binary_operator_spaces`. As you can see it's adding whitespace around the dashes in the html attributes (not php code) to make them align with the previous line. That said, if I remove one of the lines, it still adds a single whitespace character on either side of the dash:

```html
<a
    href="<?= $someVariable; ?>"
    id="details-row-link-<?= $someOtherVariable; ?> - <?= $andAnother; ?>"
>
    Test text
</a>
```

Here's the `binary_operator_spaces` config setting for this particular app:

```php
'binary_operator_spaces' => [
            'default'   => 'align_single_space_minimal',
            'operators' => ['||' => null, '&&' => null, '==' => null, '===' => null, '+' => null],
        ],
```

Ran with PHP 8.0.13.

**Comment by akrfjmt** [comment] 2022-08-25 04:27
This issue is identical to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6443 and seems to have been fixed in [pr133 ](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6476) .

**Comment by julienfalque** [comment] 2022-08-25 19:49
I confirm the issue is fixed on master.

**Closed by julienfalque** 2022-08-25 19:49 UTC
Labels: kind/bug
