### ISSUE TITLE
php_unit_strict should take argument count into consideration

### ISSUE THREAD

**Issue by twifty** [FriendsOfPHP/PHP-CS-Fixer#2917] opened 2017-07-14 21:31 UTC
cs-fixer: 2.3.1
php: 7.1

Just ran into an issue where tests were failing after running the fixer. Turns out `php_unit_strict` was converting `assertEquals` into `assertSame`. The problem is that the test was comparing array which might not have the same order, so the `$canonicalize` parameter was being used.

```php
$this->assertEquals(['foo', 'bar'], ['bar', 'foo'], 'not equal', 0, 1, true);
```

I think `php_unit_strict` really should count the number of arguments passed to the method before deciding if it should "fix" the code. Anything more than 3 arguments should be considered an explicit use of `assertEquals`.

**Comment by keradus** [comment] 2017-07-15 05:56
:-1: 
fixer is enforcing on you good practices. canonicalize is violating that.

**Comment by SpacePossum** [comment] 2017-07-17 05:20
While the fixer could be less `risky` when taking the argument count into consideration I'm not in favor as well. 
This is because this fixer is designed to make `equal`-calls strict. As such when used the behavior is expected and issues caused by its usage are to be fixed by the user. As the user _wants_ to do better strict testing this is good thing.
If you want to do more easy strict testing of `float`s within a range I suggest using a type check (`assertInternalType`) with a range check like  https://github.com/GeckoPackages/GeckoPHPUnit `assertNumberInRange` / `assertNumberOnRange` (disclaimer I'm the author of that package)

**Closed by SpacePossum** 2017-07-17 05:20 UTC
