### ISSUE TITLE
Invalid format for typed array properties for PHP 7.4

### ISSUE THREAD

**Issue by ddlzz** [FriendsOfPHP/PHP-CS-Fixer#4694] opened 2019-12-10 16:20 UTC
Hi! there is a problem with the `class_attributes_separation` rule in array typed properties. The following report will provide more info: 

#### The PHP version you are using (`$ php -v`):
`PHP 7.4.0 (cli) (built: Nov 28 2019 20:31:53) ( NTS )`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`php /app/vendor/bin/php-cs-fixer -v --config=/app/.php_cs.dist fix /app/src/*`

#### The configuration file you are using, if any:
```php
<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude(['assets', 'bin', 'public', 'var', 'vendor']);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@DoctrineAnnotation' => true,
        '@PHP71Migration' => true,
        '@PHP71Migration:risky' => true,
        'array_syntax' => [
            'syntax' => 'short',
        ],
        'braces' => [
            'allow_single_line_closure' => true,
        ],
        'no_superfluous_phpdoc_tags' => false,
        'modernize_types_casting' => true,
        'no_extra_consecutive_blank_lines' => [
            'break',
            'continue',
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'return',
            'square_brace_block',
            'throw',
            'use',
        ],
        'no_useless_else' => true,
        'no_useless_return' => true,
        'native_function_invocation' => true,
        'ordered_imports' => true,
        'phpdoc_order' => true,
        'psr4' => true,
        'semicolon_after_instruction' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'ternary_to_null_coalescing' => true,
        'ordered_class_elements' => true,
        'php_unit_strict' => false,
        'phpdoc_add_missing_param_annotation' => true,
        'doctrine_annotation_indentation' => true,
        'class_attributes_separation' => ['elements' => ['const', 'method', 'property']],
    ])
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    private array $data;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    private array

 $data;
```

 * with the changes you expected instead:
```php
    private array $data;
```

**Comment by julienfalque** [comment] 2019-12-10 17:43
Closing as duplicate of #4680. This is fixed by #4682 (not released yet).

**Closed by julienfalque** 2019-12-10 17:43 UTC
