### ISSUE TITLE
no_trailing_comma_in_list_call broken

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1772] opened 2016-02-12 22:19 UTC
When run on https://github.com/GrahamForks/CCU-Plus/blob/master/app/Ccu/EcourseLite/Attachment.php, it crashes.

**Comment by keradus** [comment] 2016-02-13 11:57
Could you send a fix?

**Comment by gharlan** [comment] 2016-02-13 14:03
The problem is the `const LIST`, which is possible since php 7.
We could fix this by using the new `TOKEN_PARSE` flag of `token_get_all`:
http://php.net/manual/en/function.token-get-all.php
Then the "list" word would be a `T_STRING` instead of `T_LIST`.

But after enabling I get many other failing test cases.

**Comment by gharlan** [comment] 2016-02-13 14:07
By the way: it seems that `TOKEN_PARSE` does something similar than the linter. Maybe we can use this parameter in php 7 **instead** of linting?

**Comment by keradus** [comment] 2016-06-04 19:35
Closing in favour of #1959, which is combining multiple threads of same issue (#1772, #1837, #1945).
Thank you @gharlan, @GrahamCampbell for discussion so far! Please, move forward discussion (if any) to new thread.

**Closed by keradus** 2016-06-04 19:35 UTC
