### ISSUE TITLE
Fixing annotation block

### ISSUE THREAD

**Issue by TheLuckyOne** [FriendsOfPHP/PHP-CS-Fixer#2451] opened 2017-01-06 16:20 UTC
Hi all

$ php -v
PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )

$ /usr/local/bin/php-cs-fixer -V
PHP CS Fixer 2.0.0 by Fabien Potencier and Dariusz Ruminski

The command you use to run the fixer (and the configuration file you are using if any).
/usr/local/bin/php-cs-fixer fix test.php
```
You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
Loaded config default.

Fixed all files in 0.026 seconds, 6.000 MB memory used
```

A minimal sample of valid PHP code that is not fixed correctly (if applicable).
```
<?php
/**
   * AdvBanners.
    */
class AdvBanners
{
    /**
         * @var int
         */
    private $id;
}
```
The fixed version of that code after you run the fixer and the version you expected.
After run:
```
<?php
/**
   * AdvBanners.
    */
class AdvBanners
{
    /**
         * @var int
         */
    private $id;
}
```

Expected:
```
<?php
/**
 * AdvBanners.
 */
class AdvBanners
{
    /**
     * @var int
     */
    private $id;
}
```

Is it a bug or?

**Comment by keradus** [comment] 2017-01-06 17:09
it is not a bug. bug is when the code was modified in wrong way.

here, you miss a feature.

**Comment by keradus** [comment] 2017-01-06 17:09
do you want to work on it and send a PR introducing new feature ?

**Comment by TheLuckyOne** [comment] 2017-01-09 12:03
I'll try :-)

**Comment by SpacePossum** [comment] 2017-07-06 13:40
this is fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2857 and will be part of the next minor release

**Closed by SpacePossum** 2017-07-06 13:40 UTC
Labels: feature request
