### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by dmamontov** [FriendsOfPHP/PHP-CS-Fixer#4270] opened 2019-01-17 13:00 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> does not start

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer -V

PHP Fatal error:  Class 'bool' not found in phar:///usr/local/bin/php-cs-fixer/vendor/symfony/options-resolver/OptionsResolver.php on line 1063
PHP Fatal error:  Class 'bool' not found in phar:///usr/local/bin/php-cs-fixer/vendor/symfony/options-resolver/OptionsResolver.php on line 1063
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/php-cs-fixer:0
PHP   2. PhpCsFixer\Console\Application->__construct() /usr/local/bin/php-cs-fixer:74
PHP   3. PhpCsFixer\Console\Command\DescribeCommand->__construct() phar:///usr/local/bin/php-cs-fixer/src/Console/Application.php:56
PHP   4. PhpCsFixer\FixerFactory->registerBuiltInFixers() phar:///usr/local/bin/php-cs-fixer/src/Console/Command/DescribeCommand.php:77
PHP   5. PhpCsFixer\Fixer\ControlStructure\YodaStyleFixer->__construct() phar:///usr/local/bin/php-cs-fixer/src/FixerFactory.php:107
PHP   6. PhpCsFixer\Fixer\ControlStructure\YodaStyleFixer->configure() phar:///usr/local/bin/php-cs-fixer/src/AbstractFixer.php:57
PHP   7. PhpCsFixer\Fixer\ControlStructure\YodaStyleFixer->configure() phar:///usr/local/bin/php-cs-fixer/src/Fixer/ControlStructure/YodaStyleFixer.php:53
PHP   8. PhpCsFixer\FixerConfiguration\FixerConfigurationResolver->resolve() phar:///usr/local/bin/php-cs-fixer/src/AbstractFixer.php:156
PHP   9. Symfony\Component\OptionsResolver\OptionsResolver->resolve() phar:///usr/local/bin/php-cs-fixer/src/FixerConfiguration/FixerConfigurationResolver.php:106
PHP  10. Symfony\Component\OptionsResolver\OptionsResolver->offsetGet() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/options-resolver/OptionsResolver.php:669
PHP  11. Symfony\Component\OptionsResolver\OptionsResolver->verifyTypes() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/options-resolver/OptionsResolver.php:743
PHP  12. Symfony\Component\OptionsResolver\OptionsResolver::isValueValidType() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/options-resolver/OptionsResolver.php:843

**Comment by keradus** [comment] 2019-01-17 13:01
hi @dmamontov , thanks for this report.
can you please provide info how have you installed PHP CS Fixer ?

**Comment by dmamontov** [comment] 2019-01-17 13:03
All of the documentation
$ wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
$ sudo chmod a+x php-cs-fixer
$ sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

**Comment by keradus** [comment] 2019-01-17 13:04
thanks,
i will investigate

**Comment by dmamontov** [comment] 2019-01-17 13:06
And now put on CentOS and everything is in order.
This error occurs in Fedora 29.

**Comment by keradus** [comment] 2019-01-17 13:11
Yeah, nothing to do on our side, i'm afraid.
looks like a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4256 , which is bug of uopz, nothing to do on our side.

as a workaround, you can run clean php as docker image

Closing as duplicate.

**Closed by keradus** 2019-01-17 13:11 UTC
