### ISSUE TITLE
Single line array to multiple line array fixer

### ISSUE THREAD

**Issue by surenderpratap** [FriendsOfPHP/PHP-CS-Fixer#4485] opened 2019-08-01 12:50 UTC
//From
$array = array("foo" => "bar","bar" => "foo");

//To
$array = array(
    "foo" => "bar",
    "bar" => "foo",
);

**Comment by SpacePossum** [comment] 2019-10-09 07:03
Hi and thanks for the question,

Currentlky we have no rule in place to do this, would be nice to have though :)

**Comment by taylankasap** [comment] 2020-02-11 14:44
Duplicate of #1217

**Comment by SpacePossum** [comment] 2020-02-11 14:48
thanks! closing as duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1217

**Closed by SpacePossum** 2020-02-11 14:48 UTC
Labels: kind/feature request
