### ISSUE TITLE
switch...case does not write break when switch's } indent is incorrect

### ISSUE THREAD

**Issue by Yurunsoft** [FriendsOfPHP/PHP-CS-Fixer#6533] opened 2022-08-03 09:10 UTC
## Bug report

PHP CS Fixer 3.9.5

### Code snippet that reproduces the problem

**before:**

```php
<?php

declare(strict_types=1);

switch (1)
{
    case 1:
        break;
    case 2:
}

```

**after:**

```php
<?php

declare(strict_types=1);

switch (1)
{
    case 1:
        break;
    case 2:
    }
```

**Comment by julienfalque** [comment] 2022-08-07 13:49
Duplicate of #6523.

**Closed by julienfalque** 2022-08-07 13:49 UTC
Labels: kind/bug
