### ISSUE TITLE
.phar file missing from current release

### ISSUE THREAD

**Issue by drazisil** [FriendsOfPHP/PHP-CS-Fixer#2140] opened 2016-08-16 14:45 UTC
https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.11.7/php-cs-fixer.phar is a 404 when trying to install using the commands in README.

I was not able to locate php-cs-fixer.phar in the source tree either.

**Comment by GrahamCampbell** [comment] 2016-08-16 14:46
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2134.

**Closed** 2016-08-16 14:47 UTC

**Comment by keradus** [comment] 2016-08-16 18:52
@drazisil 
Travis failed to create phar file due to buggy build of box, which we are using to build phar file ( see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2141)
I have created phar file locally and updated release on github Releases.
