### ISSUE TITLE
PhpCsFixer\Fixer\ClassNotation\FinalClassFixer adds final to Doctrine Entities when running in ECS PHAR archive

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#4887] opened 2020-03-17 08:35 UTC
I've originally created [an issue](https://github.com/symplify/symplify/issues/1792) on ECS repository (and before that another on [Rector's repository](https://github.com/rectorphp/rector/issues/1639), I'd like to mention for context - seems like PHAR and Final + Doctrine are a bad mix), but apparently it's [not related to ECS' code](https://github.com/symplify/symplify/issues/1792#issuecomment-591036272), so I open another here hoping someone might understand why it happens and how to fix this.

This issue only happens when running this fixer through [ecs.phar](https://github.com/symplify/easy-coding-standard-prefixed/blob/master/ecs.phar) ; if I run it through ECS installed from Composer in a Docker container, it works (but it's more work to maintain).

#### The PHP version you are using (`$ php -v`):
`PHP 7.2.28-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:25) ( NTS )`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`"friendsofphp/php-cs-fixer": "^2.16"` (what is referenced in ECS' `composer.json`)

#### The command you use to run PHP CS Fixer:
`php ecs.phar check --ansi -c easy-coding-standard.yml`

#### The configuration file you are using, if any:
```yaml
# easy-coding-standard.yaml
services:
    PhpCsFixer\Fixer\ClassNotation\FinalClassFixer: ~
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

declare(strict_types=1);

namespace App\Domain\Expenses;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table
 * @ORM\Entity
 */
class ExpenseTag
{
    /**
     * @var Expense
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Expense", inversedBy="expenseTags")
     */
    private $expense;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(name="tag_id", type="integer")
     */
    private $tagId;

    public function __construct(Expense $expense, int $tagId)
    {
        $this->expense = $expense;
        $this->tagId = $tagId;
    }

    public function tagId(): int
    {
        return $this->tagId;
    }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```diff
4) src/Domain/Expenses/ExpenseTag.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
  * @ORM\Table
  * @ORM\Entity
  */
-class ExpenseTag
+final class ExpenseTag
 {
     /**
      * @var Expense

    ----------- end diff -----------

Applied checkers:

 * PhpCsFixer\Fixer\ClassNotation\FinalClassFixer
```

 * with the changes you expected instead:
None.

PS: Unfortunately, I don't have any more time to dedicate to this issue. My team has decided to not use this Fixer after all as I've already spent hours on this with no results...

**Comment by SpacePossum** [comment] 2020-04-05 10:56
Hi @gnutix and thanks for reporting!

Currently I cannot reproduce the issue on 2.15.dev nor on 2.16.dev. It could be that the ECS phar uses an outdated version of our codebase or that we had a bug causing this for which we haven't shipped the patch yet.
It could also be that ECS reconfigures the rule to a different configuration ignore set than the default we use.

I'm keeping this open for now to see if someone else spots anything or to see if this goes away after we've published the latest bug fixes.

**Comment by ddebin** [comment] 2021-05-17 11:15
Since ECS upgraded to a prefixed version by default (see https://tomasvotruba.com/blog/introducing-ecs-prefixed-and-downgraded-to-php-71/). I'm facing this problem too.

**Comment by SpacePossum** [comment] 2021-05-28 07:44
@TomasVotruba do you if this is an issue here or in symplify or somewhere else maybe?

**Comment by SpacePossum** [comment] 2021-05-28 08:01
Thanks for details Tomas!
I don't see any more action we could take in this project on the subject, so I'm closing for now. Thanks for all the input all.

**Closed by SpacePossum** 2021-05-28 08:01 UTC
Labels: status/to verify
