### ISSUE TITLE
In braces rule the 'position_after_control_structures' => 'next' doesn't work with the switch structure.

### ISSUE THREAD

**Issue by alebak** [FriendsOfPHP/PHP-CS-Fixer#5530] opened 2021-03-04 19:24 UTC
## Bug report

Hello,

I have configured my .php_cs.dist file with the rule 'position_after_control_structures' and the value 'next', but when I run php-cs-fixer it does not fix the brace in the 'switch' control structure.

   * PHP version: `PHP 7.4.10 (cli) (built: Sep  1 2020 16:52:39) ( ZTS Visual C++ 2017 x64 )`
   * PHP CS Fixer version: `PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski`
   * Command used to run PHP CS Fixer: php-cs-fixer.bat fix src\com_flexweb\site\test.php -vvv  
   Output:
```console
PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.10
Loaded config default from "D:\workspace\ximware\flexweb\.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) src\com_flexweb\site\test.php (braces)

Fixed all files in 0.314 seconds, 12.000 MB memory used
```
   * The configuration (file):
```
<?php

$finder = PhpCsFixer\Finder::create()
	->in(__DIR__ . '/src')
;

$config = new PhpCsFixer\Config();
return $config
	->setRiskyAllowed(true)
	->setIndent("\t")
	->setRules([
		'@PSR2' => true,
		'array_syntax' => ['syntax' => 'short'],
		'blank_line_before_statement' => [
			'statements' => [
				'if',
			],
		],
		'braces' => [
			'position_after_control_structures' => 'next',
			'allow_single_line_anonymous_class_with_empty_body' => true, 'allow_single_line_closure' => true,
		],
		'cast_spaces' => ['space' => 'single'],
		'concat_space' => ['spacing' => 'one'],
		'function_typehint_space' => true,
		'include' => true,
		'no_empty_statement' => true,
		'no_unused_imports' => true,
		'no_unneeded_control_parentheses' => [
			'statements' => [
				'break',
				'clone',
				'continue',
				'echo_print',
				'return',
				'switch_case',
				'yield',
				'yield_from',
			],
		],
		'no_trailing_comma_in_list_call' => true,
		'no_trailing_comma_in_singleline_array' => true,
		'phpdoc_trim' => true,
		'trailing_comma_in_multiline_array' => true,
		'whitespace_after_comma_in_array' => true,
	])
	->setFinder($finder);

```

### Code snippet that reproduces the problem
  ```php
<?php
class Test
{
	/**
	 * Method to get name
	 *
	 * @return mixed
	 *
	 * @since 1.0.0
	 */
	public function getName()
	{
		$a = 2;
		$b = 5;
		$c = 0;

		$myArray = [1, 2, 'three', 4, 5, 'six'];

		if ($a == $b){
			$c = $a + $b;
		}

		foreach ($myArray as $value){
			echo $c . $value;
		}

		switch ($a) {
			case 1:
				echo $a;
				break;
			case 2:
				echo "It's two";
				break;
			default:
				echo "I'm a message by default";
		}

		return "My name is Test";
	}
}
  ```

### Result:
  ```php
<?php
class Test
{
	/**
	 * Method to get name
	 *
	 * @return mixed
	 *
	 * @since 1.0.0
	 */
	public function getName()
	{
		$a = 2;
		$b = 5;
		$c = 0;

		$myArray = [1, 2, 'three', 4, 5, 'six'];

		if ($a == $b)
		{
			$c = $a + $b;
		}

		foreach ($myArray as $value)
		{
			echo $c . $value;
		}

		switch ($a) { // <--  Opening brace of a switch must be on the line after the definition phpcs [29, 1]
			case 1:
				echo $a;
				break;
			case 2:
				echo "It's two";
				break;
			default:
				echo "I'm a message by default";
		}

		return "My name is Test";
	}
}

  ```

**Comment by keradus** [comment] 2021-03-05 11:35
would you like to raise a fix-PR, @alebak ?

**Comment by alebak** [comment] 2021-03-05 21:09
Hi @keradus,

> would you like to raise a fix-PR, @alebak ?

Sorry, I don't have much time. It would take me time not to understand the code and fix it. :sweat:

**Comment by keradus** [comment] 2021-03-10 19:06
I guess it will take it for everyone ;)

**Comment by Gymnasiast** [comment] 2022-07-16 14:50
I noticed this problem too today. I have been taking a look in the code of PHP-CS-Fixer, but didn’t manage to find a fix, being too unfamiliar with the codebase. Hope the devs can find the time to fix (I run open source projects myself, so I know I have to be patient). in the meantime I reverted to v2.19 for the time being.

**Comment by julienfalque** [comment] 2022-07-19 11:10
Which version did you try? I cannot reproduce the issue on v3.9.4.

**Comment by SpacePossum** [comment] 2022-08-27 07:00
Tried on latest and the `switch {` gets now moved to the next line, suggest closing this issue.

**Closed** 2022-08-28 17:14 UTC
Labels: kind/bug, braces related
