### ISSUE TITLE
`no_unused_imports` mistakenly removing imports that are used in union return types for abstract and interface method signatures

### ISSUE THREAD

**Issue by ChrisExP** [FriendsOfPHP/PHP-CS-Fixer#5944] opened 2021-09-02 15:18 UTC
## Bug report

**PHP version**: 8.0.5

**PHP CS Fixer version**: 3.1.0

**The command used**: `php-cs-fixer fix --rules=no_unused_imports -vvv --dry-run -- test.php`

### Code snippet that reproduces the problem

```php
<?php
// test.php

class A
{
}

class B
{
}

namespace AbstractTest;

use A;
use B; // This is incorrectly removed by cs-fixer

abstract class Foo
{
    abstract public function bar(): A|B;
}

namespace InterfaceTest;

use A;
use B; // This is incorrectly removed by cs-fixer

interface Foo
{
    public function bar(): A|B;
}
```

### The output

```
PHP CS Fixer 3.1.0 River by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.10
F       1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) test.php (no_unused_imports)

Checked all files in 0.109 seconds, 20.000 MB memory used
```
The last class in the union declaration is not recognized and so it removes the `use B;` import thinking it is not used.

### Expected output
No errors should be recorded as both imported classes are used.

From what I was able to figure out, the result of `$analyzer->isConstantInvocation($index)` returns `true` in `NoUnusedImportFixer:150` mistaking the token as a constant instead of a class.  
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Import/NoUnusedImportsFixer.php#L151

This only happens for method signatures rather than real methods, because the `isConstantInvocation` method returns `false` if the next token is `{` which would be true for standard method definitions.  
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Tokenizer/TokensAnalyzer.php#L307-L312

It wouldn't work to check for `;` as well as `{` because that could be true for constants.

It may work to check the if the previous token is one of `T_TYPE_ALTERNATION` (`|`) as I believe that would only be true for union types. However it's a bit beyond me at the moment. I don't know the code well enough to feel comfortable making a pull request for this.

**Comment by julienfalque** [comment] 2021-09-02 15:33
This looks like a duplicate of #5935, which should have been fixed by #5942.

**Closed by julienfalque** 2021-09-02 15:33 UTC
Labels: kind/bug
