### ISSUE TITLE
Indention fixing - When removing a useless else, lines are not unindented properly

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/PHP-CS-Fixer#2694] opened 2017-04-13 14:15 UTC
When the code inside the `else` spans multiple lines, the lines are not unindented properly.

Current diff:

```diff
-            } else {
-                return $this->redirectToRoute('space_challenge_manager_teams_pr
ize_sequence_details', array(
+            }
+
+            return $this->redirectToRoute('space_challenge_manager_teams_prize_sequence_details', array(
                     'space' => $space->getId(),
                     'team' => $team->getId(),
                     'level' => $level->getId(),
                     'sequence' => $prizeData['sequence']->getId(),
                 ));
-            }
```

Expected diff:

```diff
-            } else {
-                return $this->redirectToRoute('space_challenge_manager_teams_pr
ize_sequence_details', array(
-                    'space' => $space->getId(),
-                    'team' => $team->getId(),
-                    'level' => $level->getId(),
-                    'sequence' => $prizeData['sequence']->getId(),
-                ));
             }
+
+            return $this->redirectToRoute('space_challenge_manager_teams_prize_sequence_details', array(
+                'space' => $space->getId(),
+                'team' => $team->getId(),
+                'level' => $level->getId(),
+                'sequence' => $prizeData['sequence']->getId(),
+            ));
```

**Comment by SpacePossum** [comment] 2017-04-13 14:35
The `NoUselessElseFixer` doesn't do this by design as I didn't want to copy-paste the logic of the `braces` and `indentation_type` (DRY/single responsibility principle). 
However the priority (`useless else` must run before indentation fixers) is guaranteed.
So either;
- the priorities are messed up (would make the issue a bug)
- the indentation fixers are not run at all by configuration (would make the issue invalid)
- the indentation fixers do not fix the code after `NoUselessElseFixer` is done (would make the issue a FR request)

I expect the 3rd.

**Comment by stof** [comment] 2017-04-13 16:34
indentation fixers are running in my case. This is my config:

```php

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@Symfony' => true,
        '@Symfony:risky' => false,
        'strict_param' => false,
        'array_syntax' => array('syntax' => 'long'),
        'doctrine_annotation_braces' => true,
        'doctrine_annotation_indentation' => true,
        'doctrine_annotation_spaces' => true,
        'heredoc_to_nowdoc' => true,
        'no_useless_else' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
    ))
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/build/.php_cs.cache')
;
```

**Comment by stof** [comment] 2017-04-13 16:35
Note that the indentation of the `return` line itself got fixed, dunno by which fixer

**Comment by kylepwarren** [comment] 2017-05-10 13:56
Do you have any idea when this will be included in the "php-cs-fixer self-update" ? not sure if it's related to folding not working well, but suspicious.

**Comment by kylepwarren** [comment] 2017-05-11 15:36
Oh, I thought there was a solution above that I wasn't getting when I did an update. I guess it's just a work around - the post about the setting/config. i.e. not connected to a block of code about updating - wanted in update

**Comment by SpacePossum** [comment] 2017-05-11 15:53
@kylepwarren fixing the indentation of code is not fixed for all cases (although it is for a lot cases).
So, this is still a TODO, when it is done this issue will be closed and shortly after a new release will contain that fix. Lets hope someone finds the time to right the fix :)

**Comment by julienfalque** [comment] 2021-05-16 13:14
The issue is that `braces` partially fixes indentation and so does't fix indentation in multiline arrays. Indenting the code as expected here can now be done with the `array_indentation` rule, which was added in v2.11.

**Closed by julienfalque** 2021-05-16 13:14 UTC
Labels: kind/feature request
