### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1141] opened 2015-04-09 23:14 UTC
https://i.starbs.net/RRX8

The movement of that comment.

**Comment by gharlan** [comment] 2015-04-12 13:39
Please add a more verbose title. It is the third time that I look into this issue because I've forgotten what the issue is about.

And I would say the movement should not be happen.

**Comment by keradus** [comment] 2015-04-21 20:00
Which fixer is doing that? Please send a minimal test case as real code, not img.

**Comment by SpacePossum** [comment] 2015-06-24 15:56
>Please add a more verbose title. It is the third time that I look into this issue because I've forgotten what the issue is about.

2nd that :)

**Comment by keradus** [comment] 2015-07-04 22:54
```php
<?php

$a = [
    'explain' => [// FOO: bar
        1 => 2,
    ],
];
```

**Comment by keradus** [comment] 2015-07-04 22:55
```php
<?php

$a = [
    'explain' => [// FOO: bar
        1 => 2,
    ],
];
```
works great.

Sadly closing as cannot reproduce.

**Closed by keradus** 2015-07-04 22:55 UTC
