### ISSUE TITLE
Additional installation option

### ISSUE THREAD

**Issue by trsteel88** [FriendsOfPHP/PHP-CS-Fixer#6257] opened 2022-01-27 03:47 UTC
## Feature request

Currently you cannot use composer to require php-cs-fixer without tying your dependancies together.

Deployer currently uses a distribution repository to allow you to install deployer via composer: https://github.com/deployphp/distribution

Could php-cs-fixer use the same strategy, this way it could be a dev dependancies within a project and would only include the relevant php-cs-fixer.phar?

**Comment by keradus** [comment] 2022-01-31 08:02
Hey ! Thanks for your request.
We already agreed to have such solution, but not yet live.
I will close this thread as duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5998

**Closed by keradus** 2022-01-31 08:02 UTC
Labels: kind/feature request
