### ISSUE TITLE
`combine_consecutive_unsets` inserts blank line

### ISSUE THREAD

**Issue by josephzidell** [FriendsOfPHP/PHP-CS-Fixer#2949] opened 2017-07-30 03:21 UTC
When using `combine_consecutive_unsets`, it inserts a blank line after the newly combined `unset()`.

The PHP version you are using: 5.6.25
$ php -v

PHP CS Fixer version you are using: 2.4.0
$ php-cs-fixer -V

The command you use to run the fixer (and the configuration file you are using if any).
```php
php-cs-fixer fix some_file.php
```

Original Code:
```php
<?php
function f()
{
	unset($a[0]);
	unset($a[1]);
}
```

Actual result after running:
```php
<?php
function f()
{
	unset($a[0], $a[1]);

}
```

Expected result after running:
```php
<?php
function f()
{
	unset($a[0], $a[1]);
}
```

**Comment by SpacePossum** [comment] 2017-08-19 13:40
Hi,

The `combine_consecutive_unsets` fixer/rule does not remove the line by design. Its responsibility is to merge the calls and that is it.
Luckily we've other fixers/rules who do have the responsibility to remove the line. 
For example you can use;
`no_extra_consecutive_blank_lines` and make sure to add `'curly_brace_block'` to the `'tokens'` configuration; for example:  `'tokens' => ['curly_brace_block']`

**Comment by keradus** [comment] 2017-08-19 18:58
Closing due to discussion

**Closed by keradus** 2017-08-19 18:58 UTC
Labels: question
