### ISSUE TITLE
CI - Add running CI tests on Mac

### ISSUE THREAD

**Issue by aidantwoods** [FriendsOfPHP/PHP-CS-Fixer#2892] opened 2017-06-30 11:53 UTC
* Travis supports testing on Mac: https://docs.travis-ci.com/user/osx-ci-environment/

* Only two tests don't pass: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2846

* These will probably be fixed upstream: https://github.com/sebastianbergmann/phpunit/issues/2697

* No Mac support is 😢

**Comment by GrahamCampbell** [comment] 2017-06-30 11:55
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2846. :)

**Comment by aidantwoods** [comment] 2017-06-30 11:56
@GrahamCampbell This is a feature request, #2846 is closed because this feature doesn't exist 😉

**Comment by SpacePossum** [comment] 2017-06-30 12:03
:+1: for adding this to Travis

**Comment by keradus** [comment] 2017-06-30 16:48
PR is welcome @aidantwoods

**Comment by aidantwoods** [comment] 2017-06-30 17:00
> PR is welcome @aidantwoods

Brb

**Comment by keradus** [comment] 2017-07-24 20:37
closed due to merge of #2932

**Closed** 2017-07-24 20:36 UTC
Labels: enhancement

**Comment by SpacePossum** [comment] 2017-07-24 21:36
thanks @aidantwoods for raising the issue and the work done,  awesome to see we have test for Mac now :) 
and thanks @keradus for more work, awesome results :D
