### ISSUE TITLE
anonymous function return type breaks fixer

### ISSUE THREAD

**Issue by digitalkaoz** [FriendsOfPHP/PHP-CS-Fixer#1981] opened 2016-06-10 14:52 UTC
```php
        $pimple['decode_worker'] = function (Container $pimple) : Worker\Worker {
            return new Worker\DecodeWorker();
        };
```

will be fixed into 

```php
        $pimple['decode_worker'] = function (Container $pimple) : Worker\Worker {
            return new Worker\DecodeWorker();
        }
```

but only if i turn of linting...

if i remove the return type everything works fine

**Comment by GrahamCampbell** [comment] 2016-06-10 14:52
We don't support files that use return typehints.

**Comment by GrahamCampbell** [comment] 2016-06-10 14:53
See the existing issue please.

**Comment by digitalkaoz** [comment] 2016-06-10 14:54
mh it works in all other classes as expected...

**Comment by digitalkaoz** [comment] 2016-06-10 14:58
im using the 2.0 branch btw

**Comment by keradus** [comment] 2016-06-10 14:59
Thank you @digitalkaoz for your report.
We are not yet fully supporting PHP 7, but we are working on it, last one is to handle semi-reserved keywords.
Closing as duplicate of #1119. Please, feel free to help bringing PHP 7 syntax support ;)

**Closed by keradus** 2016-06-10 14:59 UTC
Labels: question
