### ISSUE TITLE
Fixer update PHP annotation (SF2 routing)

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfPHP/PHP-CS-Fixer#1155] opened 2015-04-14 12:47 UTC
Here is the diff before / after:

```diff
 /**
  * @Route("/account")
  * @Template()
+ *
  * @Method("GET")
  */
 class UserController extends Controller
```

**Comment by stof** [comment] 2015-04-14 13:25
I think this is the same root cause than #1147: The fixer treats ``@Method("GET")`` as if it was the ``@method`` phpdoc rather than a complex annotation.

**Comment by keradus** [comment] 2015-05-18 21:26
@lyrixx Please see #1204 ;)

**Comment by keradus** [comment] 2015-05-19 06:39
Closing due to merge of #1204

**Closed by keradus** 2015-05-19 06:39 UTC
Labels: bug

**Comment by lyrixx** [comment] 2015-05-19 08:13
Thanks
