### ISSUE TITLE
Implement is_countable fixer for @PHP73Migration ruleset

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#4236] opened 2019-01-04 21:29 UTC
```diff
-is_array($var) || $var instanceof Countable
+is_countable($foo)
```

**Comment by SpacePossum** [comment] 2019-01-05 13:17
:+1: 
however, I think this is a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3711 ?

**Closed** 2019-09-01 14:36 UTC
Labels: duplicate
