### ISSUE TITLE
class_attributes_separation fixer incorrectly adds whitespace/newline after typed array property

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#4886] opened 2020-03-17 08:20 UTC
#### PHP Version
```
$ php -v     
PHP 7.4.3 (cli) (built: Feb 18 2020 11:53:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
#### PHP-CS-Fixer Version
```
$ ./tools/php-cs-fixer -V
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski (c8afb59)
```
#### Reproducing Example: Output
```
$ ./tools/php-cs-fixer fix --dry-run --diff src/Example.php
Loaded config default from "/home/sb/example/.php_cs.dist".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
   1) src/Example.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 {
-    private array $foo;
+    private array
+
+ $foo;
 }
 

      ----------- end diff -----------


Checked all files in 0.004 seconds, 12.000 MB memory used
```
#### Reproducing Example: Configuration
```php
<?php declare(strict_types=1);
return PhpCsFixer\Config::create()
    ->setRules(
        [
            'class_attributes_separation' => ['elements' => ['const', 'method', 'property']],
        ]
    )
    ->setFinder(
        PhpCsFixer\Finder::create()
        ->files()
        ->in(__DIR__ . '/bin')
        ->in(__DIR__ . '/src')
        ->notName('autoload.php')
    );
```
#### Reproducing Example (before)
```php
<?php declare(strict_types=1);

namespace thephpcc\office;

final class Example
{
    private array $foo;
}
```
#### Reproducing Example (after)
```php
<?php declare(strict_types=1);

namespace thephpcc\office;

final class Example
{
    private array

 $foo;
}
```

**Comment by julienfalque** [comment] 2020-03-17 10:31
Duplicate of #4680. #4682 fixed it but is not part of any release yet.

**Closed by julienfalque** 2020-03-17 10:31 UTC
