### ISSUE TITLE
PHP on one line goes down one line from the <?php tag on each run

### ISSUE THREAD

**Issue by louim** [FriendsOfPHP/PHP-CS-Fixer#1331] opened 2015-07-29 04:35 UTC
This one looks like it may be related to #1330, taking the same example:

```
<?php  class SomeClass { const VERSION = '1.1.1'; const FOO = 'bar'; }
```
When formatted, on the first run I get:

```
<?php  class SomeClass
 {
     const VERSION = '1.1.1';
     const FOO = 'bar';
 }
```

On the second run:

```
<?php

 class SomeClass
 {
     const VERSION = '1.1.1';
     const FOO = 'bar';
 }
```

On the third run: 

```
<?php


 class SomeClass
 {
     const VERSION = '1.1.1';
     const FOO = 'bar';
 }
```

And it goes away like that forever and ever.

I decided to open a separate issue, feel free to close it if #1330  is the root cause (I think it is).
I'm using the command like this: `php-cs-fixer fix Myfile.php`. 
Version is : `PHP CS Fixer version 1.10 by Fabien Potencier (8e21b4f)

**Comment by GrahamCampbell** [comment] 2015-07-29 07:59
What fixers do you have enabled?

**Comment by louim** [comment] 2015-07-29 11:21
The default set (PSR-2)

**Comment by GrahamCampbell** [comment] 2015-07-29 13:48
If you enable the fixer that removes whitespace on the symfony level, the behaviour is what you want.

**Comment by louim** [comment] 2015-07-30 14:26
@GrahamCampbell I havent't tested with the symfony fixer, but it's caused by the weird indentation (the extra space). If I remove the extra space, it acts normally.

Normally, it should work without the symfony fixer, right?

**Comment by GrahamCampbell** [comment] 2015-07-30 14:28
The symfony fixer should remove that whitespace before the other fixer gets to it.

**Comment by GrahamCampbell** [comment] 2015-07-30 14:28
Ping @keradus. Do we have an issue with fixer priorities being wrong again?

**Comment by keradus** [comment] 2015-07-30 14:30
after @louim, the problem is not that one fixer run after instead of before, but he run PSR2 level and problem exists (not want to run Symfony LEVEL)

**Comment by GrahamCampbell** [comment] 2015-07-30 14:31
I'd say that's expected though. PSR doesn't let us remove that whitespace.

**Comment by GrahamCampbell** [comment] 2015-07-30 14:32
Put it another way, the PSR-2 level fixers are in the wrong order. Nothing to do with symfony.

**Comment by keradus** [comment] 2015-09-26 20:25
Closing due to merge of #1415

**Closed by keradus** 2015-09-26 20:25 UTC
