### ISSUE TITLE
binary_operator_spaces fails to apply rule properly when multiples operators are the same line 

### ISSUE THREAD

**Issue by adrian-maurin** [FriendsOfPHP/PHP-CS-Fixer#5136] opened 2020-09-02 14:55 UTC
## Bug report
   * PHP version:                                                               
```
PHP 7.4.9 (cli) (built: Aug  5 2020 05:00:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

   * PHP CS Fixer version: 
```
PHP CS Fixer 2.16.4 Yellow Bird by Fabien Potencier and Dariusz Ruminski (1023c34)
```

   * the command used to run PHP CS Fixer
```
php-cs-fixer-v2.phar fix --dry-run --diff -v --config=$HOME/php-cs-fixer.conf -- test.php
```

   * the configuration file you used
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'binary_operator_spaces' => [
            'operators' => [
                '=>' => 'align_single_space_minimal',
                '=' => 'align_single_space_minimal',
                '||' => 'align_single_space_minimal',
            ]
        ]
    ])
    ->setFinder($finder)
;
```
-->

### Code snippet that reproduces the problem
```php
<?php
$my_var = $dummy || "foo";
$my_looooong_var = $bar || "foobar";
```
Expected output:
```php
<?php

$my_var          = $dummy || 'foo';
$my_looooong_var = $bar   || 'foobar';
```

```php
<?php

$my_var          = $dummy        || 'foo';
$my_looooong_var = $bar || 'foobar';
```

**Comment by SpacePossum** [comment] 2020-09-02 15:26
Hi and thanks for reporting!

What you see is indeed a bug that is around for a while now and hard to fix. I have to close you report though as it is a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3762 . Feel free to discuss below or in the PR!

**Closed by SpacePossum** 2020-09-02 15:26 UTC
Labels: kind/bug
