### ISSUE TITLE
2.8.1 Test Suite Failing Test on MacOS

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#3247] opened 2017-11-11 22:18 UTC
```
php -v
PHP 7.2.0RC6 (cli) (built: Nov  7 2017 19:48:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
```

```
php php-cs-fixer --version
PHP CS Fixer 2.8.1 Round Numbers by Fabien Potencier and Dariusz Ruminski
```

```
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.0RC6
Configuration: /Users/graham/GitHub/PHP-CS-Fixer/phpunit.xml.dist
```

```
1) PhpCsFixer\Tests\CiIntegrationTest::testIntegration with data set #0 ('random-changes', array('touch dir\ a/file.php', 'rm -r dir\ c', 'echo "" >> dir\ b/file\ b.php', 'echo "echo 1;" >> dir\ b/file\ b.php', 'git add .', 'git commit -m "Random changes" -q'), array('dir a/file.php', 'dir b/file b.php'), array('4', '--path-mode=intersection -- d... b.php', '--path-mode=intersection', '--', 'dir a/file.php', 'dir b/file b.php'), 'S.')
Failed asserting that 'Loaded config default from ".php_cs.dist".\n
.S\n
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error' matches PCRE pattern "/^(PHP needs to be a minimum version of PHP 5\.6\.0 and maximum version of PHP 7\.2\.\*\.
Ignoring environment requirements because `PHP_CS_FIXER_IGNORE_ENV` is set\. Execution may be unstable\.
)?(You are running PHP CS Fixer with xdebug enabled\. This has a major impact on runtime performance\.
If you need help while solving warnings, ask at https\:\/\/gitter\.im\/PHP\-CS\-Fixer, we will help you\!
)?Loaded config default from "\.php_cs\.dist"\.
S\.
Legend\: \?\-unknown, I\-invalid file syntax, file ignored, S\-Skipped, \.\-no changes, F\-fixed, E\-error$/".

/Users/graham/GitHub/PHP-CS-Fixer/tests/CiIntegrationTest.php:166
```

**Comment by kubawerlos** [comment] 2017-11-12 07:35
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3171

**Comment by keradus** [comment] 2017-11-12 11:46
Closing as duplicate. If you can, please send a fix @GrahamCampbell

**Closed by keradus** 2017-11-12 11:46 UTC
