### ISSUE TITLE
Methods in camel case

### ISSUE THREAD

**Issue by fdipilla** [FriendsOfPHP/PHP-CS-Fixer#1265] opened 2015-06-16 01:41 UTC
When I run the following code under php-cs-fixer I get no errors:
```php
<?php

namespace Vendor\Package;

class ClassName
{
    public function foo_bar_baz($arg1, &$arg2, $arg3 = [])
    {
        return true;
    }
}
```

But according to PSR-1 method names MUST be declared in camel case.
Am I getting something wrong?

Thanks :smile:

**Comment by keradus** [comment] 2015-06-16 05:48
Closing as duplicate of #1044
Please read a discussion there.

**Closed by keradus** 2015-06-16 05:48 UTC
