### ISSUE TITLE
Regression with braces fixer breaks php code.

### ISSUE THREAD

**Issue by Riimu** [FriendsOfPHP/PHP-CS-Fixer#3236] opened 2017-11-09 09:44 UTC
As I upgrade from version 2.7.1 to 2.8.0, I noticed a regression when using the `braces` fixer with `'position_after_functions_and_oop_constructs' => 'same'` option. I tried to reduce it to as simple as possible reproducible case on my OS X and got this:

TestClass.php:

```php
<?php

class TestClass {
    public static function get_all_children() {
        foreach (new DirectoryIterator('/path/') as $file) {
            if ($file->getExtension() === 'php') {
                require_once $file->getPathname();
            }
        }
        return array_filter(get_declared_classes(), function ($class) {
            return is_subclass_of($class, static::class, true);
        });
    }
}
```

.php_cs:

```php
<?php

$finder = PhpCsFixer\Finder::create()
  ->in(__DIR__);

return PhpCsFixer\Config::create()
  ->setRules([
    'braces' => ['position_after_functions_and_oop_constructs' => 'same'],
  ])
  ->setFinder($finder);
```

Resulting diff, which is **NOT VALID PHP** (notice the extra `{` added after `foreach`):

```
$ php-cs-fixer fix --dry-run --diff --using-cache=no
Loaded config default from "/Users/riikka/Source/php-cs-fixer-bug/.php_cs".
   1) php-cs-fixer-bug/TestClass.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php

 class TestClass {
     public static function get_all_children() {
-        foreach (new DirectoryIterator('/path/') as $file) {
+        foreach {
+            (new DirectoryIterator('/path/') as $file) {
             if ($file->getExtension() === 'php') {
                 require_once $file->getPathname();
             }
         }
-        return array_filter(get_declared_classes(), function ($class) {
-            return is_subclass_of($class, static::class, true);
-        });
+            return array_filter(get_declared_classes(), function ($class) {
+                return is_subclass_of($class, static::class, true);
+            });
+        }
     }
 }
      ----------- end diff -----------


Checked all files in 0.010 seconds, 8.000 MB memory used
```

Additional info:

```
$ php -v
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
$ php-cs-fixer -V
PHP CS Fixer 2.8.0 Round Numbers by Fabien Potencier and Dariusz Ruminski
```

**Comment by julienfalque** [comment] 2017-11-09 09:59
Thanks for the report. This is a duplicate of #3202 which will be fixed by #3208 (merged and available in next release).

**Closed by julienfalque** 2017-11-09 09:59 UTC
