### ISSUE TITLE
PhpUnitTestCaseIndicator - matches class that is not an unit test

### ISSUE THREAD

**Issue by peter-gribanov** [FriendsOfPHP/PHP-CS-Fixer#5145] opened 2020-09-07 09:09 UTC
### Code snippet that reproduces the problem

The domain object of the questionnaire will be marked as internal.

 ```diff
<?php

++/**
++ * @internal
++ */
final class MyTest
{
    public string $question1;

    public string $question2;
}
```

I think that a good solution for the `php_unit_*` rules would be to explicitly specify the path to the unit tests or resolve it from `phpunit.xml` file.

**Comment by kubawerlos** [comment] 2020-09-14 20:02
Hi @peter-gribanov,

currently, [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Indicator/PhpUnitTestCaseIndicator.php#L23) function decides if a class is treated as PHPUnit test class or not. Maybe it's worth to update it in a way the class must always extend a class with `Test` in name of the parent.

> I think that a good solution for the `php_unit_*` rules would be to explicitly specify the path to the unit tests

That would be really annoying to add the config option to each `php_unit_*` rule, but it could be interesting to see a solution to add some global config value.

> or resolve it from `phpunit.xml` file.

I think it would be a bit too much effort, after all, it is not simply a path to single directory - can be multiple directories and/or files.

**Comment by SpacePossum** [comment] 2020-10-22 12:27
Thanks fro reporting. I think a first quick easy win would to update the PhpUnitTestCaseIndicator `'/(?:Test|TestCase)(?:Interface)?$/'` that both `Test|TestCase` must have at least one character in front of it.

**Comment by SpacePossum** [comment] 2021-09-26 08:56
closing here as duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6016

**Closed by SpacePossum** 2021-09-26 08:56 UTC
Labels: kind/bug, easy pick

**Comment by peter-gribanov** [comment] 2021-09-27 07:25
@SpacePossum older issue turned out to be a duplicate of a newer one?!

**Comment by SpacePossum** [comment] 2021-09-27 11:18
doesn't really matter which of the two stays open does it?

**Comment by peter-gribanov** [comment] 2021-09-27 13:59
No. Doesn't matter. I found it funny.
