### ISSUE TITLE
ClassAttributesSeparationFixer - ['const' => 'none'] removing unexpected whitespaces if including docblocks

### ISSUE THREAD

**Issue by paulbalandan** [FriendsOfPHP/PHP-CS-Fixer#5701] opened 2021-05-07 11:47 UTC
## Bug report

PHP version:
```
PHP 8.0.5 (cli) (built: Apr 28 2021 00:30:18) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

PHP-CS-Fixer version:
```
PHP CS Fixer 3.0.0 Constitution by Fabien Potencier and Dariusz Ruminski
```

Command used:
```
vendor/bin/php-cs-fixer fix -v
```

Relevant configuration:
```
'class_attributes_separation' => [
    'elements' => [
        'const' => 'none',
        'method' => 'one',
        'property' => 'one',
    ],
],
```

### Code snippet that reproduces the problem

case 1:
```diff
 class Foo
 {
     public const BAR = 1;
-
     public const BAZ = 2;

     public static function getX()
     {
         return 'X';
     }
 }
```
Change here is totally expected.

case 2:
```diff
 class Foo
 {
     /** @var int */
     public const BAR = 1;
-
     /** @var int */
     public const BAZ = 2;
-
     /**
      * Defaults
      *
      * @var array<int, string>
      */
     protected array $defaults = [];

     public static function getX()
     {
         return 'X';
     }
 }
```

For case 2, if the const has a doc block, it still strips the whitespaces around it. Then, when the last const is followed by a property with a docblock, the whitespace below the const is also removed.

**Comment by julienfalque** [comment] 2021-05-07 12:04
This is an enhancement I'd like to see as well. #5060 was an attempt to implement it but was abandoned because of lack of interest, maybe you could have a look and help finish it?

**Comment by julienfalque** [comment] 2021-05-22 11:01
Duplicate of #4014.

**Closed by julienfalque** 2021-05-22 11:01 UTC
Labels: kind/feature request
