### ISSUE TITLE
PSR2 fixer is incomplete with respect to argument lists

### ISSUE THREAD

**Issue by mxr** [FriendsOfPHP/PHP-CS-Fixer#1397] opened 2015-09-14 04:12 UTC
I believe the PSR2 level does not implement PSR2 completely - is that a known issue, or a bug?

One example is that function arguments should either all be on one line, or all on separate lines ([§ 4.4](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#44-method-arguments), [§  4.6](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#46-method-and-function-calls)). Additionally, `) {` should be on the same line. For the following code:

```php
<?php

function bar($a,
    $b, $c)
{
    print_r($a);
    print_r($b);
    print_r($c);
}


bar(1,
    2, 3);
```

the command `php-cs-fixer fix example.php --level=psr2` leaves the code untouched. However I would expect it to output each argument on a new line (since some are already on a new line) as follows:

```php
<?php

function bar(
    $a,
    $b,
    $c
) {
    print_r($a);
    print_r($b);
    print_r($c);
}


bar(
    1,
    2,
    3
);
```

I'm using version 1.10.

**Comment by SpacePossum** [comment] 2015-09-24 21:44
thanks for the report, I can confirm this.
(working on this, hope to wrap up a PR soon)

**Comment by mxr** [comment] 2015-09-26 20:39
@SpacePossum thank you very much!!

**Comment by keradus** [comment] 2015-09-26 20:58
Closing as duplicate of #1184.
Also, see #1187

**Closed by keradus** 2015-09-26 20:58 UTC
Labels: feature
