### ISSUE TITLE
Chained method calls counts as blank_line_before_return

### ISSUE THREAD

**Issue by patrickreck** [FriendsOfPHP/PHP-CS-Fixer#3465] opened 2018-01-23 09:59 UTC
#### The PHP version you are using (`$ php -v`):
=> 7.1.10

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.0.0

#### The command you use to run PHP CS Fixer:
=> php php-cs-fixer fix ./app --dry-run --diff --diff-format=udiff --config=.php_cs.dist.php

#### The configuration file you are using, if any:
```php
<?php
namespace OS\CS\Config;

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$finder = Finder::create()->in(__DIR__ . '/app');

return Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        'strict_param' => true,
        'array_syntax' => [
            'syntax' => 'short',
        ],
        'binary_operator_spaces' => [
            'align_double_arrow' => false,
            'align_equals' => false,
        ],
        'blank_line_after_opening_tag' => true,
        'blank_line_before_return' => true,
        'blank_line_before_statement' => true,
        'cast_spaces' => true,
        'class_keyword_remove' => false,
        'combine_consecutive_unsets' => true,
        'concat_space' => [
            'spacing' => 'one',
        ],
        'declare_equal_normalize' => true,
        'declare_strict_types' => false,
        'dir_constant' => false,
        'doctrine_annotation_braces' => true,
        'doctrine_annotation_indentation' => true,
        'doctrine_annotation_spaces' => true,
        'ereg_to_preg' => false,
        'function_to_constant' => false,
        'function_typehint_space' => true,
        'general_phpdoc_annotation_remove' => false,
        'hash_to_slash_comment' => true,
        'header_comment' => false,
        'heredoc_to_nowdoc' => false,
        'include' => true,
        'is_null' => false,
        'linebreak_after_opening_tag' => true,
        'list_syntax' => [
            'syntax' => 'short',
        ],
        'lowercase_cast' => true,
        'mb_str_functions' => false,
        'magic_constant_casing' => true,
        'method_separation' => true,
        'modernize_types_casting' => true,
        'native_function_casing' => true,
        'native_function_invocation' => false,
        'new_with_braces' => true,
        'no_alias_functions' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_blank_lines_before_namespace' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        'no_extra_consecutive_blank_lines' => [
            'break',
            'continue',
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'return',
            'square_brace_block',
            'throw',
            'use',
            'useTrait',
        ],
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        'no_mixed_echo_print' => [
            'use' => 'echo',
        ],
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'no_php4_constructor' => false,
        'no_short_bool_cast' => true,
        'no_short_echo_tag' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_around_offset' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_unneeded_control_parentheses' => true,
        'no_unreachable_default_argument_value' => true,
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'non_printable_character' => true,
        'normalize_index_brace' => true,
        'not_operator_with_space' => false,
        'not_operator_with_successor_space' => false,
        'object_operator_without_whitespace' => true,
        'ordered_class_elements' => false,
        'ordered_imports' => false,
        'php_unit_construct' => false,
        'php_unit_dedicate_assert' => false,
        'php_unit_fqcn_annotation' => true,
        'php_unit_strict' => false,
        'php_unit_test_class_requires_covers' => false,
        'phpdoc_add_missing_param_annotation' => [
            'only_untyped' => false,
        ],
        'phpdoc_align' => false,
        'phpdoc_annotation_without_dot' => false,
        'phpdoc_indent' => true,
        'phpdoc_inline_tag' => true,
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => [
            'type' => 'var',
        ],
        'phpdoc_no_empty_return' => false,
        'phpdoc_no_package' => true,
        'phpdoc_no_useless_inheritdoc' => true,

        'phpdoc_return_self_reference' => true,
        'phpdoc_order' => true,
        'phpdoc_scalar' => true,
        'phpdoc_separation' => true,
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_summary' => true,
        'phpdoc_to_comment' => false,
        'phpdoc_trim' => true,
        'phpdoc_types' => true,
        'phpdoc_var_without_name' => true,
        'pow_to_exponentiation' => false,
        'pre_increment' => true,
        'protected_to_private' => true,
        'psr0' => false,
        'psr4' => false,
        'random_api_migration' => false,
        'return_type_declaration' => true,
        'self_accessor' => false,
        'semicolon_after_instruction' => true,
        'short_scalar_cast' => true,
        'silenced_deprecation_error' => false,
        'simplified_null_return' => false,
        'single_blank_line_before_namespace' => false,
        'single_quote' => true,
        'space_after_semicolon' => true,
        'standardize_not_equals' => true,
        'strict_comparison' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_null_coalescing' => true,
        'trailing_comma_in_multiline_array' => false,
        'trim_array_spaces' => true,
        'unary_operator_spaces' => true,
        'visibility_required' => [
            'const',
            'property',
            'method',
        ],
        'whitespace_after_comma_in_array' => true
    ])
    ->setFinder($finder);
```

Chaining methods counts as a `blank_line_before_return`. I would expect the passing example to fail.

Passes:
```php
    private function myMethod()
    {
        $blob = Model::select('data')
            ->where('a', 'b')
            ->where('c', 'd');
        return $blob;
    }
```

Fails:
```php
    private function myMethod()
    {
        $a = 'b';
        return $blob;
    }
```

**Comment by SpacePossum** [comment] 2018-01-23 10:25
Hi and thanks for reporting,

Are you sure you are using `2.0.0`? 
Asking because `blank_line_before_statement` is within your configuration but that rule does not exists on v2.0.0 (was introduced in v2.4.0 as replacement of `blank_line_before_return` which I would recommend removing from your configuration as it has been deprecated). As such your configuration should not be working with `2.0.0`

On `2.2.0` both samples are fixed by the older `blank_line_before_return`,  on `master` the newer fixer gets both.

```
[11:22 AM]-[possum@zoo1]-[/home/possum/work/PHP-CS-Fixer]-[git master] 
$ php php-cs-fixer fix tmp/test.php --rules=blank_line_before_statement
```

test file content;

```php
class A
{
    private function myMethod()
    {
        $blob = Model::select('data')
            ->where('a', 'b')
            ->where('c', 'd');
        return $blob;
    }

    private function myMethod2()
    {
        $a = 'b';
        return $blob;
    }
}

```

**Comment by julienfalque** [comment] 2021-05-16 13:26
I couldn't reproduce the issue either.

**Closed by julienfalque** 2021-05-16 13:26 UTC
