### ISSUE TITLE
False positive for PhpdocTypesOrderFixer on complex PHPDoc types

### ISSUE THREAD

**Issue by gnutix** [FriendsOfPHP/PHP-CS-Fixer#6195] opened 2021-12-19 12:34 UTC
## Bug report

PhpdocTypesOrderFixer breaks a PHPDoc containing a quite complex type.

### Code snippet that reproduces the problem

```php
final class ConfigKey
{
    public const ACTIVITY__EXPORT__TYPE = '...';
}
final class Module
{
    public const FOO = 'foo';
}
interface ConfigValueProcessorInterface
{
}
interface ConfigRepositoryInterface
{
   /**
    * @var array<ConfigKey::*, array{default: mixed, acl: string[], linked_module?: Module::*, value_processors?: array<class-string<ConfigValueProcessorInterface>, mixed>}>
    */
   public const CONFIGURATIONS = [
       // ...
   ];
}
```

### Current behavior

```diff
@@ -15,7 +15,7 @@
 interface ConfigRepositoryInterface
 {
     /**
-     * @var array<ConfigKey::*, array{default: mixed, acl: string[], linked_module?: Module::*, value_processors?: array<class-string<ConfigValueProcessorInterface>, mixed>}>
+     * @var array<ConfigKey::*, array{default: mixed, acl: string[], linked_module?: Module::*, value_processors?: array<class-string|<|ConfigValueProcessorInterface>, mixed>}>
      */
     public const CONFIGURATIONS = [
         ConfigKey::ACTIVITY__EXPORT__TYPE => [
```

### Expected

No changes.

**Comment by julienfalque** [comment] 2021-12-19 12:56
Closing because I think this is a duplicate of #5921. If not, please let us know.
Also, can you please give #6063 a try and tell us whether it fixes the issue for you?

**Closed by julienfalque** 2021-12-19 12:56 UTC
Labels: kind/bug

**Comment by gnutix** [comment] 2021-12-21 18:12
It does look a lot alike, sorry for the duplicate. I cannot really test it as I'm using PHP-CS-Fixer through ECS, but maybe you could add this line as a test scenario in your PR ?
