### ISSUE TITLE
"php-cs-fixer selfupdate" installed 2.0-DEV

### ISSUE THREAD

**Issue by sebastianbergmann** [FriendsOfPHP/PHP-CS-Fixer#1953] opened 2016-06-04 15:04 UTC
Just did a `php-cs-fixer selfupdate` and that gave me 2.0-DEV:
```
$ php-cs-fixer --version 
PHP CS Fixer version 2.0-DEV by Fabien Potencier and Dariusz Ruminski (d0d76b4)
```
Using the version I got by doing so does not work:
```
$ php-cs-fixer fix       

Fatal error: Uncaught Error: Class 'Symfony\CS\Finder\DefaultFinder' not found in /usr/local/src/phpunit/.php_cs on line 2

Error: Class 'Symfony\CS\Finder\DefaultFinder' not found in /usr/local/src/phpunit/.php_cs on line 2

Call Stack:
    0.0001     373696   1. {main}() /usr/local/bin/php-cs-fixer:0
    0.0349    4166688   2. Symfony\Component\Console\Application->run() /usr/local/bin/php-cs-fixer:37
    0.0359    4367144   3. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application.php:117
    0.0360    4367144   4. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application.php:186
    0.0360    4367144   5. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application.php:791
    0.0361    4369080   6. PhpCsFixer\Console\Command\FixCommand->execute() phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php:256
    0.0372    4478256   7. PhpCsFixer\Console\ConfigurationResolver->resolve() phar:///usr/local/bin/php-cs-fixer/src/Console/Command/FixCommand.php:306
    0.0375    4593872   8. PhpCsFixer\Console\ConfigurationResolver->resolveConfig() phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:219
    0.0377    4602904   9. include('/usr/local/src/phpunit/.php_cs') phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:384
```

**Comment by SpacePossum** [comment] 2016-06-04 15:18
I didn't expect `selfupdate` to update to a non-stable...
The exception thrown is because the configuration file given is good for 1.x but cannot be used for 2.x.
(ref.: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1749).
There are two work arounds I can think of;
- switch back to 1.11 (current stable) (`$ wget http://get.sensiolabs.org/php-cs-fixer-v1.11.phar -O php-cs-fixer`), or;
- update the configuration file to 2.x format (but that would still mean running a non-stable), for ref. how to do that; https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/UPGRADE.md#config-and-finder-classes

**Comment by sebastianbergmann** [comment] 2016-06-04 15:19
Yes, I was quite surprised by `selfupdate` installing an unstable version. I have since reverted to the latest stable.

**Comment by sebastianbergmann** [comment] 2016-06-04 15:23
Turns out I did not revert back to the latest stable as I cannot find that. `http://get.sensiolabs.org/php-cs-fixer.phar` is 2.0-DEV.

As a sidenote, it would really great if downloads of PHP Archives (PHARs) were made available on a site similar to https://phar.phpunit.de/. HTTPS, release archive, Phive metadata. You get the idea :-) Easy to set up using https://github.com/sebastianbergmann/phar-site-generator.

**Comment by SpacePossum** [comment] 2016-06-04 15:31
latest stable is here, hope it helps;
http://get.sensiolabs.org/php-cs-fixer-v1.11.phar 

I would like to see the releases be a bit more organised for downloading and on [HTTPS](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1242) :)

**Comment by keradus** [comment] 2016-06-04 15:37
Thank you @sebastianbergmann for your report.

I already started discussion about it with Fabien. Please be patient.

Closing as duplicate of #1925

**Closed by keradus** 2016-06-04 15:37 UTC

**Comment by zmorris** [comment] 2016-12-12 01:23
Please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1925#issuecomment-266323864 for a full example config that fixes:

`Fatal error: Class 'Symfony\CS\Finder\DefaultFinder' not found`

and is compatible with both `PHP-CS-Fixer 1.x` and `2.x` and works with `Laravel 5.x`.
