### ISSUE TITLE
Incompatible with PHPUnit 6.3.0

### ISSUE THREAD

**Issue by inoas** [FriendsOfPHP/PHP-CS-Fixer#3028] opened 2017-09-07 08:42 UTC
When requiring `PHPUnit 6.3.0` it will require `sebastian/diff ^2.0` whereas even the latest `PHP-CS-Fixer` still requires ` "sebastian/diff": "^1.4",`

**Comment by SpacePossum** [comment] 2017-09-07 08:51
duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2993

**Closed by SpacePossum** 2017-09-07 08:51 UTC
