### ISSUE TITLE
Rule 'binary_operator_spaces' does not support 'no_space' option

### ISSUE THREAD

**Issue by bds-viktoras** [FriendsOfPHP/PHP-CS-Fixer#4267] opened 2019-01-15 17:17 UTC
#### The PHP version you are using (`$ php -v`):
PHP 7.1.1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.14.0 Sunrise

In the documentation it does say:

> **binary_operator_spaces**
> default ('align', 'align_single_space', 'align_single_space_minimal', 'no_space', 'single_space', null): default fix strategy; defaults to 'single_space'

However attempting to set the option to '**_no_space_**' gives the following error:

> The option "default" with value "no_space" is invalid. Accepted values are: "align", "align_single_space", "align_single_space_minimal", "single_space", null.

**Comment by SpacePossum** [comment] 2019-01-17 18:43
Hi @bds-viktoras ,

Thanks for reporting! Currently I cannot reproduce the issue you reported on the current 2.14 branch and also not on the v2.14.0 release tag. Could you provide more details about your setup?

**Comment by OskarStark** [comment] 2019-02-17 13:33
Sounds like you are unsing multiple versions. PHAR and Composer.json for example?

**Comment by SpacePossum** [comment] 2019-10-11 19:39
Closing as we didn't hear back from the reporter, as such there is nothing we can do here.

**Closed by SpacePossum** 2019-10-11 19:39 UTC
Labels: status/input required
