### ISSUE TITLE
Indentation applying wrong for PSR2

### ISSUE THREAD

**Issue by sakonachhoeurng** [FriendsOfPHP/PHP-CS-Fixer#2789] opened 2017-05-22 07:07 UTC
I am using `php7`.
php-cs-fixer is `PHP CS Fixer 2.3.1 by Fabien Potencier and Dariusz Ruminski`
This is before format code
```
 public function findByTagAndBlog(Tag $tag, Blog $blog)
    {
        $query = $this->createQuery();

        return $query->matching($query->logicalAnd($query->equals('blog', $blog), $query->contains('tags',
            $tag)))->setOrderings(array('date' => QueryInterface::ORDER_DESCENDING))->execute();
    }
```
After I use `php-cs-fixer` by this command `php-cs-fixer fix /path/to/project --rules=@PSR2`
```
 public function findByTagAndBlog(Tag $tag, Blog $blog)
    {
        $query = $this->createQuery();
        return $query->matching(
                $query->logicalAnd(
                    $query->equals('blog', $blog),
                    $query->contains('tags', $tag)
                )
            )
            ->setOrderings(array('date' => QueryInterface::ORDER_DESCENDING))
            ->execute();
    }
```
actually, after reformat code It is indentation 8 spaces not for 4 spaces

**Comment by keradus** [comment] 2017-05-22 09:58
body method was indented for `{`. probably we don't have feature to normalize `{`

**Comment by sakonachhoeurng** [comment] 2017-05-22 10:00
@keradus not for `{`
it has problem as code below 
```
 $query = $this->createQuery();
        return $query->matching(
                $query->logicalAnd(
                    $query->equals('blog', $blog),
                    $query->contains('tags', $tag)
                )
            )
            ->setOrderings(array('date' => QueryInterface::ORDER_DESCENDING))
            ->execute();
```

**Comment by keradus** [comment] 2017-05-22 10:18
now, you have provided 3rd version of code... no idea now what is the outcome you got...

**Comment by sakonachhoeurng** [comment] 2017-05-23 01:41
I think my code should display like this after fix from php-cs-fixer
----------------------------------------------------------------------------------------
```
 public function findByCategoryAndBlog(Category $category, Blog $blog)
    {
        $query = $this->createQuery();
        return $query->matching(
            $query->logicalAnd(
                $query->equals('blog', $blog),
                $query->equals('category', $category)
            )
        )
        ->setOrderings(array('date' => QueryInterface::ORDER_DESCENDING))
        ->execute();
    }
```

**Comment by julienfalque** [comment] 2021-05-16 13:00
I couldn't reproduce this, I assume it has been fixed since its report so I'm closing. If it still happens, please submit a new issue.

**Closed by julienfalque** 2021-05-16 13:00 UTC
Labels: status/to verify
