### ISSUE TITLE
Release 3.0.1 break `phpdoc_types_order` rule

### ISSUE THREAD

**Issue by drupol** [FriendsOfPHP/PHP-CS-Fixer#5834] opened 2021-08-03 09:18 UTC
Since 3.0.1 `phpdoc_types_order` is broken.

Here's what it tries to do:

```diff
-     * @param callable(iterable<TKey, T>): iterable<TKey, T> ...$callbacks
+     * @param callable(iterable<TKey, <|T>): iterable|TKey, T> ...$callbacks
```

I'm going to bisect to find which commit introduced the issue and I'll update this post.

**Comment by kubawerlos** [comment] 2021-08-03 09:29
This looks like a duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5832.

**Closed by kubawerlos** 2021-08-03 09:29 UTC
Labels: kind/bug
